### ISSUE TITLE
Peptide sequence is an empty string

### ISSUE THREAD

**Issue by erprateek** [suhrig/arriba#100]
Hi Sebastian,

Congratulations on the publication! That is great news and quite the date for acceptance as well!

My issue today is regarding an empty string value in peptide_sequence column in the sample_name.fusions.tsv file. I read through Arriba documentation and concluded that the value presented in the peptide_sequence column should either be a legitimate sequence or a '.'. However I ran across an interesting edge case today where the peptide_sequence showed up to be an empty string instead. Here are two consecutive records from the outputs. Could you help isolate the problem here?

[Arriba_issue.txt](https://github.com/suhrig/arriba/files/5884246/Arriba_issue.txt)

This was run with Arriba v1.2.0 and STAR 2.7.3a

Hope this helps in diagnosing the issue.

**Comment by suhrig** [comment]
Hi Prateek,

Thanks for bringing this to my attention. I wasn't aware of this and can confirm that the column should never be empty and should at least contain a dot. Going through my own test data I found some edge cases myself (2 out of 10000). So I can debug the issue without further help from you. I will report back when I have found a solution.

As a hotfix, you could patch the source code of Arriba 1.2.0. If you insert the following code before [this line](https://github.com/suhrig/arriba/blob/ca1d40b0575e958243fe2e7fd28acd54de038349/source/output_fusions.cpp#L972), the peptide sequence should never be empty:

```
if (peptide_sequence.empty()) peptide_sequence = ".";
```

Regards,
Sebastian

**Comment by suhrig** [comment]
This bug is triggered, when the breakpoint of gene1 is in the 5' UTR and the breakpoint of gene2 is in the 3' UTR or an intergenic region. I am surprised it occurs so rarely. Anyhow, the hotfix I sent to you is not just a hotfix, it is the actual solution. I will push it to GitHub soon.

BTW, the second sequence you sent me contains lots of `?`. I believe this was a bug in older versions of Arriba, when the `HardClip` parameter of STAR was used. If you use `SoftClip` (or update to a newer Arriba version), sequences with many question marks should not occur as often anymore (if ever).

**Comment by suhrig** [comment]
Hi Prateek, I pushed the fix to the `develop` branch. So it will be fixed in the next release. Thanks again for reporting!

**Comment by erprateek** [comment]
Great thanks very much! Ill patch it right away.
