### ISSUE TITLE
known_fusions with min_support filter

### ISSUE THREAD

**Issue by erprateek** [suhrig/arriba#101]
Hi Sebastian,

I have a case of a known fusion event in a sample for which Arriba is able to detect only 1 read of evidence. I have this fusion event in a known_fusions file and supply it to arriba. Nevertheless, the fusion event lands in the discarded file with only a min_support filter tag in the row. I thought the whole point of known_fusions was to disable filtering application to bias it on the side of sensitivity. Is that not the case? In worst case, I can mine the discarded file using the known_fusions file to ensure Arriba did not discard the event but thought of asking first.

Example event in discarded file:

> sample.fusions.discarded.tsv:EGFR	SEPT14	+/+	-/-	7:55268106	7:55863785	splice-site	splice-site	inversion	downstream	downstream	0	1	0	104	13	low	.	.	min_support	.	..	.	.	.

**Comment by suhrig** [comment]
Hi Prateek,

Normally, the `known_fusions` filter is triggered only when there are at least 2 supporting reads linking a pair of genes. Otherwise, the false positive rate would be too high. This is already more sensitive than the default, because the `relative_support` often requires that there be 3 or 4 or even more reads. So the real purpose of the `known_fusions` filter is to override the `relative_support` filter. Since version 1.2.0, there is another situation where it triggers (overriding the `min_support` filter even), namely when both breakpoints are at splice sites and the coverage is not too high. This is the case with your EGFR fusion. However, there is an exception for genes in proximity (i.e., less than 1Mbp apart), because again, there would be too many false positives. So your fusion of interest is discarded in the end.

The good news is that since version 2.0.0, the known fusions file can be enhanced in a way that fusions can be rescued regardless of read support: If you specify exact breakpoint coordinates in both columns, then the `known_fusions` filter recovers the event even if it has just 1 supporting read. This new feature can be utilized in a meaningful way by specifying recurrent breakpoint coordinates. Most oncogenic fusions have preferences for very specific breakpoint coordinates, such that certain exons are fused together. For example, BRAF likes to have its breakpoint at the boundary of exon 8 or 9, and the fusion partner typically has a preference for an exon boundary that yields an in-frame fusion. So if you specify the common breakpoints of EGFR and SEPT14 in the known fusions file, there is a good chance that Arriba will report it even with just one read. Note that this method only really works in practice when the typical breakpoints are at splice sites. Otherwise you would have to specify all combinations of all bases of the fusion partners, which would miss the purpose of this feature.

Regards,
Sebastian

**Comment by erprateek** [comment]
Thanks Sebastian for the fix! Since this issue is fixed in the current 2.0.0, I haven't changed my local checkout of 1.2.0 to mimic this behavior. Instead im currently doing a post calling rescue from discarded events if a fusion from whitelist is discarded only due to min_support. I hope we can upgrade the system wide installation to 2.0.0 sometime in 2021.

**Comment by suhrig** [comment]
Alright. Let me know if you need help with that. Be sure to check out the [release notes](https://github.com/suhrig/arriba/releases/tag/v2.0.0) for changes that are incompatible with previous versions and might require adaptations in your scripts, hence.
