### ISSUE TITLE
Changing blacklist to removelist/denylist/filterlist etc.

### ISSUE THREAD

**Issue by Gaura** [suhrig/arriba#102]
Hi @suhrig! 

arriba is a great tool. Can you consider changing the term blacklist to removelist/denylist/filterlist or something else that does not have [racial connotations](https://www.cnn.com/2020/07/06/us/racism-words-phrases-slavery-trnd/index.html)? Github changed the default principal branch name from "master" to "main" as well. This would be an inclusive change and wouldn't change the functionality. 

Thank you!

Best,
Gaurav

**Comment by suhrig** [comment]
Hi Gaurav,

I'm glad you find the tool useful. My apologies if the term "blacklist" offended you or anyone else. To be honest, I did not think twice when implementing it, because never in my life did I make the connection to a racial context. (Is that even where the term comes from?) Then again, I'm white, so my perspective may not be relevant here.

I will consider it, but in general I like to keep the user interface as stable as possible, because I don't want to break existing pipelines and scripts that already make use of the parameter `-b` or files named `blacklist_...`. For that reason, this change will certainly not happen before the release of the next major version of Arriba (which is not even scheduled yet).

I cannot rename or delete the master branch, sorry. This would break the repository.

Regards,
Sebastian

**Comment by Gaura** [comment]
Thank you for considering the change, Sebastian. I personally find it uncomfortable to use that term and I know many do too. I understand your perspective, many terms are so commonly used that we use them without a second thought. Gradually, we are seeing a change in the use of terms. This was the reason I mentioned that Github changed the name of the principal branch to main and many companies did that too. One primary reason being that it is has slavery-era connotations. I was not suggesting you do that, it was another example where we see change in language. Apologies for not being clear earlier. 

I should have clarified that the suggestion was for the next version, whenever that it, exactly because of the reason you mentioned. 

Thanks for being open about it, Sebastian. 

Should I keep the issue open until the next version or should I close it?

**Comment by suhrig** [comment]
> I was not suggesting you do that, it was another example where we see change in language.

Ah, I see.

> I should have clarified that the suggestion was for the next version, whenever that it, exactly because of the reason you mentioned.

I don't see real obstacles to changing the name with the next major release.

> Should I keep the issue open until the next version or should I close it?

I already made a note on my todo list. Consider it solved. :-D So I'm closing this.
