### ISSUE TITLE
Duplication or Circular RNA Ambiguity

### ISSUE THREAD

**Issue by DarioS** [suhrig/arriba#103]
A split read going from the end of exon 4 to the beginning of exon 2 could indicate a duplication or alternatively a circular RNA if the input data is total RNA-seq, which sequences RNA molecules without a tail. Is there a way to distinguish these two possibilities?

**Comment by suhrig** [comment]
You're absolutely right. It could be the result of circular splicing - which is much more abundant than exon duplications. That is precisely the reason why they are tagged as `non-canonical-splicing` by Arriba. In rare cases this can even happen between neighboring genes. If you have DNA-Seq you can look for a structural variant confirming the duplication. If there is no confirmation it's likely circular splicing. Up until now I thought that it is impossible to distinguish the two types of events on the transcriptome level. But now that you bring it up again, there actually is a way. You have to be lucky, but it should be possible. Your "luck" is dependent on the read length (or fragment length in case of paired-end data) and the size of the duplication. The former must be bigger than the latter. You need to find a fragment that is big enough to span both breakpoints. In case of a circular RNA the fragment will be clipped at both breakpoints; in case of a tandem duplication only one end of the fragment will be clipped. Thanks for bringing this to my attention again. I will have a look into this. Maybe this approach really works in practice. Then I could implement it in Arriba and improve the ranking of fusion predictions by confidence. I would not go as far as to remove all circular RNAs, because they could still be interesting even if they are not the result of a genomic rearrangement. However, I could remove the `non-canonical-splicing` tag from events that are for sure duplications and I could rank them higher. I am a bit busy at the moment, but I will get back to you once I have some insights.

**Comment by DarioS** [comment]
Ah, of course! I checked the genome segmentation and there is a duplication listed by PURPLE surrounding those exact exons.

**Comment by suhrig** [comment]
Glad you could figure it out.

I looked into the idea of distinguishing exon duplications from circular splicing by searching for split reads that reach beyond the other breakpoint. It was very quick to implement. However, you have to be reeeeeally lucky. Most duplications involve more than one exon and the breakpoints are much farther apart than the read length, hence. So this does not work in practice. SVs or CNAs from DNA-Seq are the only real answer.
