### ISSUE TITLE
Annotation file influence in the discovery of non-annotated Fusions

### ISSUE THREAD

**Issue by Bsguerraa** [suhrig/arriba#107]
First of all, thanks for such a great tool! Your job here is outstanding! I've been working with Chimeras in RNA-seq in my PhD and your tool is by far the most complete and comprehensive I've found so far! 

Ok, so here is my question and I hope you can help to give me some insights:
- I'm trying to identify new chimeras from non-cancer tissues, I have plenty of RNA-seq data PE 100bp and I want to know the influence of the annotations files (.GTF) in the exclusion of possible true candidates non-annotated yet. Does STAR or ARRIBA exclude this type of read?
- I'm trying to run STAR with a different combination of parameters without the annotation, trying to boost the junction read discovery, like TwoPass modes. How do you think this should influence the ARRIBA pipe-line? 
- What kind of Parameters for STAR and Filters in ARRIBA do you think is a good idea to change to address my objective? I know that in my research the number of false-positive going to be high, maybe there isn't much I can do since I'm trying something new.

**Comment by suhrig** [comment]
Thanks for the positive feedback! I'm glad you find the tool useful.

> the influence of the annotations files (.GTF) in the exclusion of possible true candidates non-annotated yet

Generally speaking, I recommend to use a GTF file with comprehensive annotation. GENCODE is a good source. In contrast, RefSeq lacks a lot of transcripts and quite a few genes, too.

If you are interested in chimeras involving at least one annotated gene, then you have nothing to worry about. As long as one of the breakpoints hits an annotated gene, it will be reported - even if the other breakpoint is in an intergenic region.

If you are also interested in chimeras with both breakpoints in intergenic regions, then your concern that non-annotated genes may lead to false negatives is justified. Arriba does not report fusions with both breakpoints in intergenic regions or deep inside introns. Using an annotation with comprehensive annotation is one way to reduce the risk of breakpoints being considered intergenic. If you have major concerns about this, you can try disabling the respective filter using `-f intronic`. You will see more false positives, however.

> I'm trying to run STAR [...] without the annotation

I suspect this will impair alignment, because STAR will have a harder time finding spliced alignments. Also, it may lead to more false positives, because a read that would normally be mapped to an annotated gene as a spliced alignment might then be mapped to a (spliced) pseudogene or elsewhere in the genome, which can lead to spurious chimeric alignments. For this reason, I would not omit the annotation when building the STAR index. It is useful information for alignment.

> TwoPass modes. How do you think this should influence the ARRIBA pipe-line?

TwoPass mode may be the better option to boost the discovery of novel junction sites. I have to admit, though, that I do not know if chimeras are even considered for de novo junction discovery in TwoPass mode. I think it is only used for discovery of linearly spliced junctions. So it will predominantly help in the discovery of cis-spliced read-through fusions. In my experience, TwoPass mode improves chimera detection only marginally, if at all, and therefore I do not use it.

> What kind of Parameters for STAR and Filters in ARRIBA do you think is a good idea to change to address my objective?

You should know that Arriba makes use of a blacklist that removes chimeras observed in benign tissue. But these may just be the events that you are interested in if I understand you correctly (???). You can disable the blacklist using `-f blacklist`. The most apparent effect will be lots of read-through fusions, since these are very abundant in every tissue. If you don't care about read-through fusions, you can remove them by means of the `read-through` tag in the `type` column. Quite likely, you will want to be even more strict than that. Arriba tags read-through fusion with a breakpoint distance of 400kb as `read-through`. There are many read-through fusions with longer distance, however. So you could increase this to 700kb or even 1Mb. There is no parameter to do this. You will have to compute the breakpoint distance yourself from the columns `breakpoint1/2` and remove anything annotated as a `deletion` within this distance. The second most apparent effect of disabling the blacklist will be local trans-spliced chimeras, i.e., splicing between genes on opposite strands in close proximity (or back-splicing). If you don't care about these either, I recommend removing *everything* within a distance of 700kb or possibly even within 1Mb. The downside of disabling the blacklist is that it will increase the number of false positives, because the blacklist also removes recurrent alignment artifacts.

**Comment by suhrig** [comment]
I'm closing this issue for now, as it looks to me like your questions have been answered. Don't hesitate to come back and reopen the issue if you have more questions!
