### ISSUE TITLE
Running arriba with cleandata?

### ISSUE THREAD

**Issue by byemypast** [suhrig/arriba#108]
Hi Sebastian,
Really appreciate for your great work! Arriba performs better than any other software in my subject.
I am not familiar with the STAR , so I wonder if it's suggested that using data-cleaning/trimming tools before STAR-Arriba protocol?

Thank you & Have a nice day

Best Regards,
Junyi

**Comment by suhrig** [comment]
Hi Junyi,

Thank you for the positive feedback!

I assume by cleaning data you mean: trimming adapters, trimming `N`s, trimming low-quality bases. STAR can do clipped alignments. In my experience, it is usually not necessary to perform trimming prior to alignment, because STAR will simply clip the part of the read that it cannot align.

However, I do recommend to trim in extreme cases. In the following, I will mostly talk about adapters, but the same is true for `N`s or low-quality bases at the end of reads. When the insert size is small, such that the adapters make up a substantial fraction of the read, you should trim before alignment, because otherwise STAR will discard the read as unmappable with the reason `too short`, because it can align just a short part of the read. This can impair fusion detection. Fusion-supporting reads are particularly hard to align in such a scenario, because in addition to the difficulty of finding a chimeric alignment, STAR also has to deal with the adapter. STAR only reports a chimeric alignment when a big fraction of both parts of a chimeric read aligns to the genome. This is not given when an adapter makes up a big fraction of the read.

I suggest you have a look at your data. If the average insert size is smaller than the read length, it is probably better to trim. Likewise, if you see many `N`s at read ends in a notable fraction of your sample, you better trim them. Low-quality bases are usually less of a concern in my experience. They would have to be really bad for STAR to become a problem. So trimming is usually not necessary here.

Note that when the insert size is so small that mate1 and mate2 basically overlap fully, you will run into a bug in STAR which will cause about 50% of the chimeric reads to be lost. See issue #97. In this case, it is best to align only mate1 of the fully overlapping reads in single-end mode, which avoids the bug. Mates which do not fully overlap should still be aligned in paired-end mode as usual. I filed a bug report with the developer of STAR. Hopefully, it will be fixed with the next release.

Regards,
Sebastian

**Comment by byemypast** [comment]
Thank you for your detailed suggestion!

Cheers,
Junyi
