### ISSUE TITLE
not finding contigs with mouse reference

### ISSUE THREAD

**Issue by anoronh4** [suhrig/arriba#109]
i am trying to run arriba with a mouse sample and a mouse genome like so:
```
arriba \
-x star.bam \
-a genome.fa \
-g annotation.gtf  \
-f blacklist  \
-o fusions_arriba.tsv \
-O fusions_discarded_arriba.tsv \
-T -P
```
i am running on linux in a singularity container, and this has worked fine for human so far. With mouse I am running into issues. I have disabled the blacklist, and i confirmed that my reference STAR directory, fasta and annotation are truly mouse. my log is as follows:
```
$ cat work/8e/9f261440e50b6714a680455fa7e092/.command.log
[2021-04-03T21:18:03] Loading annotation from 'annotation.gtf'
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
WARNING: gene ID 'ENSMUSG00000092329' appears to be non-unique and will be ignored
[2021-04-03T21:18:09] Loading assembly from 'genome.fa'
ERROR: could not find sequence of contig '21'
```
(as you may know, mouse only has 20 chromosomes, so erroring out at 21 hints that it's looking for human chromosomes). how can i get this running for non-human genomes?

**Comment by suhrig** [comment]
Hi,

Which version of Arriba are you using? The options `-T` and `-P` are from older Arriba versions (1.x). Mouse data has been officially supported only since version 2. There are ways to get things working with version 1 if you are obliged to stick to this version for certain reasons, but the easiest way would be to update to the latest version. With the latest version, you can create a STAR index for the mouse genome `mm10` using the following command. (You can skip this step, if you already have an index, assembly, and annotation, but the file names must conform to expected patterns, or else the singularity image won't find them. So for a smooth experience it may be better to just run this command.)

```
mkdir /path/to/references
singularity exec -B /path/to/references:/references docker://uhrigs/arriba:2.1.0 download_references.sh mm10viral+GENCODEM25
```

Once the index has been built, you can run Arriba as follows:

```
singularity exec \
       -B /path/to/output:/output \
       -B /path/to/references:/references:ro \
       -B /path/to/read1.fastq.gz:/read1.fastq.gz:ro \
       -B /path/to/read2.fastq.gz:/read2.fastq.gz:ro \
       docker://uhrigs/arriba:2.1.0 \
       arriba.sh
```

That's it. This should work.

Regards,
Sebastian

P.S. If you must use version 1 or if you want to use your own index/annotation/assembly instead of having the script `download_references.sh` create them for you, let me know. I can help you get things working.

**Comment by anoronh4** [comment]
Thanks, we were using 1.2. We should be able to upgrade and use the solution you mentioned for this case, although it looks like we can just copy/reference the blacklist from `database` folder of that container. arriba completed with the references that i provided without issue... i ran STAR separately in this case. 

Thanks for your response, both helpful and fast!

**Comment by suhrig** [comment]
As things seem to be working for you now, I am closing this issue. Don't hesitate to reopen it if you have more trouble/questions.
