### ISSUE TITLE
Error: package or namespace load failed for ‘GenomeInfoDb’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):  there is no package called ‘GenomeInfoDbData’

### ISSUE THREAD

**Issue by lmckinney2020** [suhrig/arriba#111]
I am writing to see if there have been others who face the error above. I check to see if I had the dependencies "GenomicRanges, GenomeInfoDb, and circlize' installed and updated. They are. Assistance with getting draw_fusions.R to run would be appreciated. 
-----
draw_fusions.R --../genome/Annotation/gencode.v36.primary_assembly.annotation.gtf.gz --fusions=../test/SRR8312111/arriba_outdir/SRRXXXXXXX.fusions.tsv --output=SRRXXXXXXX.output.pdf --cytobands=../arriba/cytobands_hg38_GRCh38_v2.1.0.tsv --proteinDomains=../var/lib/arriba/protein_domains_hg38_GRCh38_v2.1.0.gff3 --squishIntrons=TRUE --printExonLabels=TRUE --render3dEffect=TRUE --pdfWidth=11.692 --pdfHeight=8.267 --color1=#e5a5a5 --color2=#a7c4e5 --mergeDomainsOverlappingBy=0.9 --optimizeDomainColors=FALSE --fontSize=1 --showIntergenicVicinity=0 --transcriptSelection=coverage

**Comment by suhrig** [comment]
According to the error message, the problem is not the package `GenomeInfoDb`, but one of its dependencies: `GenomeInfoDbData`. Have you checked if the latter is installed, too? If not, can you install it like so:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("GenomeInfoDbData")
```

If this is indeed the problem, then it's strange that the dependency is not installed automatically. This could be a bug in Bioconductor. Can you give me more details about your environment? What is the exact Linux version and R version that you are using?

BTW there is an error in your command. The first argument should read `--annotation=../genome/Annotation/...`. I don't think this is related to the error about the package, but you should fix this as well.

**Comment by lmckinney2020** [comment]
Thanks for your reply. 

I am using 
- Linux: 3.10.0-1160.2.1.el7.x86_64 GNU/Linux
- R: v3.6.1

I am confused as to how installing BiocManager locally in R will help with me running the draw_fusions.R package in Linux using an HPC. May you provide further clarification?

Thank you for catching the missing annotation flag. I will update it.

**Comment by suhrig** [comment]
That's just how Bioconductor packages are installed, see here: https://bioconductor.org/packages/release/data/annotation/html/GenomeInfoDbData.html

You can skip the installation of BiocManager if it is already installed.

The Linux kernel looks like it is from RedHat or CentOS. Can you post the content of `/etc/redhat-release` or `/etc/centos-release`? This would help me set up a similar system to reproduce the issue.

**Comment by lmckinney2020** [comment]
Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by lmckinney2020** [comment]
Everything appears to be working now. I just need to update R to version 3.6.3 to utilize the package "circlize"

Thank you! You've been very helpful!
