### ISSUE TITLE
arriba for hg38

### ISSUE THREAD

**Issue by deb0612** [suhrig/arriba#112]
Dear sir,
I noticed that when installing arriba, it will use hs37d5viral+GENCODE19 as reference.
What your suggestion? if I need to apply arriba to grch38 reference sequence.

**Comment by suhrig** [comment]
You can specify the assembly/annotation when you run the script `download_references.sh` with the respective argument. For example, when you run `download_references.sh GRCh38viral+GENCODE28`, it will install GRCh38. Run the script without an argument to see all available options. You are not bound to these options, however. So if the given options do not suit your preferences, you can also create a STAR index on your own and use that. Note that if you use Singularity/Docker, the file names of the reference files must stick to expected patterns, or else Arriba won't find them. If you use the manual installation than the files can be named however you want, because you explicitly state their names when running Arriba.

**Comment by deb0612** [comment]
thanks. It works!

**Comment by suhrig** [comment]
In case you have not found it yet, here is some useful information about how to install/run Arriba:

https://arriba.readthedocs.io/en/latest/quickstart/

Check out the other sections of the manual as well if you want. There is plenty of information there about all aspects of Arriba.
