### ISSUE TITLE
Arriba for targeted RNAseq

### ISSUE THREAD

**Issue by kvaldez** [suhrig/arriba#114]
Hi, thank you for creating this tool, I am currently using it with an RNAseq pipeline and I'm happy with the results (especially the visualizations).

I'm also running a TSO500 pipeline where each fastq includes ~50+ genes.  Do you foresee any issues with running Arriba on this type of targeted RNAseq data?

Thanks,
Kristin

**Comment by suhrig** [comment]
Hi Kristin,

This works. I have received positive feedback from multiple sources.

I should mention though, that Arriba was developed for unbiased sequencing. Focal, very deep sequencing depths as in targeted sequencing do not match Arriba's model of the coverage distribution. Estimation of the background noise does not work as well here, which means you will see some more false positives. You probably want to ignore low-confidence fusions altogether. Moreover, you should be aware that the panel only covers cancer-relevant genes. So every reported fusion prediction will affect a potentially interesting gene. You should apply some common sense whether the fusion actually makes sense in the given cancer type. For example, some panels include SLC45A3-ELK4. This fusion is primarily relevant to prostate cancer. It does not make so much sense in the context of other cancer types. Yet it shows up in many samples, because it is a read-through fusion that is also seen in benign tissue and because panels over-amplify even slightly expressed transcripts. Generally speaking, the false positives you will find will mostly affect neighboring genes, because the close proximity of genes gives rise to random cis-/trans-spliced transcripts, which are amplified by the panel to higher levels than one would expect with untargeted RNA-Seq. So you should be careful whenever a fusion has breakpoints in close proximity.

Lastly, I recommend using the parameter `-u` to enable external duplicate marking instead of using Arriba's internal duplicate. I guess your fragments are probably tagged with UMIs. Arriba is oblivious to UMIs. It marks duplicates solely based on the fact that reads have identical mapping coordinates. So it may discard reads with unique UMIs as PCR duplicates. It is better to perform duplicate marking yourself based on the UMIs prior to running Arriba. The parameter `-u` tells Arriba to not do its own detection of duplicates and instead rely on duplicates being marked as such in the BAM file.

Regards,
Sebastian

**Comment by kvaldez** [comment]
Thanks Sebastian, this is super helpful.

Kristin
