### ISSUE TITLE
Some fusions are reported with no support at all

### ISSUE THREAD

**Issue by af8** [suhrig/arriba#115]
Hi,

I have the following fusion reported with no split reads nor span reads support :

```
AGAP5	BMS1P4	-/-	-/-	chr10:73692043	chr10:73713332	CDS/splice-site	exon/splice-site	duplication	0	0	0	128	134	low	out-of-frame	.	.	.	.	ENSG00000172650.13	ENSG00000271816.1	ENST00000581191.5	ENST00000580790.1	upstream	downstream	mismatches(2)	GTTGTAGAAATAAGAAGAAGCAACTGTACAAACCAT|TGTCAGAGATGGCTTTGGATTCCCCGTTCTGTGTGCTGtTGTCTGGCTCCTGAACCCAGCTGTAGAGGTGTGTCAATCCCAACTGGTGAAGTACTGAGAGGAAGCTACACAAAAGGCAGCAAAGTATTA___GTGAGTGGTGTCATTGAGCAAACACGAAGTCGGGCTCATCCAAGGATGAGATTTTGCCAGAGAAAGGACGAGCA	VVEIRRSNCTNH|cqrwlwiprsvccclapepscrgvsiptgevlrgsytkgskvlvsgvieqtrsrahprmrfcqrkde	A00710:101:HYLJKDRXX:1:2105:31331:34115,A00710:101:HYLJKDRXX:1:2268:28067:2503
```

Is there a particular reason for such a fusion to be reported or is this a bug ?

Note : There are two others entries with this fusion but with different pairs of breakpoints.
```
AGAP5--BMS1P4 | chr10:73694736/chr10:73713332
AGAP5--BMS1P4 | chr10:73692043/chr10:73705078
```

Thanks,
Anthony

**Comment by suhrig** [comment]
Hi Anthony,

> I have the following fusion reported with no split reads nor span reads support :

Arriba's filters remove some alignments that the filters consider to be alignment artifacts (e.g., duplicates). These are not counted in the columns `split_reads1`, `split_reads2`, and `discordant_mates`. In some cases, all reads are removed, leaving a value of 0. Normally, such fusions are not reported in the final output file, but there are filters which rescue discarded fusions. So in the end, an event with 0 good alignments may show up in the final output file. The number of removed alignments is listed in the column `filters` in parentheses for each filter. In your example, there are two reads which were removed, because they have too many mismatches.

> There are two others entries with this fusion but with different pairs of breakpoints.

When a fusion has multiple transcript isoforms, all of them are reported. Basically, Arriba extracts all fusions with breakpoints at splice sites. Usually, you will find one that is expressed at a high level (the relevant one), and some additional isoforms that are expressed at a low level. The reason why all transcript isoforms of a fusion are reported - even though only one of them is biologically relevant - is that it increases the confidence of the fusion call. If you see multiple isoforms, it means the spliceosome must have been involved, which is a strong indication that this transcript truly existed in the cells being sequenced. This does not always mean that the fusion is the consequence of a genomic rearrangement, however. In your example, the breakpoints are very close to each other. If the expression of all breakpoints is low, then possibly, this is a splicing error which produced backspliced transcripts. You need additional evidence (such as structural variant calls from whole-genome sequencing) to distinguish a genomic rearrangement from a mere splicing error.

Regards,
Sebastian

**Comment by af8** [comment]
Thanks a lot for the fast answer and detailed explanation.
