### ISSUE TITLE
Identical fusion reported with different support values

### ISSUE THREAD

**Issue by af8** [suhrig/arriba#116]
Hi, 

I am using Arriba among other callers in a clinical setting and I try to aggregate results of the different results produced in a summary file. To do so my strategy is currently to consider as an identical fusion fusions for which gene partners and chromosomal breakpoints are the same. I came across the fusion described below `AC092431.1(7024),ANXA4(21103)--ANXA4` which is reported twice with the exact same breakpoints but with different support values.  I can see also some differences in `filters` and `fusion_transcript` but I am not sure how to interpret that.

```
AC092431.1(7024),ANXA4(21103)	ANXA4	./+	+/+	chr2:69720871	chr2:69781520	intergenic	5'UTR/splice-site	deletion/read-through	1	2	5	25	99	low	.	.	|Annexin(100%)	.	.	.	ENSG00000196975.16	.	ENST00000394295.6	downstream	upstream	duplicates(1)	GCTGAGGGCGGGGATGGACTGTGTGATTTGCATCTGCCAAATGCAGAAAATTTGGAAG___TTCACAGCCTCTTAGTTGGATGCCCCTGTGTCACAGAACACATTTTGGCTATGGGGTGTGATCTGTGTCTGAGGAACAACAAGAAGCTACACG...CCTAAAACCACGCTACCGAAAGTGTTGATCCACAAACCAGTGCCAGTGCTTGAACTTTGTTACTGGTCCACAGTTAG___GTCCCCTCAGTGATTCCTGTGTGCACCCAGGGTTGAGAACTACTGCATAAGAGGTCCTAGAAGATATCTGGTATGGCCAGAGTACAGAGGGACCGGAG|AAGAACTTCTGCTTGGGTGGCTGAACTCTGATCTTGACCTAGAGTCATGGCCATG___GCAACCAAAGGAGGTACTGTCAAAGCTGCTTCAGGATTCAATGCCATGGAAGATGCCCAGACCCTGAGGAAGGCCATGAAAGGGCTCG___GCACCGATGAAGACGCCATTATTAGCGTCCTTGCCTACCGCAACACCGCCCAGCGCCAGGAGATCAGGACAGCCTACAAGAGCACCATCGGCAGG___GACTTGATAGACGACCTGAAGTCAGAACTGAGTGGCAACTTCGAGCAGGTGATTGTGGGGATGATGAtGCCC	.	A00710:97:HWTWMDMXX:2:1353:10926:30906,A00710:97:HWTWMDMXX:2:1353:11035:30937,A00710:97:HWTWMDMXX:1:2267:21811:17785,A00710:97:HWTWMDMXX:2:2180:29930:7044,A00710:97:HWTWMDMXX:1:1347:6858:12524,A00710:97:HWTWMDMXX:1:1445:9959:30733,A00710:97:HWTWMDMXX:1:2382:8359:18693,A00710:97:HWTWMDMXX:1:2444:18647:14653,A00710:97:HWTWMDMXX:2:2437:20672:36260
AC092431.1(7024),ANXA4(21103)	ANXA4	./+	+/+	chr2:69720871	chr2:69781520	intergenic	5'UTR/splice-site	deletion/read-through	5	3	1	25	99	low	.	.	|Annexin(100%)	.	.	.	ENSG00000196975.16	.	ENST00000394295.6	downstream	upstream	duplicates(2)	GCTGAGGGCGGGGATGGACTGTGTGATTTGCATCTGCCAAATGCAGAAAATTTGGAAG___TTCACAGCCTCTTAGTTGGATGCCCCTGTGTCACAGAACACATTTTGGCTATGGGGTGTGATCTGTGTCTGAGGAACAACAAGAAGCTACACG...CCTAAAACCACGCTACCGAAAGTGTTGATCCACAAACCAGTGCCAGTGCTTGAACTTTGTTACTGGTCCACAGTTAG___GTCCCCTCAGTGATTCCTGTGTGCACCCAGGGTTGAGAACTACTGCATAAGAGGTCCTAGAAGATATCTGGTATGGCCAGAGTACAGAGGGACCGGAG|AAGAACTTCTGCTTGGGTGGCTGAACTCTGATCTTGACCTAGAGTCATGGCCATG___GCAACCAAAGGAGGTACTGTCAAAGCTGCTTCAGGATTCAATGCCATGGAAGATGCCCAGACCCTGAGGAAGGCCATGAAAGGGCTCG___GCACCGATGAAGACGCCATTATTAGCGTCCTTGCCTACCGCAACACCGCCCAGCGCCAGGAGATCAGGACAGCCTACAAGAGCACCATCGGCAGG___GACTTGATAGACGACCTGAAGTCAGAACTGAGTGGCAACTTCGAGCAGGTGATTGTGGGGATGATGACGCCCACGGTGCTGTATGACGTGCAAGAGCTGCGAAGGGCCATGAAG___GGAGCCGGCACTGATGAGGGCTGCCTAATTGAGATCCTGGCCTCCCGGACCCCTGAGGAGATCCGGCGCATAAGCCAAACCTACC	.	A00710:97:HWTWMDMXX:1:1184:8838:1485,A00710:97:HWTWMDMXX:1:2146:24108:19038,A00710:97:HWTWMDMXX:1:2218:32452:4711,A00710:97:HWTWMDMXX:1:2218:32633:4899,A00710:97:HWTWMDMXX:2:1353:10926:30906,A00710:97:HWTWMDMXX:2:1353:11035:30937,A00710:97:HWTWMDMXX:2:2362:27543:11929,A00710:97:HWTWMDMXX:1:2150:32163:30514,A00710:97:HWTWMDMXX:1:2267:21811:17785,A00710:97:HWTWMDMXX:2:2180:29930:7044,A00710:97:HWTWMDMXX:1:1347:6858:12524
```

Do you have any hints to provide on this ?

By the way, when we have (for instance) several possible partners on the 5' side (here `AC092431.1(7024)` and `ANXA4(21103)`) would it be better to create two different lines rather than aggregating gene names ?

Many thanks for your help,
Anthony - using Arriba v2.0.0

**Comment by suhrig** [comment]
Hi Anthony,

Thanks for pointing this out to me. This does indeed look like a bug. I have seen several such examples in the past, but whenever I investigated the underlying cause, it was always an error in the gene annotation (GTF file): Some genes are annotated multiple times with the same name and overlapping coordinates but with different gene IDs. Since Arriba uses the gene IDs to distinguish genes from each other (after all this is the purpose of gene IDs), it happens that genes with the same name and same breakpoints are reported multiple times. However, in your example, the gene IDs are identical, too. So this is likely a bug in Arriba. I have screened my test data and found a handful of examples myself. All of them had one breakpoint in an intergenic region. So likely, it has something to do with how Arriba handles intergenic breakpoints. I will debug this and report back when I have found a fix. In the meantime, you can take the breakpoint with the higher read support. The differences in the `filters` and `fusion_transcript` columns are also a consequence of different read support.

> would it be better to create two different lines rather than aggregating gene names ?

This is what Arriba does actually. When there are multiple possible partners, it generates one line for each partner. In your example there is **no** partner: the breakpoint is intergenic. Intergenic breakpoints are denoted as the closest genes in the vicinity with the distances to these genes given in parentheses. There is a [detailed description of all columns of Arriba's output file in the manual](https://arriba.readthedocs.io/en/latest/output-files/) in case you have not stumbled upon it yet.

Regards,
Sebastian

**Comment by suhrig** [comment]
Hi Anthony,

This bug is fixed now in the `develop` branch. You can either use my previously suggested workaround (taking only the line with the higher read support) or download and compile the latest development version:

```
git clone https://github.com/suhrig/arriba.git
cd arriba
git checkout develop
make
```

Thanks again for taking the time to report this bug.

Regards,
Sebastian
