### ISSUE TITLE
Can Arriba generate fusion vcf?

### ISSUE THREAD

**Issue by jiaan-yu** [suhrig/arriba#119]
Hi, does Arriba has the functionality to generate fusion vcf? Or would vcf be considered a possible output format in the future? Many curation software nowadays ask for vcf format as input.
Thanks!

**Comment by suhrig** [comment]
Yes! The next release will come with a script to convert Arriba's custom format into VCF. You can find the script already online in the develop branch: https://github.com/suhrig/arriba/blob/develop/scripts/convert_fusions_to_vcf.sh

I would be grateful if you could already give it a try and let me know if it produces output that is compatible with your downstream software. If there are issues I could possibly fix them before the next stable release.

**Comment by jiaan-yu** [comment]
Thanks for the script! The output vcf looks good enough, and I'm happy to take it from there and hamper it to fit our curation software.
Although I have a few questions regarding your script:
- How is the orientation in the "ALT" is determined? Your script uses the "upstream" / "downstream" column, but how are they different from the "strand1/2(gene/fusion)" column?
- Some of the "REF" bases are *reverse compliment* to what I retrieve from reference file using chrom+pos. My theory is that the fusion happens on the reverse strain of the reference, but it does not make sense to me from a vcf perspective? Why they are not converted to reverse compliment bases?

**Comment by jiaan-yu** [comment]
To add on my previous comment, I observe that the second value of the "strand1/2(gene/fusion)" seem to match the sequence in "fusion_transcript". But the strandness has no correlation with upstream/downstream.

**Comment by suhrig** [comment]
The sequence for the REF/ALT fields is taken from the fusion transcript sequence. This sequence depends on the strand that is transcribed (as encoded by the second half of the `strand1/2` fields). So in cases where the reverse strand is transcribed, the sequence can be reverse complemented.

The VCF spec is not clear about whether the REF / ALT fields must contain the reference sequence from the forward strand. It is only by convention. I guess this is because the spec was developed for genomic data (rather than transcriptomic data), where the concept of strandedness does not apply.

I agree that information from the reverse strand can be confusing in the context of a VCF file. I can adapt the VCF conversion script to only report sequence information from the forward strand. The downside of this representation is that you lose information about the transcribed strand, which is quite relevant in the context of gene fusions.

On a related note: In its current form, the script does not have a solution for when the fusion transcript cannot be determined due to strand ambiguity (as denoted by a `.` in the second half of the `strand1/2` columns). In these cases, the script simply puts a `.` in the REF / ALT fields. Resolving this will require the use of the reference assembly. So I guess I should anyway enhance it in a way that makes use of the reference assembly.

**Comment by suhrig** [comment]
I have modified the script to only output sequences from the forward strand. You can download it from the link above again. Note that this updated script takes an additional parameter - the assembly - and requires samtools to be available in your `$PATH`.

**Comment by jiaan-yu** [comment]
Thank you for explaining the strand direction and the REF / ALT fields in Arriba.
If there is no standard for fusion representation in VCF (which I hope we would have that soon), I'll just go with whatever the curation software requires.
