### ISSUE TITLE
comparison with STAR-Fusion

### ISSUE THREAD

**Issue by snowlover** [suhrig/arriba#12]
Hi Sebastian,

May I ask if you have performed some comparisons with STAR-Fusion ?

Thanks.

**Comment by snowlover** [comment]
Hi Sebastian,

I used both arriba & star-fusion.
really useful information. actually I encountered an strange issue using star-fusion, as stated [here](https://github.com/STAR-Fusion/STAR-Fusion/issues/110), it's possibly due to the STAR parameter used in their pipeline because using the arriba's parameter looks good, but I'm not an expert so it's hard to find out the ultimate reason, maybe you can help if you would like to.

I really hope your manuscript publish asap :)

**Comment by suhrig** [comment]
> actually I encountered an strange issue using star-fusion

I tried reproducing your observations, but when I run STAR the reads do not map at all. Likely, I'm not using the exact same version of STAR, reference genome assembly and parameters as you are. Anyhow, I agree with Brian that this question is best answered by the developer of STAR, since it is an issue with the alignment algorithm and not with fusion calling per se.

> it's possibly due to the STAR parameter

You can narrow down the issue by running STAR iteratively and gradually changing the parameters to more and more match those of Arriba with each iteration. I would have tried myself, but like I said, I cannot even get STAR to align the reads at all.

> STAR-Fusion says 2 mismatches (nM:2) for both paired ends of the fragment

This flag counts the number of mismatches for the entire fragment, which means that it is set to the sum of the mismatches of both reads. That is why it is set to "2" for both reads, even though one of the reads may harbor both mismatches.

> I really hope your manuscript publish asap :)

Thanks!

**Comment by snowlover** [comment]
Thanks, Sebastian.
