### ISSUE TITLE
draw_fusions.R

### ISSUE THREAD

**Issue by yingfeikeji** [suhrig/arriba#120]
hi:
 How to use Arriba data to render IGV?
 Thanks you!

**Comment by suhrig** [comment]
draw_fusions.R has nothing to do with IGV.

You can load the output files of STAR into IGV and interactively inspect the fusion-supporting reads using IGV, as shown here: https://arriba.readthedocs.io/en/latest/visualization/#inspection-of-events-using-igv

Does that answer your question? Or are you asking how to make automated IGV screenshots of the fusion-supporting reads?

**Comment by yingfeikeji** [comment]
Thanks!
Whether it can be loaded to IGV web page! Instead of using the IGV client

**Comment by suhrig** [comment]
I'm not sure what web page you mean. Can you send me a link?

**Comment by yingfeikeji** [comment]
https://igv.org/app/

**Comment by yingfeikeji** [comment]
This is an example of IGV! Real data will be more than that

**Comment by yingfeikeji** [comment]
This is an example of IGV! Real data will be more than that

**Comment by yingfeikeji** [comment]
R script output PDF data! Can it be converted to JSON! Provide IGV usage

**Comment by suhrig** [comment]
> Can it be converted to JSON! Provide IGV usage

To do what exactly? The PDF contains a lot of information - the chromosomes, be wild-type transcripts, the fusion transcript, a circos plot, the protein domains, the number of supporting reads. What exactly do you want to visualize in the IGV app? 

You can load the BAM file into the IGV app. Just go to Tracks -> Local file and choose the BAM file and BAM index. You can also load the protein domain track into the app by choosing the file `database/protein_domains_ASSEMBLY_v2.1.0.gff3` to be found in the Arriba download package.

**Comment by yingfeikeji** [comment]
Do you know 'fusioninspector'? Because we are very much in favor of Arriba data at present! There is no way to use 'fusioninspector' to generate IGV for web page visualization!

Use 'fusioninspector' to generate visualization! Then we have to re execute 'star'!

It will take a lot of time!

**Comment by suhrig** [comment]
> Do you know 'fusioninspector'?

I have never used it, but I know what it is about.

> There is no way to use 'fusioninspector' to generate IGV for web page visualization!

The visualization component of FusionInspector actually makes use of the IGV app. It builds a self-contained HTML page with an embedded IGV.

According to the documentation of FusionInspector, you can use it with any fusion prediction tool - including Arriba. All it takes as input is a list of fusion partners.

> Use 'fusioninspector' to generate visualization! Then we have to re execute 'star'!

FusionInspector creates a visualization with the fused genes side-by-side. This is only possible by performing a realignment against a synthetic genome consisting of the two fused genes. There is no way you can avoid rerunning STAR if you want the fusion partners to be visualized side-by-side.

Does it have to be side-by-side? Why not use the visualization based on the standard alignments in [IGV's split-screen mode](https://arriba.readthedocs.io/en/latest/visualization/#inspection-of-events-using-igv)? This does not require a realignment and shows pretty much the same thing.

> Can it be converted to JSON!

Do you want to create an IGV session in JSON format to load into the IGV app? If yes, what should this session contain? Can you name the tracks you want to show?

**Comment by yingfeikeji** [comment]
May I send you an email! The file contains the data we need to display

**Comment by yingfeikeji** [comment]
Can I have your email address?

**Comment by suhrig** [comment]
s.uhrig at dkfz dot de

**Comment by yingfeikeji** [comment]
has been sent

**Comment by suhrig** [comment]
I have received the file. If I understand you correctly, you want to generate the self-contained HTML file such as [the example given in the FusionInspector wiki](https://github.com/FusionInspector/FusionInspector/wiki/FusionInspector-Visualizations#fusion_inspector_webhtml-self-contained-dynamic-html).

The easiest way to get this is to run FusionInspector on the output of Arriba. In the FusionInspector wiki it says the tool is run like so:

```
FusionInspector --fusions fusions.txt \
                --genome_lib /path/to/CTAT_genome_lib \
                --left_fq rnaseq_1.fq --right_fq rnaseq_2.fq \
                --out_dir my_FusionInspector_outdir \
                --out_prefix finspector \
                --vis
```

The file `fusions.txt` must contain the fusions to be visualized, for example:

```
BCR--ABL1
TMPRSS2-ERG
EWSR1-FLI1
```

If you do not want to realign the entire BAM file just to get the visualizations (because it's very time-consuming), you can limit the realignment to the fusion-supporting reads found by Arriba. This will only take a few seconds to realign.There is a new script in the develop branch of Arriba's GitHub repository, which generates mini-BAMs that only contain the fusion-supporting reads. You can find the script here: https://github.com/suhrig/arriba/blob/develop/scripts/extract_fusion-supporting_alignments.sh The script creates one mini-BAM per fusion. You need to convert it back to FastQ using `samtools collate ... | samtools fastq ...` or `bamtofastq` from the biobambam package. You can then pass the FastQ files as input to FusionInspector.

Does this answer your question?

**Comment by yingfeikeji** [comment]
I have tested your method!

But I haven't used your mini-bam!

I'm going to test it now!

Thank you very much.

**Comment by yingfeikeji** [comment]
It's been tested!
But not ideal! The output 'mini-BAM' file column is different!
But thank you very much!

**Comment by suhrig** [comment]
What column do you mean?

**Comment by yingfeikeji** [comment]
Third column!
your is  chr...!
FusionInspector is AC044810.2--OVCH2!

**Comment by suhrig** [comment]
You are not supposed to give the mini-BAM as input to FusionInspector. FusionInspector takes a list of fusions as input in the form

```
BCR--ABL1
TMPRSS2--ERG
EWSR1--FLI1
```

Additionally, FusionCatcher takes a pair of FastQ files as input. You must convert the mini-BAM to FastQ.

**Comment by yingfeikeji** [comment]
yes!
I Know!
I compared the documents first!
Next I'll continue to test!
thank you!

**Comment by suhrig** [comment]
Do you need any further help with this? Or had your question been answered by the mini-BAM script?
