### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [suhrig/arriba#138]
I would like to point out that identifiers like “[`_ANNOTATION_H`](https://github.com/suhrig/arriba/blob/ecae3c1e6904644a4a54ac32d2cd67f95b751e71/source/annotation.hpp#L1 "Update candidate")” and “[`_READ_STATS_H`](https://github.com/suhrig/arriba/blob/2d2c4957d72f72ea2b3609a6c62ea004e5046dce/source/read_stats.hpp#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by suhrig** [comment]
Sorry for the delayed reply. Somehow I never got a notification for this issue. Maybe I overlooked it or it got eaten by the spam filter.

Anyway, thanks for making me aware of this and for the helpful links. Yes, I should & will fix this.

I know that the coding style may not be the best. I try to keep things compliant and tidy to the best of my knowledge, but I won't refrain from using shortcuts if it makes implementation much easier or if there is some other benefit, such as a massive performance improvement. For example, I use C functions in several places even though there is a C++ equivalent, because it speeds things up. If I wanted to do the same in pure C++ I would have to implement my own performance-optimized class, which is much more effort than using existing C functions. Generally speaking, a lot of my code is more like the infamous "C with classes" coding style than proper C++. I am aware of this, but I don't plan to change it, because doing so would be a lot of effort and I rather invest this time in improvement of the algorithm than in refactoring of code.

**Comment by elfring** [comment]
>Yes, I should & will fix this.

Thanks for your constructive feedback.

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/suhrig/arriba/commit/6782fc0ae7003915e7d8a936c2b80fa3621af90d "standard-compliant header guards").
