### ISSUE TITLE
Duplicates filter

### ISSUE THREAD

**Issue by xiucz** [suhrig/arriba#139]
Hi, @suhrig 

I found a call from the discarded.tsv,  it was marked as "duplicates(2),min_support". IF the support reads are enough,  this fusion event should be  tagged PASS ?  And what does duplicates here mean?

```
fusions.discarded.tsv:PVT1	CCDC26	+/+	-/-	chr8:128806980	chr8:130411930	exon/splice-site	exon/splice-site	inversion	0	1	0133	78	low	.	.	.	.	.	ENSG00000249859.12_7ENSG00000229140.11_12	.	.	downstream	downstream	duplicates(2),min_support	.	.	.
```

Thank you.
xiucz.

**Comment by suhrig** [comment]
Hi @xiucz,

It means there are 3 reads supporting this fusion, 2 of which are PCR duplicates (as evidenced by having identical mapping coordinates). After subtracting the 2 duplicates, only 1 supporting read remains. The `min_support` filter requires at least 2 supporting reads, so it discards the candidate.

Rearrangements of the MYC locus such as this one are quite common. I agree that this could be a false negative. But given the poor read support, not much can be done about this. I do not recommend disabling the `duplicates` or `min_support` filter, since you will get lots of false positives otherwise.

For more information about the filters, check out the [manual](https://arriba.readthedocs.io/en/latest/internal-algorithm/).

Regards,
Sebastian
