### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [suhrig/arriba#141]
I suggest to reuse a higher level build system than [your current make script](https://github.com/suhrig/arriba/blob/3492d2c28917fe6c9320b1caab73afbb93f7bfbf/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by suhrig** [comment]
The Makefile works fine. This is one of the cases where I would rather not waste time on updating something that already works. Moreover, Make is installed automatically as part of the standard software development toolkit on most platforms, which is not true for CMake or autotools. This means users who want to compile the software would have to jump through additional hoops if the build system was based on CMake/autotools rather than good old Make.

**Comment by elfring** [comment]
- Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.70/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.22/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?

**Comment by suhrig** [comment]
I made it an effort to keep Arriba's dependencies at a minimum. The few that it has are automatically pulled upon `make`ing. As a result, compilation should work on a minimal system that has essential development tools installed. This eliminates the need for sophisticated dependency checking tools IMO.

**Comment by elfring** [comment]
:thought_balloon: I imagine that additional software build functionality can occasionally become more attractive (under “special” circumstances).
