### ISSUE TITLE
Support for out-of-source builds

### ISSUE THREAD

**Issue by elfring** [suhrig/arriba#142]
How do you think about to benefit from [parallel build trees](https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html "Parallel build trees (a.k.a. VPATH builds)") also for this software?
Would you like to [support out-of-source](https://gitlab.kitware.com/cmake/community/wikis/FAQ#what-is-an-out-of-source-build "https://gitlab.kitware.com/cmake/community/wikis/FAQ#what-is-an-out-of-source-build") ([VPATH](https://www.gnu.org/software/make/manual/html_node/General-Search.html "Search path for all prerequisites")) builds?

**Comment by suhrig** [comment]
I like how things are built/compiled at the moment. No build directory required, no configure, etc. All you have to do is type `make`. It does not get simpler than that. I have used systems for parallel build trees in the past and they made things more complicated than necessary for such a rather small code base. I don't think users of this software care where the build files are stored. I believe they care more about ease of install, because bioinformatics tools are typically a pain to install. So I make it an effort to keep the installation routine as clean and straightfoward as possible.
