### ISSUE TITLE
blacklist/known fusion file with updated GENCODE

### ISSUE THREAD

**Issue by tarfy** [suhrig/arriba#144]
Hi @Suhrig,

I have used your download_reference.sh script to make a STAR index with the latest  version of GENCODE (GRCh38viral+GENCODE39).

Is it ok to still use the blacklist_hg38_GRCh38_v2.2.1.tsv.gz and known_fusions_hg38_GRCh38_v2.2.1.tsv.gz files provided in the tarball or will the gene coordinates/annotations have changed because of the updated GENCODE?

Thanks!

**Comment by suhrig** [comment]
Hi @tarfy,

It is perfectly fine to use the blacklist/known fusions file with an updated version of GENCODE. The gene coordinates may be slightly different between GENCODE39 and previous versions, but it should have minimal effect on fusion calling. I have used it even with RefSeq as a gene model (which has many more differences to GENCODE) and the files still did their job just fine.

You may see some warnings from the protein domain annotation, because the protein domains file uses gene names. But this also affects only a small set of genes, so nothing to worry about either.

Regards,
Sebastian

**Comment by tarfy** [comment]
Ok good to know, thanks for the explanation Sebastian.
