### ISSUE TITLE
Detecting Fusions to Intronic LINE1

### ISSUE THREAD

**Issue by DarioS** [suhrig/arriba#146]
In this month's issue of _Nature Genetics_, it has been shown that [exons sometimes fuse to intronic LINE1](https://www.nature.com/articles/s41588-021-01003-w). Can this be found using arriba?

**Comment by suhrig** [comment]
Hi Dario,

As I understand it, these LINE1 elements are transcribed conditionally in the shape of additional exons between canonical exons. Arriba ignores any **cis-spliced** exon junctions **within** the boundaries of a gene. Arriba considers these as alternative transcript isoforms and likely normal. Even if Arriba made an attempt to detect them, they would probably be removed by Arriba's blacklist, since they are observed in normal tissue according to the paper, and the blacklist was trained on many normal samples. In summary, Arriba is not able to detect these events. I believe a tool for alternative/novel transcript isoform detection would be more suitable for this purpose.

Regards,
Sebastian
