### ISSUE TITLE
Issues with draw_fusion.R script

### ISSUE THREAD

**Issue by yoongmin** [suhrig/arriba#148]
Hi, Im working on aloft.sh...

But when plotting jobs, it popped out errors as below:
Running Plotting jobs...
0% 0:1=0s arriba_v1.2.0/draw_fusions.R --fusions=/home/neo/RNAseq_DrChong/output/home/neo/miniconda3/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

what command should I use to change my R location? I dont know why it turned out use the R from miniconda3...

**Comment by suhrig** [comment]
Hi,

I am not too familiar with aloft.sh, because I did not develop it, but as far as I can tell the error is not necessarily related to aloft.sh. draw_fusions.R uses whatever R it finds in the `$PATH` environment variable. If you type `which R`, you will see the installation of R that is being used. My guess is that your `$PATH` environment variable is set to the miniconda installation. You should see it when you type `echo $PATH`. You should prepend your desired R installation to the variable, e.g., `export PATH=/path/to/proper/R/installation:$PATH`. This should fix it for the running bash session. To make the change permanent, you need to figure out how miniconda ended up in the `$PATH` environment variable in the first place and fix that. It's probably somewhere in your `~/.bash_profile` or '~/.bashrc` file.

Does that help?

Regards,
Sebastian

**Comment by yoongmin** [comment]
Hi Sebastian, the problem solved.
Thanks for you advice. =)
