### ISSUE TITLE
Minimum Support Filter Not Working

### ISSUE THREAD

**Issue by DarioS** [suhrig/arriba#158]
I read that

> The 'min_support' filter discards all fusions with fewer than  this many supporting reads (split reads and discordant mates combined)

and I ran with `-S 20` but I see many fusions that don't meet the criteria.

```
         type    split_reads1    split_reads2    discordant_mates        coverage1       coverage2       confidence
  duplication               2               0                   0               56              80              low
     deletion               0               2                   3              479              58             high
translocation               3               0                   0               64              19           medium
```

It must be unintentionally summing something more than just split reads and discordant pairs.

**Comment by suhrig** [comment]
This filter (among others) is overruled by some rescue filters. You need to disable the following filters in order to strictly enforce the `min_support` filter:

```
-f spliced,internal_tandem_duplication,isoforms,known_fusions,many_spliced
```

This should work. The numbers reported in the columns `split_reads1` + `split_reads2`+ `discordant_mates` may still be a bit lower in some occasions, because there is also the `mismappers` filter which discards some reads after the `min_support` filter takes effect. These reads are then listed in the column `filters`.

Note that the internal tandem duplication filter has its own min supporting reads threshold, which can be configured using the parameter `-Z` (by default 10). So you can leave this one enabled if you set the value of `-Z` and `-S` equal.

Obviously, sensitivity will take a hit, especially if you set it as high as 20. But I guess that was only for testing purposes. You may get a better sensitivity/specificity trade-off if you discard the low-confidence fusions rather than enforcing such a high threshold for the supporting reads.
