### ISSUE TITLE
GTF file parse

### ISSUE THREAD

**Issue by denise0593** [suhrig/arriba#159]
Hi arriba developers, 
I'm trying your software on Sars-cov-2 samples, but when the script returns:
"
[2022-05-30T12:19:41] Launching Arriba 2.3.0
[2022-05-30T12:19:41] Loading assembly from '/opt/references/SARS-CoV2/SARS-CoV-2.fasta' 
[2022-05-30T12:19:41] Loading annotation from '/opt/references/SARS-CoV2/SARS-CoV-2-GenBank.gtf.gz' 
ERROR: failed to parse GTF file, please consider using -G
"
[SARS-CoV-2-GenBank.gff.gz](https://github.com/suhrig/arriba/files/8797592/SARS-CoV-2-GenBank.gff.gz)
[SARS-CoV-2-GenBank.gtf.gz](https://github.com/suhrig/arriba/files/8797593/SARS-CoV-2-GenBank.gtf.gz)

I cannot understand the error.
Thanks a lot

**Comment by suhrig** [comment]
Hi Denise,

Your GTF file has no `exon` features. That's why Arriba does not unterstand it. In your case, it seems that `gene` features can be used as a surrogate. You can instruct Arriba to do so using the parameter `-G`. The following should work:

```
-G 'gene_name=gene_id gene_id=gene_id transcript_id=gene_id feature_exon=gene feature_CDS=CDS' -v ''
```

In addition, `-v ''` is required. Otherwise Arriba searches for viral integration sites into the human genome, which makes no sense in this context, because there is no human DNA.

Regards,
Sebastian

**Comment by denise0593** [comment]
Hi Sebastian, 
It works! Thank you so much!
Best Regards,
Denise
