### ISSUE TITLE
pinning to htslib 1.8 in bioconda

### ISSUE THREAD

**Issue by roryk** [suhrig/arriba#16]
Hey everyone,

Congrats on the great showing in the DREAM challenge! I am looking at what it would take to integrate this in our workflow. I tried installing the package from bioconda, but the pinning of htslib to be 1.8 causes a bunch of other stuff to get removed that we install. Is the pinning to 1.8 necessary? If it is, do you think we could work to get it working against htslib 1.9?

**Comment by suhrig** [comment]
Hi Rory,

Arriba might work with htslib 1.9 just as well. It's just that I have never tested it and recall that some modifications were necessary when switching from 1.6 to 1.8, which is why I didn't dare to specify a flexible dependency. I will give it a try in the next days and submit a patch to bioconda, if the tests are successful. I will let you know.

Regards,
Sebastian

**Comment by suhrig** [comment]
Hi Rory,

I have updated the bioconda recipe for Arriba. It uses htslib-1.9 now.

Regards,
Sebastian

**Comment by roryk** [comment]
Awesome! Thanks so much.
