### ISSUE TITLE
Detect EGFR variants and MET exon-14 skipping

### ISSUE THREAD

**Issue by foxchase** [suhrig/arriba#162]
Dear Sebastian,
Thank you for your excellent tool. Arriba can accurately detect FLT-IDT and KMT2A-PTD in addition to fusions. Is it possible to detect EGFR variants and MET exon-14 skipping, which are of clinical importance in lung cancer. Below is the Seracare fusion RM which has EGFR vIII and MET exon14 skipping.
https://www.seracare.com/globalassets/seracare-resources/coa-0710-0496-seraseq-ffpe-fusion-rna-reference-material-v4-10610614.pdf

Thank you in advance.

**Comment by suhrig** [comment]
Unfortunately, Arriba cannot detect intragenic deletions such as EGFR or MET exon skips. Intragenic deletions are hard to differentiate from alternative splicing in RNA-Seq data, because they look alike. In any given sample, there are thousands of transcripts which skip exons that should not be skipped according to the gene model (GTF file). It is not obvious which of them are an effect of alternative splicing and which are the result of an intragenic deletion.

From a technical point of view, it would also be hard to implement such a feature, because Arriba was never designed for this purpose and it would require fundamental changes to the code.

You should use a differential splicing analysis tool or define a whitelist of known oncogenic exon skipping transcript variants and extract them manually from the BAM.
