### ISSUE TITLE
Interpretation of Arriba fusion output with multiple genes in either 5'- or 3'- partners

### ISSUE THREAD

**Issue by asmitagpta** [suhrig/arriba#163]
Hi,

I am running Arriba to predict fusions in a cohort of TCGA cancer samples. The output files contain several examples like below - 

-----------------------

`STK11         Z82202.1(60181),AC207130.1(46663)       +/+     ./-     19:1222006      22:49326261     splice-site     intergenic      translocation   downstream      downstream      8       8       54      96      72      high    .       .       duplicates(3),mismatches(9)     .       .       .       .`

`SEMA4B        AC027176.3(47028),ZNF710(2951)  +/+     ./+     15:90185081     15:89998373     splice-site     intergenic      duplication     downstream      upstream        1       1       17      68      32      high    .       .       duplicates(4),mismatches(1)     .       .       .       .`

`SCAF4         TPT1P1(25848),HUNK(6314)        -/-     ./-     21:31688307     21:31866706     splice-site     intergenic      duplication     upstream        downstream      2       1       9       216     11      high    .       .       duplicates(3)   .       .       .       .`

-----------------------

These examples list multiple genes in the **gene2** column. Does it suggest that there are multiple genes acting as 3'- partners to the 5'- gene? What does the number in the brackets indicate? Can you please suggest what pair should I consider for further downstream analysis?

Thanks,

**Comment by suhrig** [comment]
Hi,

It means that the breakpoint is intergenic and does not hit any gene directly. The value in parentheses is the distance to the gene. Have a look at the manual if you need [more info about the output file format](https://arriba.readthedocs.io/en/latest/output-files/#fusionstsv).

> Can you please suggest what pair should I consider for further downstream analysis?

Strictly speaking, you should not use any of the genes, because they are not involved in the fusion. If you absolutely have to specify a gene for your purpose (e.g., because it is a mandatory field), then you can use the first gene, if the column `direction2` is `downstream`, and the second gene, if it is `upstream`, because this is the part of the chromosome that is retained in the fusion. Note that this rule is not always straightforward to apply, because there are situations where you can have more than two genes listed in the column or even none at all. An easier way to handle this situation would be to simply take both genes and make two separate entries. There are situations where the above rule does not make the right choice.

Regards,
Sebastian

**Comment by sufyazi** [comment]
Hello, thank you for the cool tool!

Commenting here: I just don't want to clutter the Issues tab with near-related posts.

I have two followup questions regarding this topic actually:

> It means that the breakpoint is intergenic and does not hit any gene directly. 

1) Why would Arriba retain these as "gene fusion events" then? Is it because the underlying logic is just 'if a transcript seems to come from gene A--Breakpoint--??, label these as potential gene fusion events before applying filters'? Because after realizing this, I would have thought a 'gene fusion' event is only considered true when the breakpoint lies intragenically AND a "fused" transcript can be traced back to two separate genes (annotations).

2) In my own data, it seems like all of these instances appears to have the "3' fusion partner" being intragenic region. Is that the natural consequence or can we expect intragenic region being the "5' partner"?

**Comment by suhrig** [comment]
> Why would Arriba retain these as "gene fusion events" then?

True, it's not a gene fusion in the strict sense. In the strict sense, one would even need to remove fusions which are out-of-frame, because even though they fuse genes together, there is not biologically relevant product.

In practice, however, even out-of-frame fusions and fusions with intergenic regions can be relevant. They typically hit tumor-suppressor genes, thus inactivating the genes.

A better term would be "structural variant".

> it seems like all of these instances appears to have the "3' fusion partner" being intragenic region

Arriba has a preference to put the affected gene as the 5' partner when the other end is intergenic. This is because the transcription start is unlikely to be in an intergenic region. For the same reason, fusions with 5' intergenic ends are penalized heavily and likely won't make it through the filters, which is why you may only see fusions with the 3' end being intergenic.

**Comment by sufyazi** [comment]
Thank you @suhrig for a very prompt response. I had some time going through all of your answers to questions relevant to what I asked so in addition you what you just replied, everything is clearer to me now. Cheers!
