### ISSUE TITLE
how to add "chr" prefix to output exon coordination 

### ISSUE THREAD

**Issue by xiucz** [suhrig/arriba#17]
Hi, 
When I tried to use "draw_fusions.R" to visualize arriba output, it reported "error : exon coordinates not found in gff3 ",so is there a way to get output results with "chr" prefix in exon coordinates ?

Thank you,
Xiucz

**Comment by suhrig** [comment]
Hi Xiucz,

Just to get this straight: You ran Arriba (which implicitly removes all `chr` prefixes). Then you added the prefix manually by modifying the output file `fusions.tsv`. And then you ran `draw_fusions.R`. Is that correct? If yes, then the following hack should produce plots including the `chr` prefix, provided that all input files of `draw_fusions.R` (annotation.gtf, Aligned.out.bam, fusions.tsv, protein_domains.gff3) also use a `chr` prefix: Just delete [the line which removes the `chr` prefix](https://github.com/suhrig/arriba/blob/477f92b6cfe10df11ff22c1ffd5ef65f1fe20243/draw_fusions.R#L129) in the script. It's on line 129:
https://github.com/suhrig/arriba/blob/477f92b6cfe10df11ff22c1ffd5ef65f1fe20243/draw_fusions.R#L129

I hope this helps. Let me know, if you are having trouble getting this to work. I must admit I am not 100% happy with how Arriba handles the `chr` prefix. Well, actually, I am not happy with the fact that there are two naming conventions - one with and one without the prefix, but I can't do anything about that. ;-) The reason why Arriba discards the prefix, is because this ensures the most robust behavior no matter what files users throw at it. I will think about a better solution that also permits users to keep the prefix, if desired.

Note: You will need to add a `chr` prefix to the protein_domain.gff3 file, if you want to visualize protein domains. Do not add a `chr` prefix to the blacklist, though, or else it will be ineffective (unless you also hack the `arriba` executable to not remove the prefix)!

Regards,
Sebastian

**Comment by xiucz** [comment]
Thank you , I will have a try, and I close this issue.

**Comment by xiucz** [comment]
Hi @Sebastian,
```
~/software/STAR-2.6.1c/bin/Linux_x86_64_static/STAR --runThreadN 4 --genomeDir ~/database/hg19/gatk_bundle --genomeLoad NoSharedMemory \
--readFilesIn ~/data/test/fusioncatcher/reads_1.fq.gz ~/data/test/fusioncatcher/reads_2.fq.gz \
--readFilesCommand zcat --outStd BAM_Unsorted --outSAMtype BAM Unsorted --outSAMunmapped Within --outBAMcompression 0 --outFilterMultimapNmax 1 --outFilterMismatchNmax 3 --chimSegmentMin 10 --chimOutType WithinBAM SoftClip --chimJunctionOverhangMin 10 --chimScoreMin 1 --chimScoreDropMax 30--chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentReadGapMax 3 | \
~/software/FUSIONTOOLS/arriba_v1.1.0/arriba -x /dev/stdin \
-a ~/database/hg19/gatk_bundle/ucsc.hg19.fasta -g ~/database/gff/gencode/gencode.v30lift37.annotation.gtf -b ~/software/FUSIONTOOLS/arriba_v1.1.0/database/blacklist_hg19_hs37d5_GRCh37_2018-11-04.tsv.gz -T -P \
-o ./arriba/arriba.fusions.tsv \
-O ./arriba/arriba.fusions.discarded.tsv
```


```
~/software/FUSIONTOOLS/arriba_v1.1.0/draw_fusions.R --fusions=./arriba/arriba.fusions.tsv --output=arriba.fusions.pdf --annotation=~/database/gff/gencode/gencode.v28lift37.annotation.gff3 --cytobands=~/zhangbo/software/FUSIONTOOLS/arriba_v1.1.0/database/cytobands_hg19_hs37d5_GRCh37_2018-02-23.tsv --proteinDomains=~/software/FUSIONTOOLS/arriba_v1.1.0/database/protein_domains_hg19_hs37d5_GRCh37_2018-03-06.gff3
```
