### ISSUE TITLE
Potentially truncated fastq?

### ISSUE THREAD

**Issue by min-codes** [suhrig/arriba#175]
Dear authors,

Thank you for developing Arriba and for the very detailed and organised documentation. The experience has been really smooth so far!

When I ran Arriba, I get this error message for some of the samples :

```
[2022-11-27T09:16:35] Reading chimeric alignments from '/dev/stdin' 
EXITING because of FATAL ERROR in reads input: quality string length is not equal to sequence length
[W::bgzf_read_block] EOF marker is absent. The input may be truncated
```

The fastq files have worked with other tools before, so i decided to just rerun them using the exact parameters, and interestingly it worked the second time. Wanted to post it here to see if you could tell what made it work the second time

I personally suspect that this due to insufficient memory/ RAM on the server I'm using - since I am running other tools at the same time? And because Arriba reads from stdin it wasn't able to do so properly due to the RAM issue?

**Comment by suhrig** [comment]
> I personally suspect that this due to insufficient memory

This could be an explanation. I would have expected the error message to be a different one, namely something more obviously related to RAM shortage. But insufficient RAM can lead to all kinds of problems, and sometimes far downstream such that the true underlying error is masked by a seemingly unrelated error.

This is not an error message from the `arriba` executable BTW. The error comes from STAR. Maybe it is even caused by an earlier step, because STAR complains about **input**. So possibly `zcat` (which feeds the FastQ reads to STAR) terminated prematurely.

Anyhow, without the ability to reproduce we will probably never know for sure. Thanks for reporting nonetheless. It's good to know that the workflow terminates with an error in such cases rather than just continuing silently with incomplete data. These rare errors are hard to test and often neglected. So good to know the workflow behaves appropriately.
