### ISSUE TITLE
Fusion pdf output "No coding regions due to antisense transcription"

### ISSUE THREAD

**Issue by kvaldez** [suhrig/arriba#176]
Hi Sebastian,

Thank you for this excellent tool that we rely on for our fusion detection, we especially appreciate the pdf output.

I have a quick clarification question regarding some wording used in the pdf output. 

We have the following fusion in our tsv file:
#gene1	gene2	strand1(gene/fusion)	strand2(gene/fusion)
EWSR1	PATZ1	+/.	-/.

And the resulting output in the pdf plot lacks transcript information and states that:
"No coding regions due to antisense transcription"

It appears as though no strand or fusion transcript can be determined.  However the wording in the report suggests otherwise.  Can you clarify what "No coding regions due to antisense transcription" means in this case?

Thanks!
Kristin

**Comment by suhrig** [comment]
Hi Kristin,

The error message relates to the protein domain panel. Usually, it is printed when both genes are transcribed in antisense direction and no protein-coding sequences are transcribed, hence. You're right, in your case, the error message is misleading. Arriba completely failed to determine which strands are transcribed. This could be antisense transcription or sense transcription. It's simply unclear and therefore, the draw_fusions.R script makes no attempt at drawing protein domains. A more appropriate error message would be "Transcribed strands could not be determined" or "Failed to determine retained protein domains due to lack of strand information". I will reformulate the error message for this special case. Thanks for taking the time to report this.

Regards,
Sebastian

**Comment by kvaldez** [comment]
Thank you! I appreciate the info and the prompt response.

Kristin
