### ISSUE TITLE
Question, is there an easy way to display Circos plot by itself with all fusions labeled

### ISSUE THREAD

**Issue by jlee110** [suhrig/arriba#18]
I would like to display the circos plot with fusions labeled with maybe different colors for interchromosomal and intrachromosomal fusions. 

Could you point me in the right direction? I'm trying to understand your r script so I can customize the circos plot if possible.

**Comment by suhrig** [comment]
The code that draws the circos plot is contained in the function `drawCircos()`. By default the function draws arcs for all fusions (with a confidence >= what is given in the parameter `minConfidenceForCircosPlot`). But only the fusion given in the parameter `fusion` is labeled.

The labels are drawn on the following line:

https://github.com/suhrig/arriba/blob/477f92b6cfe10df11ff22c1ffd5ef65f1fe20243/draw_fusions.R#L317

In order to label all fusions, you need to fill the `geneLabels` data frame with all the labels and coordinates given in the `fusions` parameter. Simply INSERT the following code BEFORE the above line:

```
geneLabels <- data.frame(contig=c(fusions$contig1, fusions$contig2), start=c(fusions$breakpoint1, fusions$breakpoint2), end=c(fusions$breakpoint1+1, fusions$breakpoint2+1), gene=c(fusions$gene1, fusions$gene2))
```

The colors of the arcs are determined on the following line:

https://github.com/suhrig/arriba/blob/477f92b6cfe10df11ff22c1ffd5ef65f1fe20243/draw_fusions.R#L333

By default, the labeled arc is colored dark red, while others are light red. To color arcs by inter- versus intrachromosomal fusions, you need to REPLACE the line with this:

```
lwd=2, col=ifelse(f$contig1 == f$contig2, rgb(1,0,0), rgb(0,0,1))
```

Getting the script to only draw the circos plots is not that easy. Maybe the fastest way to get there is to zoom in and make a screenshot of just the circos plot. If you need a proper solution, I can provide you with customized script that only draws circos plots. Just let me know.

**Comment by jlee110** [comment]
Thank you for your thorough response. 

I don't want to impose but if it's not too much trouble, could you provide me with a script that only draws circos plots? 

I'm stuck on this part:

> drawCircos <- function(fusion, fusions, cytobands, minConfidenceForCircosPlot)

I'm not sure what "fusion" is supposed to look like. Am I supposed to feed first two columns (gene1, gene2) of the "fusion.tsv"? Thank you for all your help. Your tool rocks.

**Comment by suhrig** [comment]
> I'm not sure what "fusion" is supposed to look like.

It's a number that indicates which row of the `fusions` data frame should be labeled and drawn in solid red (instead of light red). It does not really have a meaning anymore, if you made the modifications I sent you earlier, because then all fusions would be labeled and drawn in a solid color.

Here is a reduced script that only draws circos plots: [draw_circos.R](https://github.com/suhrig/arriba/files/3235981/draw_circos.txt)
Run it without arguments to see the usage, which is similar to the original script, but just with fewer arguments.

**Comment by jlee110** [comment]
WOW. Your script worked! Interchromosomal in blue, and intrachromosomal in red :+1: 

What argument would you suggest I use to label the genes that are at least "high" in confidence? I think I have way too many fusions :) It seems that arcs are drawn for "high" confidence.

**Comment by suhrig** [comment]
> I have way too many fusions labeled

Whoops, you are right. The code I sent to you draws labels for all fusions (including low-confidence fusions).

> What argument would you suggest I use to label the genes that are at least "high" in confidence?

You can insert the following code before the call to `circos.genomicLabels()` on line 94:

```
geneLabels <- geneLabels[rep(fusions$confidence == "high",2),]
```
It selects labels for only those fusions that have high confidence.

> It seems that arcs are drawn for "high" confidence.

Arcs are drawn for fusions with a confidence of what is given as an argument to `--minConfidenceForCircosPlot` (by default `medium`).

**Comment by jlee110** [comment]
Thank you so much!!!!!!!!!!!!!!!!!! :100: :+1:
