### ISSUE TITLE
How to calculate fusion gene expression？

### ISSUE THREAD

**Issue by wiltbb** [suhrig/arriba#185]
In the result file,like `xxx.tsv`,There are two lists of parameters called `split_read`.How can I use these two columns to calculate the expression?

**Comment by suhrig** [comment]
Calculating the expression of a fusion from the supporting reads is not straightforward. Generally speaking, it is valid to assume that the higher the sum of `split_reads1`, `split_reads2`, and `discordant_mates` the higher the expression. However, it is not really possible to normalize these values such that they would be comparable between samples as with RPKM, FPKM, TPM etc. At best, this would be possible with a large margin of error. There are several reasons for this:

1. The supporting reads are almost always underestimated, because they are difficult to align and STAR misses quite a few of them, hence.

2. The observed expression of the gene is a mixture of the fusion and the other wildtype allele. It is hard to tell how much expression comes from the fusion and how much from the wildtype allele.

I guess the best you can do is take all supporting reads (`split_reads1` + `split_reads2` + `discordant_mates`) and divide them by the total number of mapped reads (ideally ignoring duplicates, because Arriba ignores them, too). This would give you a metric that is somewhat comparable between samples (but not between genes). I think this is also what the FFPM metric is as reported by STAR-Fusion.

**Comment by wiltbb** [comment]
Thank you very much,Suhrig! There is a problem I'm not very clear that you say divide them by the total number of mapped read,does it mean I count the number of `transcript_id1` and `transcript_id2` mapped reads(these transcript_id are displayed in `xxx.tsv` files) and then I delete the part of duplicates?If not,could you explain to me how to calculate the total number of mapped reads?

**Comment by suhrig** [comment]
Maybe it was me who misunderstood your question. Can you elaborate what is the purpose for which you want to calculate the expression? The sum of `split_reads1` + `split_reads2` + `discordant_mates` already is a measure of expression. You could just use that. It depends on how you want to use this measurement.

Usually, people who are interested in quantifying expression want something like RPKM, FPKM, or TPM to make the numbers comparable between samples. As explained earlier, it is not trivial to get these metrics for fusions.

> I'm not very clear that you say divide them by the total number of mapped read

What I meant is take all of the mapped reads in the BAM file, and divide the sum of the supporting reads by that number. For example, you can get the number of mapped reads with a command such as `samtools idxstats Aligned.sortedByCoord.out.bam | awk '{mapped+=$3} END{print mapped}'`. I should note, though, that this is a naive way to count the number of mapped reads, because it also counts duplicates and multi-mapping reads, which you don't want to count if you want to normalize the fusion-supporting reads reported by Arriba, because Arriba does not count those either.

**Comment by wiltbb** [comment]
> Can you elaborate what is the purpose for which you want to calculate the expression?
Ok,I want to count the difference in expression between fusion genes and normal genes so I must calculate the expression.

**Comment by suhrig** [comment]
I see. In that case, it is best to sum up `split_reads1` + `split_reads2` + `discordant_mates` and divide it by `coverage1` + `coverage2`. This will give you an estimate of the fraction of expression coming from the fusion. Say, the value is 0.5, this would mean that about half the expression comes from the fusion. In reality you will usually get much lower numbers between 0 and 10%.

Again, the previously mentioned caveats apply. This is only a rough estimate. You will get slightly more accurate numbers if you also count reads listed in the `filters` column, i.e., `split_reads1` + `split_reads2` + `discordant_mates` + reads listed in the `filters` column. The reason is explained in the [manual](https://arriba.readthedocs.io/en/latest/current-limitations/#supporting-read-count-vs-coverage). However, you will need to manually parse the `filters` column to extract the numbers from it.

**Comment by wiltbb** [comment]
> parse the `filters`

I think this should be fine with a few  commands in shell.

> `split_reads1` + `split_reads2` + `discordant_mates` + reads listed in the `filters` column.

Do you mean that I put this result together with the results of common genes to compare the differences?

**Comment by suhrig** [comment]
> Do you mean that I put this result together with the results of common genes to compare the differences?

No. I mean you divide this by `coverage1` + `coverage2` to get a measure of how much of the expression is explained by the fusion and how much by the wildtype genes. The number will be sort of an average over both fused genes. If you want them to be separated by gene (e.g., you have a EML4-ALK fusion and want to know how much of EML4's expression is explained by the fusion), then the following formula gives a rough answer:

(`split_reads1` + `discordant_mates`) / `coverage1`

For ALK, it would have to be `split_reads2` and `coverage2`, since ALK is the second gene.

There will be edge cases where you will get values > 1, which does not make a lot of sense, of course. Moreover, it is debatable whether the discordant mates should be included in the calculation or not. Most of the time they are close to the fusion breakpoint so it is fair to include them. If they are far away, then they would not be reflected in the coverage computation, which can lead to quotients begin > 1. As I said, it is not really possible to normalize the fusion expression, because the quantification of fusion-supporting reads is just so error-prone and because the reads are distributed over two genes.

Let me know if you need further clarification.

**Comment by wiltbb** [comment]
> I mean you divide this by `coverage1` + `coverage2` to get a measure of how much of the expression is explained by the fusion and how much by the wildtype genes.

I think you have provided a good way to analyze the expression of fusion genes. In another paper([https://doi.org/10.1186/s13059-022-02696-w](url)), the authors write "Using the same reference genome coordinate, if the region for an FPKM value had more than 50% sequence overlap to a fusion gene or homologous short copies, the FPKM value was used as the expression signal measurement for the relative genes."  I would like to know if this means the same thing as what you are saying above? Thank you very much.
