### ISSUE TITLE
e-value threshold

### ISSUE THREAD

**Issue by notthathime** [suhrig/arriba#189]
Hi! Thank you for your great work.
I have a few questions and hope you can help me out. 
1 -i CONTIGS default is chromosomes 1-22, X, and Y as well as viral genomes named AC_* or NC_*. Can I modify the filter and will it affect the specificy of the result?

2 What is the appropriate range for -E value? The default is 0.3 but I tried with different E values up to 100 and resecued fusion involving the genes of my interest. Is it fine to set it to 100 and filter further on the more strict supporting reads filter? I noticed you answered a similar question and suggested to  completely disable it using -f relative_support. Will the result still be reliable? 

Thank you!

**Comment by suhrig** [comment]
1. You can modify the list of contigs. ChrM is missing on purpose, because it's a separate genome in the mitochondria and translocations between chrM and the genome in the nucleus are unlikely to happen. If you are interested in genomic rearrangements within chrM, you can add it, and just ignore fusions with the nuclear chromosomes, which are probably all artifacts. Moreover, Arriba's filters were not designed for chrM, which has much different coverage characteristics than the nuclear chromosomes. I would expect to see many false positives among fusion predictions within chrM, too. The e-value filter is probably useless. And you will probably have to increase the minimum number of supporting reads (`-S`) to remove artifacts.

2. I wouldn't increase the value more than an order of magnitude, i.e., 3. It becomes ineffective for very high values and you might as well just disable the filter using `-f relative_support`. You can test the effect of playing around with the threshold yourself by looking at Arriba's output. For each filter, it reports the number of remaining candidates after applying the filter.

> Is it fine to set it to 100 and filter further on the more strict supporting reads filter?

You can do this, but you will lose sensitivity in genes with low coverage, because these genes have only few supporting fusion reads.

**Comment by notthathime** [comment]
Hi! Thank you so much for your quick response.
I will just disable the filter using -f relative_support instead of changing the E value.
