### ISSUE TITLE
How breakpoints should be interpreted on doubled 5' transcript end gene-fusions?

### ISSUE THREAD

**Issue by alejandrogzi** [suhrig/arriba#194]
Hi @suhrig!

Since our last chat I successfully run Arriba over more than 1,000 dog transcriptomes. Before processing the cancer samples with this new huge gene-fusion background I wanted to reach you for some questions:

1) How should I interpret fusions with doubled 5' transcript ends ? For example:

PARVA(121742),ENSCAFG00845019330(5346) | TEAD1
-- | --
ENSCAFG00845007992(8844),RUSC2(45807) | RUSC2 |  

Here Arriba found supporting reads for two genes that make up the 5' end of each fusion. So, for the first row 2 different fusions are reported "PARVA-TEAD1" and "ENSCAFG00845019330-TEAD1"; therefore, if I wanted to build a catalogue of fusions both fusions should be explicitly and independently reported, right?. The second row shows a similar example; however, since one of the fusions ocurred within the intergenic region of RUSC2, it is then logical that RUSC2 appeared in both columns:

intergenic | 5'UTR/splice-site
-- | --

This arises subsequent questions:

2) How does information should be interpret in this type of fusions? Does the site1 belongs to ENSCAFG00845007992 or RUSC2?
3) The confidence for that fusion is calculated for both at the same time? Meaning that "PARVA-TEAD1" and "ENSCAFG00845019330-TEAD1" are both high confidence fusions, for example.

I am attaching one .tab file just for reproducibility purposes: [arriba_example.txt](https://github.com/suhrig/arriba/files/11470895/arriba_example.txt).

Thanks in advance,
Alejandro

**Comment by alejandrogzi** [comment]
@suhrig did you have time to check this? 

Best,
Alejandro

**Comment by suhrig** [comment]
Hi Alejandro,

Apologies for not getting back to you. I didn't have time to reply right away and then your request got pushed down in my inbox by a flood of other mails. In the future, if I don't reply within a week, feel free to nudge.

I'm glad to hear you managed to process a sizable number of samples.

Whenever one of the columns `site1` or `site2` contains the value `intergenic`, it means that the genes listed in the respective columns `gene1` or `gene2` are **not** involved in the fusion. The breakpoint is located outside any gene. Merely the closest genes are listed along with the distance to these genes in parentheses. In your example, the breakpoint is between the genes `PARVA` and `ENSCAFG00845019330`. There is more info about how to read the columns in the manual: https://arriba.readthedocs.io/en/latest/output-files/ Consequently, the confidence score does not apply to two fusions, but just to one which has an intergenic and a genic breakpoint.

Both of your examples are alternative promotors it seems, since they are upstream of a nearby fused gene and spliced *in cis* (labeled as `read-through`). This is very common and probably these transcripts should be annotated as normal transcripts in the GTF file. The annotation is likely incomplete here.

If your intention is to build a blacklist, then I recommend not blacklisting the genes by name, but by the breakpoint coordinates. This is more specific, and your cohort size should be big enough to capture most of them.

I hope this answers your questions.

Regards,
Sebastian
