### ISSUE TITLE
coverage < split_reads

### ISSUE THREAD

**Issue by Benoitdw** [suhrig/arriba#217]
Hello,

I'm seeking clarification regarding how Arriba computes the parameters coverage

I've come across an event where "split_reads1" equals 1, "split_reads2" equals 1, and "coverage1" is 1, but surprisingly, "coverage2" is reported as 0. I'm a bit puzzled as to how "coverage2" could be 0 when "split_reads2" is 1. Logically, I would expect the coverage to be at least 1, right?
[dna_fusions.txt](https://github.com/suhrig/arriba/files/12816842/dna_fusions.txt)
(Row 17 in the result file)

While this event may not be of substantial interest to me these values appear unusual.

Any insights into this discrepancy would be greatly appreciated.

Note that I ran Arriba on DNA sample

**Comment by suhrig** [comment]
The coverage only counts non-fusion reads. Also, the coverage is computed over 20bp bins, so there can be slight deviations from the coverage at the precise fusion breakpoint. It doesn't matter so much when the coverage is above a certain level. But in cases where the coverage is near 0 it may be confusing, because a single read makes a big difference.
