### ISSUE TITLE
Known canonical fusion reported with zero reads - need help to understand the output

### ISSUE THREAD

**Issue by renjukrishna13** [suhrig/arriba#227]
Hi,
Aribba v2.1.0 was run on a patient's sample, and the output was unexpected. I reran it with the latest v2.4.0, and the result was the same. I would appreciate some explanation for the output. I've attached the pdf and the fusion table for this sample.
[14342030_fusions (2).pdf](https://github.com/suhrig/arriba/files/13814941/14342030_fusions.2.pdf)
[14342030_Fusions.xlsx](https://github.com/suhrig/arriba/files/13814940/14342030_Fusions.xlsx)

According to the attached, this sample detected two fusion events that involved the genes NAB2 and STA6. These are the expected genes for this patient's tumour type and would ordinarily be reported as confirming the diagnosis.

However, in this case, the canonical NAB2-STAT6 fusion with breakpoints at NAB2 exon 1 and STAT6 exon 4 is reported with no mapped reads, while a novel structure involving NAB2 exon 1-2 fused upstream of a truncated STAT6 has lots of supporting reads.

I wonder:

a) why does Arriba present the canonical fusion if no reads support it?

b) could the reads supporting the novel structure also map to the canonical structure - i.e. is this an error in the Arriba output?

I am happy to share any additional files or information you need. Thanks!

**Comment by suhrig** [comment]
> a) why does Arriba present the canonical fusion if no reads support it?

The columns `split_reads_1`, `split_reads_2`, and `discordant_mates` only count reads which were not discarded by any filters. In the column `filters` you will find two reads: one which was discarded by the `mismatches` filter and another one which is a duplicate. So there are two supporting reads, but they are of poor quality.

> b) could the reads supporting the novel structure also map to the canonical structure - i.e. is this an error in the Arriba output?

It looks to me like the second fusion (the one with 0 supporting reads) is not the relevant one in this tumor, even though it may be the canonical one. The first fusion looks more relevant to me given it's much higher expression. This fusion also creates an in-frame transcript containing all protein domains of STAT6. So it should have the same biological effect. It has a bit of an unusual breakpoint in the 5'UTR of STAT6, but the codons from the UTR happen to yield an in-frame transcript. There is no stop codon between the fusion breakpoint and the start codon of STAT6.

The only mistake that Arriba made is that it chose the wrong STAT6 transcript ID for the first fusion. It should have chosen the same transcript as it did for the second fusion (ENST00000454075). I guess it chose the wrong one, because there is good overlap between the transcribed region in the 5'UTR and the exon in the region 12:57504912-57504975.

Does this clear up your confusion?
