### ISSUE TITLE
Problem detection exom skipped

### ISSUE THREAD

**Issue by zgtman** [suhrig/arriba#231]
Dear users Arriba,

Are you also experiencing issues with detecting exon skipping using Arriba?

I can share some validated data, but I just wanted to ask if Arriba can handle this kind of fusions?

best,

Paul

**Comment by suhrig** [comment]
Hi Paul,

Arriba makes no attempt at detecting exon skips within the same gene. That explains why it does not detect your validated findings. I also have no plans to add this feature, since it is an entirely different type of analysis. Sorry I don't have a more satisfying response.

Kind regards,
Sebastian

**Comment by zgtman** [comment]
Dear suhrig,

great, thank you so much for your time and answer. Arriba is awesome!

Best,

Paul
