### ISSUE TITLE
Criteria of selecting specific transcripts

### ISSUE THREAD

**Issue by sotaro-kanematsu** [suhrig/arriba#236]
Thank you for developing such a user-friendly tool. I am currently using arriba (v2.3.0) to search for fusion genes. I believe there is a fusion.tsv file in the output results of arriba. Could you please tell me what criteria are used to select the transcript IDs in the fusion.tsv file? It would be very helpful if you could provide me with this information.

**Comment by suhrig** [comment]
Hi, I am glad you find the tool useful!

The transcript is selected based on which of the available isoforms matches the splice pattern of the fusion-supporting reads best. For example, let's say there are two transcripts for a given fusion gene: one transcript which comprises exons 1, 2, 3, and another transcript which comprises exons 1 & 3. If the fusion-supporting reads skip exon 2, then the second transcript will be selected.

Of note, Arriba does not take non-fusion-supporting reads into account. It only considers fusion-supporting reads (those listed in the column `read_identifiers`). This is because the wild-type allele and the fusion allele may express different isoforms (this happens quite frequently, actually).

Of course, there are all kinds of special cases, for example, isoforms may have overlapping exons or the fusion may involve transcription of intronic or intergenic regions. In general, Arriba chooses the transcript which explains the fusion splice pattern the best, i.e., the bases which are transcribed as part of the fusion are the closest to the bases which make up the exon.

FWIW, the exact procedure is coded in this function (for version 2.3.0): https://github.com/suhrig/arriba/blob/3a88da0833f208370ff1820c624d74d419c22bf8/source/output_fusions.cpp#L719

**Comment by sotaro-kanematsu** [comment]
Hi Suhrig!
Thank you very much for your prompt response. It's been very informative. I also appreciate you providing specific script locations; it's been helpful. To be honest, with so many cpp files, I was hesitant to search for those sections myself, as it seemed like it would be difficult.
 Currently, I am using arriba to explore fusion genes that are specifically expressed in tumor tissues. I always struggle with the tumor content and tumor heterogeneity during this process. 

While arriba does not consider non-fusion-supporting reads, it is speculated that non-fusion-supporting reads are only useful around the breakpoint. In the dataset I am currently analyzing, the insert length is approximately 300 bp. In this case, it is possible to detect fusion gene-specific isoforms if the length of exons around the fusion point is short.

 However, is it correct to assume that detecting fusion gene-specific isoforms becomes difficult when the exon length before and after the fusion point is several kb or longer?

 Additionally, in samples with low tumor content as mentioned above, it is indeed difficult to detect fusion gene-specific isoforms due to the low number of supporting reads, isn't it?

**Comment by suhrig** [comment]
Yes, both of your assumptions are correct. In this case, you may resort to using non-fusion-derived reads to infer the isoforms, but beware that they are a mixture of wild-type and fusion-derived reads.

**Comment by xiucz** [comment]
Hi, 
I use ARRIBA2.4 here, `[--transcriptSelection=provided]`. "The transcript is selected based on which of the available isoforms matches the splice pattern of the fusion-supporting reads best".  However, `ENST00000678447` may not be the best choice because of "nonsense_mediated_decay" transcript_type ?
and here is my result, 
```
G3BP2	CCNG2	-/-	+/+	chr4:76598392	chr4:78079686	5'UTR/splice-site	CDS/splice-site	inversion	3	0	1	754	266 medium	.	.	|Cyclin__N-terminal_domain(100%)	.	.	ENSG00000138757.15_7	ENSG00000138764.15_8	ENST00000678447.1_1	ENST00000316355.10_2	upstream	upstream	duplicates(1)	GTCCTTGTCGCACGTCGCAGCGCCTGGCGCCCGGGAAGAGGTGGTTGTGAGGCAGACGAACTCGCGGCTCTCCGGCTTCCGAGGCTTCCGAGTTGTCGGAGGAAGGGGGCGGCGAGCAATAAGAACCCGCCGCACCCGGTCCTCAGCGACTCTTCTGACCTCCGCGCGACGTACCCGCCGCCGCCGTTGGCTGGAG|ATGAAGGATTTGGGGGCAGAGCACTTGGCAGGTCATGAAGGGGTCCAACTTCTCGGGTTGTTGAACGTCTACCTGGAACAAGAAGAGAGATTCCAACCTCGAGAAAAAGGGCTGAGTTTGATTGAGGCTACCCCGGAG___AATGATAACACTTTGTGTCCAGG	.	LH00292:134:222N7HLT4:4:1256:26134:8956,LH00292:134:222N7HLT4:4:2111:30003:2513,LH00292:134:222N7HLT4:4:2212:9562:19714,LH00292:134:222N7HLT4:4:2312:47134:10819,LH00292:134:222N7HLT4:4:2281:3565:20149

```

![image](https://github.com/suhrig/arriba/assets/12706146/1531b028-5565-4b80-83b2-805eba2ce53b)
https://github.com/suhrig/arriba/issues/51#issuecomment-706595304

**Comment by suhrig** [comment]
Thanks for reporting this case. I agree, the selected transcript is not the best in this case. Arriba selects the transcript with the best overlap with the fusion transcript sequence. In this example, there are multiple candidates. In such situations, it simply picks the longest one - which happens to be a NMD transcript. I guess a smarter way to break such ties would be to select the one with the longest coding sequence. I will put this on my to-do list.

That being said, in this example it makes absolutely no difference which transcript is chosen. The breakpoint is in the 5'UTR. Regardless of which transcript is chosen, it has no effect on the coding sequence.
