### ISSUE TITLE
Arriba-blacklist

### ISSUE THREAD

**Issue by caranathunge** [suhrig/arriba#251]
Hi Sebastian,

Thank you for developing Arriba - it's such a user-friendly, reliable tool to use, and we have been using it in our fusion calling pipeline with great success. I have a question about the blacklist of fusions that you have incorporated in Arriba. (I tried reaching out to you via email, but couldn't, so I decided open an issue here even though it isn't an issue with Arriba per se.) 

From your paper I know that the blacklist of fusions came from a number of different sources (i.e. Human Protein Atlas, etc.), but it has been a little difficult to locate how many tissue samples from how many individuals were used to compile the blacklist of fusions. If you have that information and if it is not too much trouble, could you please share that data with me? 

Thank you!

**Comment by suhrig** [comment]
Hi Chathurani,

It's perfectly fine to ask this type of question here. Unfortunately, I don't have access to much of the data that was used for blacklisting anymore, since I no longer work at the institution which owns the samples.

From my memory, there were well over a thousand samples from a diverse set of cancer types. I blacklisted highly recurrent events from this cohort. Most patients had only one sample. I believe about 10% had more than one sample. From the Human Protein Atlas I took some 270 samples I believe. I don't recall how many samples per donor, though. From the Illumina Human BodyMap 2.0 I used about 30 samples, each of which came from a different donor I think. From the non-cancerous samples I blacklisted pretty much anything that is recurrent in at least two samples.

I hope this is sufficiently detailed. If you're thinking about creating a blacklist yourself, I recommend to have at least a couple of hundred samples/donors.

Best regards, 
Sebastian

**Comment by caranathunge** [comment]
Thank you for the quick and detailed response, Sebastian! This is really helpful. 
If you don't mind, I have a few follow-up questions:
1. Could you comment on the percentage of normal or benign tissue samples in the 1000 or so samples you used to compile the blacklist?
2. Also, do you happen to know if the normal/benign tissue samples were taken from healthy individuals (i.e. cancer-free) , or if they were taken from individuals with cancer?
3. You mentioned that you blacklisted highly recurrent events/artifacts from the cohort of 1000 samples. In tumor samples/cancerous tissue, what recurrence threshold did you use to put a fusion in the blacklist?

Thank you!

Best regards,
Chathurani

**Comment by suhrig** [comment]
1. Rough estimate: 30% benign/normal
2. They should be cancer-free.
3. I think I used 10% or 15% recurrence as the threshold. The cohort was very mixed. So there was little chance of any driver fusion recurring in more than 10% of the cohort.

**Comment by caranathunge** [comment]
Thanks for the clarification, Sebastian! This discussion has helped clear up the confusion we had about blacklisted fusions. I will go ahead and close the issue now. Thank you!

Best regards,
Chathurani
