### ISSUE TITLE
Blacklist - benign tissue samples (human and mouse)

### ISSUE THREAD

**Issue by caranathunge** [suhrig/arriba#255]
Hi Sebastian,

Thank you for the quick response to my last question (#251). We have come across another issue while running Arriba that I thought it would be best to reach out to you for clarification. I have two questions:

1. In your response to #251 you mentioned that ~300 or normal/benign tissue samples from cancer-free individuals were used to create the blacklist (in addition to recurrent artifacts from tumor samples). We recently ran Arriba on some breast cancer tumor samples with default settings and for good measure, we included 20 normal tissue samples to filter out tumor fusions present in benign tissue. We were not expecting to see many as we had already applied the blacklist filter. However, we found 11 tumor-fusions in our normal samples, and surprisingly, some of them (in bold) that passed through Arriba's blacklist filter had a recurrence rate of >5% within our normal samples.

- **SNORD3A-CH507-528H12.1**
- **ACTB-CH507-528H12.1**
- **AC015688.3-LGALS9DP**
- **ACTG1-CH507-513H4.1**
- **CATSPER2P1-RP11-315A19.1**
- LINC00993-ANKRD30A
- POLRMTP1(82744),RPL36AP47(8087)-NPEPPS
- CIITA-CLEC16A
- **ARL17B-KANSL1**
- **AP001347.6-ANKRD20A11P**
- **FSIP1-RP11-624L4.1**

I see that some of these fusions are lncRNA-associated, and some have breakpoints in intergenic locations, and non-coding RNA-genes, etc. My question is have you already applied a filter to remove these types of fusions from Arriba blacklist that somehow, these fusions got through in our search? By the way, our normal samples came from the Cooperative Human Tissue Network and the Komen Tissue Bank, so we are quite confident that the tissue came from patients without a cancer history.

2. The next question I have is related to the mouse-blacklist included with newer versions of Arriba. Could you provide some details on how the mouse blacklist was created? I know from #74 that the number of samples were fewer than what was used to create the human-blacklist. I would appreciate any information you have on the mouse samples used to identify recurrent artifacts and fusions associated with benign tissue.

Thank you!
Best regards,
Chathurani

**Comment by suhrig** [comment]
Hi Chathurani,

Thanks for taking the time to provide feedback. In particular the cohorts of normal samples may be useful resources to improve the blacklist. To answer your questions: 

1. As you have realized yourself, the blacklist is not 100% effective. It can only be as good as the data it was created from. There are many reasons why a normal fusion/recurrent artifact may not be part of the blacklist, almost all of which can be summarized as not being represented in the training data or in other words, not expressed in a sufficient number of samples in the training data. Probably, my training data didn't comprise enough samples from breast, which is why you're seeing recent fusions from normal breast tissue. Even if my training data had a lot of breast samples, it doesn't necessarily mean that the normal fusions were observed there. Some samples may simply not express the fusion transcript. Then, there are other factors such users using a different gene annotation (GTF file) than I did, which may have slight effects on the blacklist filter. In short, the blacklist can always be improved upon, and if you have additional normal samples at hand, it only makes sense to add them to your blacklist. 

> My question is have you already applied a filter to remove these types of fusions from Arriba blacklist that somehow, these fusions got through in our search?

I assume that most of them should be read-through fusions. Arriba has several filters to deal with them, yes. You could apply a more stringent cutoff by increasing the value of the argument `-R`. Please beware though that you run the risk of dropping fusions from focal deletions this way.

The ones involving ACT* genes are usually caused by extreme expression of the ACT* genes, which gives rise to all kinds of artifacts. The blacklist will probably not help with those. Arriba has other filters in place to get rid of those, but again, no filter is 100% effective.

2. If I recall correctly, I used some 400-600 samples from ENCODE. I need to check. I'm currently on travel and don't have access to my records. 

Best regards, 
Sebastian

**Comment by caranathunge** [comment]
Hi  Sebastian,

Thank you for the clarification. This is useful information for us to decide our next steps. We are debating whether to expand our normal controls with normal breast tissue samples from GTEx. Could you confirm whether any GTEx samples were used to create your blacklist? We want to ensure that we are not including the same samples again.

Thanks,
Chathurani

**Comment by suhrig** [comment]
GTEx was not used to build the blacklist. Even if it was, it wouldn't harm. If you build your own blacklist from GTEx and add it on top of the existing blacklist, just remove the duplicate entries. You should to this either way to keep the blacklist small. Then, it also doesn't matter if you're building a blacklist from samples that were already part of the blacklist.

**Comment by caranathunge** [comment]
Thank you, Sebastian! I really appreciate your help and input. We have decided to expand our normal controls with GTEx and go from there.
