### ISSUE TITLE
Questions regarding known fusions and batch processing

### ISSUE THREAD

**Issue by Visayas892** [suhrig/arriba#262]
Hi there!

First of all, thanks for sharing this incredible tool - works like a charm!
We want to implement a RNA fusion calling pipeline for our routine haemato oncological diagnostics and so far, all of our 40 samples we tried for establishment/validation were called correctly.

My questions are minor:
Firstly, I'd like to try rerunning above samples with the known fusions + tags, but I was only able to find known fusion files for hg19? Running the pipeline on hg38 to be up to date - not sure if I can just use the hg19 known fusions without problems?

Secondly, I'm not sure if I can't find the right argument, but is it possible, to load annotations/assemblies and keep them in memory, until all the analyses are processed?
I wrote a short script to batch process our outputs (8 patients multiplexed resulting in a pair of fastq's each) and a lot of run time comes from the loading/unloading of the annotations for each sample.

´Thank's in advance!

**Comment by suhrig** [comment]
> I was only able to find known fusion files for hg19

The known fusions for hg38 are in `database/known_fusions_hg38_GRCh38_v2.4.0.tsv.gz` in the release download. Let me know if you have trouble finding it. You cannot use files from a different assembly version, because the coordinates are incompatible.

> load annotations/assemblies and keep them in memory, until all the analyses are processed

This is not possible, unfortunately. It should only take 1-2 minutes, though. So it's rather quick. Does it take longer for you? Reading the BAM file takes a couple of minutes usually, so loading the assembly/annotation makes up only a fraction of the runtime normally.

**Comment by Visayas892** [comment]
Hello again,

please excuse - my mistake - no idea how but somehow I must've lost the known fusions hg38 file (facepalm). Untared the package again and found it.

Alright - I just noticed the pipeline being "stuck" at "Loading annotation" often, but as I wrote - minor issue. Was just wondering if the reloading can be skipped for optimization :)

Thank you!
