### ISSUE TITLE
Explanation of best-select filter ?

### ISSUE THREAD

**Issue by BrunoFant** [suhrig/arriba#27]
Hi Sebastian,

I am coming back to you after a few weeks of extended use and integration of arriba (still a great tool :) ). I am running it with the -T -P options.

In one of my samples, I had a series of results that I have been wondering about :

> CSNK1D  SUZ12P1 -/-     +/+     17:82251379     17:30734897     splice-site     splice-site     inversion       upstream        upstream        0       3       14      902     149     high    .       .       duplicates(14),mismatches(1)       GCTACCCTT___CCGAATTTGCCACATACCTGAATTTCTGCCGTTCCTTGCGTTTTGACGACAAGCCTGACTACTCGTACCTGCGGCAGCTTTTCCGGAATCTGTTCCATCGCCAGGGCTTCTCCTATGACTACGTGTTCGACTGGAACATGCTCAAATTT|AGCCAACACAGATCTATAGATTTCTTTGAACTCGGAATCTCATAGCA___CCAATATTTTTGCACAGAACTCTTACTTACATGTCTCATCGAAACTCCAGAACAAACATCAAAAG___GAA...AGCTTGTCAGCTCATTTGCAGCTTACATTTTTGGTTTCTT     out-of-frame    YPSEFATYLNFCRSLRFDDKPDYSYLRQLFRNLFHRQGFSYDYVFDWNMLKF|sqhrsidffelgis*       .
> CSNK1D  SUZ12P1 -/-     +/+     17:82251379     17:30759491     splice-site     splice-site     inversion       upstream        upstream        0       1       4       902     278     medium  .       .       duplicates(3),mismatches(1)        CATACCTGAATTTCTGCCGTTCCTTGCGTTTTGACGACAAGCCTGACTACTCGTACCTGCGGCAGCTTTTCCG...CATCGCCAGGGCTTCTCCTATGACTACGTGTTCGACTGGAACATGCTCAAATTT|CTTGTCAGCTCATTTGCAGCTTACATTTTTGGTTTCTTCCACAAAAATG___ATAAGCCATCA...AAAATGAACAAAATTCTGTTACCCTGGAAGTCCTGCTTGTGAAAGTTTGC    out-of-frame    HRQGFSYDYVFDWNMLKF|lvssfaayifgffhkndkp  .
> CSNK1D  SUZ12P1 -/-     +/+     17:82252434     17:30766503     splice-site     splice-site     inversion       upstream        upstream        0       1       0       1016    238     low     .       .       duplicates(1)      ATCGAAGTGTTGTGTAAAGGCTACCCTT|ATAAGCCATCACCAAACTCAGA...TCCAATAAGGCAAGTTCCCACAGGTAAAAAGCAGGTGCCTTTGAATCCTG        out-of-frame    IEVLCKGYP|ykpspns       .

As you can see, arriba detected several fusions between the same pair of two genes (all of them at different splice sites of SUZ12P1). However, according to the best-select filter description, "If there are multiple breakpoints detected between the same pair of genes, this filter discards all but the most credible one."  What is happening in this case ? Does another filter overrule the best-select ?

Thank you in advance for your time,
Best,
Bruno

**Comment by suhrig** [comment]
Hi Bruno,

The `select_best` filter makes the subsequent filters more effective, because these filters only need to discard a single candidate for each pair of genes. The likelihood that an artifact slips through all filters is reduced, simply because the total number of candidates is reduced. Moreover, the `select_best` filter eliminates redundancy in the final output file.

You guessed correctly that there is one filter that overrules the `select_best` filter: The `isoforms` filter recovers alternatively spliced fusion transcripts. The filter simply searches for fusions between the same pair of genes having both breakpoints at splice sites. You can turn it off by running Arriba with `-f isoforms`. It has no effect on filtering, i.e., disabling the filter merely removes *additional* transcript isoforms. The ability to report alternatively spliced fusion transcripts may be of interest to some users, which is the reason the filter exists.

Regards,
Sebastian

**Comment by BrunoFant** [comment]
Ah so it's the isoform filter ! Thanks a lot, it's indeed pretty helpful to have this information, and also helps to assess biological relevance. Thank you very much, issue closed for me :)

Best,
Bruno
