### ISSUE TITLE
tarball contains .git

### ISSUE THREAD

**Issue by roryk** [suhrig/arriba#28]
Hi Suhrig,

It looks like the release tarball has the .git directory included in it, is that intentional?

```
arriba_v1.1.0/.git/objects/82/cd1803664f28f864d8e84e5e65e86c25eff653
arriba_v1.1.0/.git/objects/82/4b29862c4e75ac77ccedaaa7c37d7c2e504f5f
arriba_v1.1.0/.git/objects/82/8dd1cff22901bff9b303d5164ac578e3c2b9ce
arriba_v1.1.0/.git/objects/74/
arriba_v1.1.0/.git/objects/74/60c082bbf9c511783691f0405ce57dd90ca2d9

``` 
etc.

**Comment by suhrig** [comment]
Hi Rory,

Thank you for the thoughtful hint. I am aware of this. I thought about removing it, but figured it does not harm and is in fact convenient for users, because this way they obtain the full bundle (binaries, source code, database files) in a single download. Ss far as I can see, the only reason the directory should be excluded is Github's file size limit (100 MB). Since the tarball is still smaller than that, I don't see a need to do so at the moment. Do you see any other reason that I should be aware of?

Regards,
Sebastian

**Comment by roryk** [comment]
Hi Sebastian,

Thanks for the quick response. No, no reason, just noticed it when untarring it and was wondering.
