### ISSUE TITLE
-i doesn't take a space separated list

### ISSUE THREAD

**Issue by roryk** [suhrig/arriba#29]
Hi @suhrig,

When using the `-i` option, passing a space-separated list only grabs the first one in the list:

```bash
arriba -x ${test_bam} -g ${test_gtf} -a ${test_fasta} -o ${sample}-withi-fusions.tsv -o ${sample}-withi-fusions.discarded.tsv -i 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y

Filtering mates which do not map to interesting contigs (1) (remaining=73956)
```

```bash
arriba -x ${TEST_BAM} -g ${TEST_GTF} -a ${TEST_FASTA} -o ${SAMPLE}-withi-fusions.tsv -o ${SAMPLE}-withi-fusions.discarded.tsv -i 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y

Filtering mates which do not map to interesting contigs (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y) (remaining=1543505)
```

The documentation says spaces or commas work, though.

**Comment by suhrig** [comment]
Hi Rory,

If you use spaces, you need to put the whole list in double-quotes:

```
-i "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y"
```

Otherwise bash (or whatever shell you are using) passes the list as separate arguments.

On the other hand, omitting the quotes should throw a different error, such as `Unknown argument "2"`. Let's see if I can enhance parameter parsing to complain about excess arguments ...

Regards,
Sebastian

**Comment by suhrig** [comment]
Hi Rory,

The next release of Arriba will issue an error when arguments with spaces are not wrapped in quotes. I just implemented it. Thanks again for pointing this out. I'm closing this issue now.

Regards,
Sebastian

**Comment by roryk** [comment]
Thanks Sebastian!

**Comment by suhrig** [comment]
One more note after having a quick peek at your code: Instead of building external commands as a string and executing them via a shell, you might want to switch to Python's `subprocess` module. Otherwise, you will be running into issues whenever an argument has blanks in it - not just with Arriba, but with any program. For example, if you try to call `cat` on a file with blanks in the name, it will throw an error unless you wrap the file name in quotes, because it will try to look for several files:

```
$ cat file with blanks
cat: file: No such file or directory
cat: with: No such file or directory
cat: blanks: No such file or directory
```

Proper usage:

```
$ cat "file with blanks"
Hello, world!
```

See this stackoverflow thread: https://stackoverflow.com/questions/204017/how-do-i-execute-a-program-from-python-os-system-fails-due-to-spaces-in-path/204049#204049

And here some more info: https://janakiev.com/blog/python-shell-commands/

**Comment by roryk** [comment]
Thanks for the tip!
