### ISSUE TITLE
Gene ID's in output

### ISSUE THREAD

**Issue by umieat** [suhrig/arriba#30]
Hello,

When reporting fusion genes, is there a way to output gene ID's as well as names.
I was trying to use htseq-count for counting reads mapped to each exon of fusion genes. I also use STAR-Fusion together with Arriba; STAR-Fusion reports both gene name with gene ID.

Thanks.

**Comment by suhrig** [comment]
Hi,

Arriba itself cannot output gene IDs and names at the same time. But you can tell Arriba to output IDs instead of names by changing how GTF files are parsed. Run Arriba with the following argument to make it use the `gene_id` attribute instead of the `gene_name` attribute to fill the columns `gene1` and `gene2`:

```
-G "gene_name=gene_id gene_id=gene_id transcript_id=transcript_id feature_exon=exon feature_CDS=CDS"
```

Once you have gene IDs in the output file, you can manually annotate the gene names using the following awk snippet. I appends two columns `name1` and `name2` at the end.

```
awk '{
  if (FILENAME ~ /gtf$/) {
    match($0, /gene_id "[^"]*"/)
    id = substr($0, RSTART+9, RLENGTH-10)
    match($0, /gene_name "[^"]*"/)
    name = substr($0, RSTART+11, RLENGTH-12)
    map[id] = name
  } else { # fusions.tsv
    map["#gene1"] = "name1"
    map["gene2"] = "name2"
    print $0"\t"map[$1]"\t"map[$2]
  }
}' annotation.gtf fusions.tsv
```

Note that intergenic breakpoints would not be annotated with gene names using this snippet. They would simply produce blank `name1/2` columns.

Alternatively, you could prepare a modified GTF file which has both gene ID and name in the `gene_name` attribute:

```
sed -e 's/gene_id "\([^"]*\)"\(.*\)gene_name "\([^"]*\)"/gene_id "\1"\2gene_name "\3~\1"/' annotation.gtf > modified_annotation.gtf
```

When you pass this modified GTF to Arriba, the gene columns will contain names and IDs separated by a tilde.

Are those workarounds acceptable?

Regards,
Sebastian

**Comment by umieat** [comment]
Thank you,
I didn't get want to get rid of gene name all together, because I'm also using for further downstream analysis.
By preparing modified gtf before running Arriba using this
`sed -e 's/gene_id "\([^"]*\)"\(.*\)gene_name "\([^"]*\)"/gene_id "\1"\2gene_name "\3~\1"/' annotation.gtf > modified_annotation.gtf`
I'm able to get results that I need.

Issue is closed for me.

Regards,
Ümit
