### ISSUE TITLE
Can't compile with make release

### ISSUE THREAD

**Issue by SethosII** [suhrig/arriba#31]
When I try to compile `Arriba` with the `release` flag I get the following error:

```
$ make release
...
make LIBS_SO="" LIBS_A="htslib-1.8/libhts.a " CPPFLAGS="-DHAVE_LIBDEFLATE -Ihtslib-1.8/htslib -I../static_libs_centos6.9"
make[1]: Entering directory '/dev/shm/arriba_v1.1.0'
make -C htslib-1.8 CPPFLAGS="-DHAVE_LIBDEFLATE -Ihtslib-1.8/htslib -I../static_libs_centos6.9" LDFLAGS="" libhts.a
make[2]: Entering directory '/dev/shm/arriba_v1.1.0/htslib-1.8'
gcc -g -Wall -O2 -I. -DHAVE_LIBDEFLATE -Ihtslib-1.8/htslib -I../static_libs_centos6.9 -c -o bgzf.o bgzf.c
bgzf.c:39:10: fatal error: libdeflate.h: No such file or directory
 #include <libdeflate.h>
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:121: recipe for target 'bgzf.o' failed
make[2]: *** [bgzf.o] Error 1
make[2]: Leaving directory '/dev/shm/arriba_v1.1.0/htslib-1.8'
Makefile:27: recipe for target 'htslib-1.8/libhts.a' failed
make[1]: *** [htslib-1.8/libhts.a] Error 2
make[1]: Leaving directory '/dev/shm/arriba_v1.1.0'
Makefile:34: recipe for target 'release' failed
make: *** [release] Error 2
```

Is the `htslib-1.8` folder supposed to include the `libdeflate` library or how is the `release` flag supposed to work? And can you document this in the installation instructions? Also what is supposed to be in `STATIC_LIBS` or `static_libs_centos6.9`?

**Comment by suhrig** [comment]
Hi Paul,

End-users are actually not supposed to use the `release` make rule. It's a special rule for developers who build Arriba for a GitHub release. That is why it is not mentioned in the [installation instructions](https://arriba.readthedocs.io/en/latest/quickstart/). This rule builds Arriba with libraries that are compatible with older operating systems, such as CentOS 6.9. The directory `static_libs_centos6.9` is expected to contain these libraries (bgzf, deflate, ...). Normal users should just type `make` without any arguments (or simply use the precompiled binaries in the tarball). I actually recommend using the precompiled binary, because it comes with deflate, which speeds up reading of BAM files by 10-20%. When you compile yourself, then this is not enabled by default. There is no real disadvantage to using the precompiled binary. If you still want to compile yourself *with deflate*, then I can send you detailed instructions. Let me know.

Regards,
Sebastian

**Comment by SethosII** [comment]
Hi Sebastian, thank you for the explanation. I would be interested in the instructions for compiling it with deflate.

**Comment by suhrig** [comment]
Here are the instructions (tested on CentOS 6.9):

```
# install compilers
yum groupinstall "Development Tools"
yum install wget

# compile libdeflate
cd /data/uhrigs/arriba
mkdir static_libs_centos6.9
wget -O - 'https://github.com/ebiggers/libdeflate/archive/v1.3.tar.gz' | tar -xzf -
make -C libdeflate-1.3
cp libdeflate-1.3/libdeflate.{a,h} static_libs_centos6.9

# compile zlib
wget -O - 'https://zlib.net/zlib-1.2.11.tar.gz' | tar -xzf -
(cd zlib-1.2.11 && ./configure && make)
cp zlib-1.2.11/{zlib.h,zconf.h,libz.a} static_libs_centos6.9

# compile bzip2
wget -O - 'https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz' | tar -xzf - 
make -C bzip2-1.0.8
cp bzip2-1.0.8/{bzlib.h,libbz2.a} static_libs_centos6.9

# compile lzma
wget -O - 'https://tukaani.org/xz/xz-5.2.4.tar.gz' | tar -xzf -
(cd xz-5.2.4 && ./configure && make)
cp -r xz-5.2.4/src/liblzma/{.libs/liblzma.a,api/lzma,api/lzma.h} static_libs_centos6.9

# compile arriba
make release
```

**Important note**: Rerunning these instructions from scratch brought a small mistake in the `Makefile` to my attention. The `Makefile` as it is now uses `zlib.h` of the system package `zlib-devel` instead of using the one in the `static_libs_centos6.9` directory. Either you install `zlib-devel` by running the command `yum install zlib-devel` (a bit of a dirty hack) or you modify the `release` rule in the `Makefile` to look like this:

```
release:
        $(MAKE) LIBS_SO="" LIBS_A="$(LIBS_A) $(wildcard $(STATIC_LIBS)/*.a)" CPPFLAGS="-DHAVE_LIBDEFLATE $(CPPFLAGS) -I$(STATIC_LIBS) -I../$(STATIC_LIBS)"
```

(Essentially, you need to add `-I$(STATIC_LIBS)`).

I'll gladly help out, if you run into issues.

**Comment by SethosII** [comment]
That worked, thank you for the instructions!
