### ISSUE TITLE
Chimeric.out.sam vs Aligned.out.bam

### ISSUE THREAD

**Issue by foxchase** [suhrig/arriba#34]
Dear Arriba,
Inspection of events using IGV needs two files Chimeric.out.sam and Aligned.out.bam using run_arriba.sh generates Aligned.out.bam only. Is it possible to get Chimeric.out.sam from Aligned.out.bam? or is there  an option to get Chimeric.out.sam as well as Aligned.out.bam using the run_arriba.sh?

**Comment by roryk** [comment]
Hi @foxchase,

The chimeric events should already be in the BAM file (this is set here: https://github.com/suhrig/arriba/blob/477f92b6cfe10df11ff22c1ffd5ef65f1fe20243/run_arriba.sh#L31 with the `--chimOutType WithinBam` setting. You can set that to be `--chimOutType WithinBam Junctions` and also get a separate `Chimeric.out.sam` file.

**Comment by foxchase** [comment]
Thank you.

**Comment by suhrig** [comment]
Hi foxchase,

You need to run STAR with the parameter `--chimOutType separateSAMold`. This way you get the chimeric alignments in a separate file `Chimeric.out.sam`. You can then call arriba with the parameters `-x Aligned.out.bam -c Chimeric.out.sam`. Rory is right that with `--chimOutType WithinBAM` the chimeric alignments are in the main output file `Aligned.out.bam` and that's why there is no `Chimeric.out.sam`. Arriba's manual suggests `WithinBAM`, because the workflow runs a little faster that way, since Arriba and STAR run in parallel. But using `separateSAMold` works just as well.

Regards,
Sebastian

**Comment by foxchase** [comment]
Thank you Sebastian,
Yes, It works with --chimOutType separateSAMold.

Jianming
