### ISSUE TITLE
'lzma.h' file not found

### ISSUE THREAD

**Issue by chahatupreti** [suhrig/arriba#36]
Hi!

I am trying to install Arriba and on running make, it gives the error - 

`gcc -g -Wall -O2 -I. -Ihtslib/htslib -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:61:10: fatal error: 'lzma.h' file not found`

`#include <lzma.h>`

`                 ^~~~~~~~`

`1 error generated.
make[1]: *** [cram/cram_io.o] Error 1
make: *** [htslib/libhts.a] Error 2`

Do you have any idea what I could do to resolve this error? I was expecting that all files necessary for the installation would be contained within the arriba folder.

Thanks!

**Comment by suhrig** [comment]
Hi Chahat,

If you want to compile Arriba from source, you need the development files of some compression libraries. Ever since HTSlib started to support CRAM files, a few non-standard compression libraries are required for compilation, which is a bit annoying, but that's just how CRAM works.

Another user had a similar question. I documented the steps to install the compression libraries in a response to this question: https://github.com/suhrig/arriba/issues/31#issuecomment-551099842

BTW there is not really a need to compile Arriba from source. The precompiled binary should work just as well.

Regards,
Sebastian

**Comment by suhrig** [comment]
P.S. The libraries and development files can probably also be installed using the package manager of your OS (e.g., apt-get or yum), which is easier than compiling the compression libraries from source as documented in my comment in issue #31. But without known what your OS is, I cannot know what the precise commands are.

And you're right - ideally, all the dependent files should be contained in the tarball. But it has some disadvantages, too:

* The tarball would become too big (GitHub has a limit of 100 MB).
* I would have to maintain the versions of the libraries.
* Arriba would use different versions of the libraries than the rest of the OS, which is bound to cause issues in the long run (security updates, compatibility, ...).
* Some libraries are not maintained on GitHub, so I cannot just link them as a submodule.

Thanks for the hint, though. I will think about how to improve this. Maybe I should put a separate section for compilation from source in the manual.

The linked comment uses `static_libs_centos6.9` as a folder name for the compression libraries. I have since renamed the folder to `static_libs_centos6.10`. So make sure to adapt the paths accordingly. Feel free to reach out to me again, if you run into any issues.

**Comment by chahatupreti** [comment]
Thanks for the quick reply Sebastian. 

I was able to resolve the issue by installing `xz` on my system (OSX) using `brew install xz` followed by rerunning `make`. 

But I wanted to ask about something else you said - 

> BTW there is not really a need to compile Arriba from source. The precompiled binary should work just as well.

I tried to download another version of Arriba, and run it directly as such - 

```
| => cd /Users/chahat/Downloads/arriba_v1.2.0\ 2 
________________________________________________________________________________
| ~/Downloads/arriba_v1.2.0 2 @ ctcf (chahat) 
| => ./arriba 
-bash: ./arriba: cannot execute binary file
```

So it said it can't execute the binary file, but once I run `make`, then it works - 

```
| => make
g++ -c -Wall -Wno-parentheses -pthread -std=c++0x -O2 -Ihtslib/htslib -o source/annotation.o source/annotation.cpp
...
...

| => ./arriba 
ERROR: No arguments given.

Arriba gene fusion detector
---------------------------
Version: 1.2.0

Arriba is a fast tool.........
```

So, I wasn't sure if I was correct in understanding that the arriba binary was good to go right after downloading or running make was indeed required.

Thanks!

**Comment by suhrig** [comment]
I see, you're using OSX. The precompiled binary was created on Linux. That's why it throws the `cannot execute binary file` error on Mac. In this case you're absolutely right that you need to recompile from source.

I never tested Arriba on a Mac. Good to know that compilation works there, too. At the moment, Arriba is not officially supported on Mac. But I'm willing to help out in case of trouble. If you run into strange issues (segfaults, inexplicable errors, ...), let me know.

Thanks for the feedback!
