### ISSUE TITLE
ERROR: could not find sequence of contig 'Y'

### ISSUE THREAD

**Issue by chahatupreti** [suhrig/arriba#37]
Hi,
I tried running Arriba using the following command - 

`/Users/chahat/Documents/DRG/STAR-master/bin/MacOSX_x86_64/STAR --runThreadN 3 --genomeDir /Users/chahat/Documents/DRG/STAR-master/genome --genomeLoad NoSharedMemory --readFilesIn /Volumes/bam/DRG/fastq_50/PhenoInfoAvailable/23T2L.fastq --outStd BAM_Unsorted --outSAMtype BAM Unsorted --outSAMunmapped Within --outBAMcompression 0 --outFilterMultimapNmax 1 --outFilterMismatchNmax 3 --chimSegmentMin 10 --chimOutType WithinBAM SoftClip --chimJunctionOverhangMin 10 --chimScoreMin 1 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentReadGapMax 3 | /Users/chahat/Downloads/arriba_v1.2.0/arriba -x /dev/stdin -o fusions.tsv -O fusions.discarded.tsv -a /Volumes/bam/DRG/annotations/hg38.fa -g /Volumes/bam/DRG/annotations/gencode.v32.annotation.gtf.gz -b /Users/chahat/Downloads/arriba_v1.2.0/database/blacklist_hg38_GRCh38_2018-11-04.tsv.gz -T -P`

Where, I downloaded the latest hg38 fasta file from http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/latest/hg38.fa.gz  and the latest Gencode GTF annotation from [ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_32/gencode.v32.annotation.gtf.gz](ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_32/gencode.v32.annotation.gtf.gz) 

On running, I got - 

[2020-01-15T19:26:31] Loading annotation from '/Volumes/bam/DRG/annotations/gencode.v32.annotation.gtf.gz'
[2020-01-15T19:27:11] Loading assembly from '/Volumes/bam/DRG/annotations/hg38.fa'
ERROR: could not find sequence of contig 'Y'

Any ideas why this error could be occuring?

**Comment by suhrig** [comment]
This may either be a case of unexpected behavior on Mac, or your `hg38.fa` is really missing the `Y` chromosome (probably due to a corrupt download). Can you check, if the sequence is present:

```
grep chrY /Volumes/bam/DRG/annotations/hg38.fa
```

This should give you:

```
>chrY
>chrY_KI270740v1_random
>chrY_KZ208923v1_fix
>chrY_KZ208924v1_fix
>chrY_KN196487v1_fix
```

I just tested the FastA and GTF files you linked. Arriba does not throw the error on my system (Linux). I will test it on a Mac next. Hopefully, I will find some time tomorrow.

**Comment by chahatupreti** [comment]
It's pretty strange. I do have the Y chromosome - 

```
| => grep chrY /Volumes/bam/DRG/annotations/hg38.fa
>chrY
>chrY_KI270740v1_random
>chrY_KZ208923v1_fix
>chrY_KZ208924v1_fix
>chrY_KN196487v1_fix
```

And yet it gives the error I mentioned! This is very mysterious.

**Comment by suhrig** [comment]
I was able to reproduce your problem on a Mac! Just as suspected the root cause is a Mac peculiarity. The function I use to check if a file is empty behaves differently on Mac than on Linux. Mac always reports the file as empty and therefore nothing gets read at all. Arriba only complains about chromosome Y, because that's the first one it checks, but really all of the chromosomes are missing.

Incidentally, I have already fixed the issue in my local code repository, because I recently made some optimizations to the routine that loads the assembly. This optimization happens to circumvent the Mac issue. I will push the changes to GitHub sooner or later. Until then, there is an easy workaround: You should only pass gzipped files to Arriba (i.e., whenever you use `-a`, `-g`, `-b`, `-d`, or `-k`). Loading of gzipped files uses different code, so there the issue is not triggered. BAM and SAM files (arguments `-c` and `-x`) need not be zipped, because they also use different code for loading.

**Comment by chahatupreti** [comment]
Hi Sebastian, 

Your suggestion to use the gzipped file worked! Thanks a lot for the prompt and detailed response.
