### ISSUE TITLE
Outdated Bioconductor Installation Instructions

### ISSUE THREAD

**Issue by DarioS** [suhrig/arriba#38]
The user guide advises the user to execute

```r
source("https://bioconductor.org/biocLite.R")
biocLite("GenomicAlignments")
biocLite("GenomicRanges")
```

but about a year ago, this was stopped because of security issues. The correct way to install packages now is to install BiocManager from CRAN and then

```r
library(BiocManager)
install("GenomicAlignments")
```

There is no need for the user to separately install GenomicRanges because that will automatically happen during the installation of GenomicAlignments because GenomicRanges is in the Depends field of the DESCRIPTION file of GenomicAlignments, so the install command will take care of it.

Also, there's nothing in the user guide which explains if there's a Google Groups site or how to contact the developer with questions.

**Comment by suhrig** [comment]
Hi Dario,

Many thanks for the good suggestions! I will make sure to apply them for the next release.

Regards,
Sebastian

**Comment by suhrig** [comment]
Hi Dario, I updated the installation instructions in the manual. Thanks again for bringing this to my attention! I decided to keep `GenomicRanges` and `GenomicAlignments` separate, because they are used independently in my scripts and hypothetically there is no guarantee that one package will always automatically pull the other.
