### ISSUE TITLE
DNA fusion detect

### ISSUE THREAD

**Issue by xieweijia** [suhrig/arriba#4]
Sience Arriba is a command-line tool for the detection of gene fusions from RNA-Seq data, I want to know how to do with DNA-seq data. looking forward to hearing from you.

**Comment by suhrig** [comment]
Arriba is not suitable to detect structural variants (SVs) from DNA-seq data. You need a structural variant caller for this task. Popular choices are:

- [Delly](http://doi.org/10.1093/bioinformatics/bts378)
- [novoBreak](http://doi.org/10.1038/nmeth.4084)
- [Manta](http://doi.org/10.1093/bioinformatics/btv710)
- [CREST](http://doi.org/10.1038/nmeth.1628)

But there are many more to choose from: https://omictools.com/structural-variant-detection-category

Once you have called SVs, you can feed this information into Arriba using the parameter `-d`. Arriba utilizes this information to improve its accuracy.

The various SV callers use different output formats. You will need to convert the output file into a format that is recognized by Arriba. You can find the details in the manual: http://arriba.readthedocs.io/en/latest/input-files/#structural-variant-calls-from-wgs

**Comment by xieweijia** [comment]
Dear suhrig,

Thank you for taking time to answer my questions. I really appreciate your help.

Best wishes,

**Comment by mkazanov** [comment]
What is the reason why Arriba can not be used to detect gene fusions from DNA-seq data?

**Comment by suhrig** [comment]
Arriba makes assumptions about the data that are note valid for DNA-Seq data, for example:

- breakpoints at splice sites are preferred
- the coverage is expected to correlate with the expression level
- there should be intron skips because of splicing
- small structural variants (< 10000 kb) are most often libprep-mediated artifacts in RNA-Seq data and therefore penalized, whereas in DNA-Seq data there are no such artifacts and these variants are often real and should not be penalized
- the blacklist was built using RNA-Seq data, such that many false positives that are present in DNA-Seq data are not filtered effectively

Structural variant callers built for DNA-Seq are not afflicted with these short-comings and should perform better than Arriba on DNA-Seq data.

**Comment by mkazanov** [comment]
Thank you for your answer! Do I understand correctly that these assumptions do not preclude that Arriba can find the correct gene fusions from DNA-seq data in many cases? So, at least we can try to apply it along with the SV detection tools, right?

**Comment by suhrig** [comment]
You will miss many intronic and intergenic variants, also most variants < 10kb. Most of those are non-coding and/or benign germline polymorphisms. So you will probably not miss a lot of stuff relevant to cancer. Still, these variants are very abundant and if you are interested in having a complete picture, then a DNA-Seq-based caller should be used.

The most relevant variants that Arriba will miss consistently in DNA-Seq data are intragenic deletions, i.e. deletions of a few exons. Arriba does not make an effort to call these at all, because they are indistinguishable from splicing in RNA-Seq data and thus futile to detect. Intragenic deletions are very relevant to cancer, however.
