### ISSUE TITLE
Event Prediction Specificity if Many Overlapping Pairs of Reads

### ISSUE THREAD

**Issue by DarioS** [suhrig/arriba#40]
I have a data set which is pairs of reads, each read being 150 bases long. The median insert size is 140 bases, so more than half of the read pairs for a sample overlap each other completely (I have done essential adapter trimming with [cutadapt](https://pypi.org/project/cutadapt/) to remove TruSeq adapter from reads ends). It seems like arriba would have problems with this data set:

>  ... and three alignments for split reads (alignments of the first and second read and a supplementary alignment of the clipped segment) ... Fragments with too few or too many alignments are removed.

If two reads that completely overlap each other have a split in them, the split would appear in both reads and so there would be four alignments and it sounds like they would be discarded by arriba. Is it so?

Also,  I notice many chimeric read pairs at a low level all across many different genes. I read on [SEQanswers](http://seqanswers.com/forums/showpost.php?s=66c91a8c039d142eca3a93d0ce4f49f6&p=199260&postcount=9) that fragmenting the RNA to very short lengths causes short fragments to randomly ligate to each other. Is there a way for arriba to handle this 'background level' of chimeras?

**Comment by suhrig** [comment]
> If two reads that completely overlap each other have a split in them, the split would appear in both reads and so there would be four alignments

In my experience, this would not generate four alignment records, but three as usual. I have dealt with such data myself and from what I have seen STAR generates three alignment records from such read pairs and Arriba deals correctly with them. If you have evidence that this would result in four alignments, then I would be very much interested in seeing an example read pair so I can investigate it.

There is an easy way to check for yourself if Arriba discards reads due to having four alignments: Have a look at the status messages of Arriba. In the line reading `Reading chimeric alignments from ... (total=X)` it tells you how many chimeric alignments were loaded from the BAM file. In the next line (`Filtering multi-mappers and single mates (remaining=Y)`) it tells you how many were kept for further analysis. The difference between `X` and `Y` it the number of alignments that were discarded due to having the issue you describe. A few is normal, because some reads cause STAR to produce malformed SAM records. If it's hundreds or thousands, then it may be a concern. Note: Old versions of STAR (e.g., 2.3.0) produced a lot of malformed SAM records, which should not have ended up in the `Chimeric.out.sam`, so there it was sane to discard these alignments without loss of important information.

On a related note: If you know that your data have many overlapping pairs of reads, you should run STAR with the parameter `--peOverlapNbasesMin 10`. STAR is known to have issues aligning chimeric reads when the mates overlap and this parameter helps with that. I plan on adding this parameter as a default in the demo script `run_arriba.sh` in the next release.

> Also, I notice many chimeric read pairs at a low level all across many different genes.

In the main output file of Arriba? This could be artifacts resulting from random ligation or true fusion calls resulting from a complex rearrangement between a group of genes (e.g., chromothripsis). You can find some [advice in Arriba's manual on how to spot in vitro-generated artifacts](https://arriba.readthedocs.io/en/latest/interpretation-of-results/#frequent-types-of-false-positives). Scroll to the section `In vitro artifacts`.

> Is there a way for arriba to handle this 'background level' of chimeras?

Yes. This is the duty of the `pcr_fusions`, described [here](https://arriba.readthedocs.io/en/latest/internal-algorithm/#event-level-filters). As every filter, it is not perfect and on some samples fails to remove some false positives. This is because these in vitro-generated fusions have many characteristics of driving fusions (high expression), so the filter is cautious not to accidentally discard a driving fusion. If you think about it, this type of artifact is notoriously difficult to remove, because *there physically are chimeric fragments in the library*, so a fusion detection algorithm is technically not wrong when it reports such fusions. It's just that they are not relevant to cancer and therefore not of interest. Arriba tries it's best to get rid of them. If you still see samples with a lot of obvious in vitro-generated artifacts and have the possibility to share the data, I would be interested in getting my hands on it, because then I might be able to improve the filtering. Note that the most recent release of Arriba `1.2.0` comes with some improvements that address exactly this issue, so it could be worth running this version if you have only run older versions.

**Comment by DarioS** [comment]
- Indeed, it never creates four records now that I check the read alignments. I was just using my intuition which is incorrect.

```r
> chimerics <- read.delim("cancerChimeric.out.sam", skip = 28)
> range(table(chimerics[, 1]))
[1] 1 3
```

- I have been using `--peOverlapNbasesMin 10` for a long time since the sequencing service provider generates this kind of data for all of our biologist collaborators, unfortunately.

- No; I noticed the chimeric pairs in IGV. I have not yet run arriba on any data sets I have, but I'm assessing which fusion algorithm will give the best control of false positives. A screenshot of STAR's chimeric SAM file from an older poly-A enriched RNA-seq data set (reads coloured by chromosome of their mate) in IGV:

![image](https://user-images.githubusercontent.com/631218/72774140-9c4ae300-3c5d-11ea-8963-ea6a31cbcafd.png)

Perhaps a simple visualisation like this could be useful advice for novice users for the Frequent Types of False Positives section of your user guide.

> This could be artifacts resulting from random ligation or true fusion calls resulting from a complex rearrangement between a group of genes (e.g., chromothripsis).

Ah, I thought I could tell real events from preparation artefacts by looking for sharp peaks of chimeric reads. But, I suppose that chromothripsis could also cause chimeric reads to be spread out which causes them to look like artefacts. It's tricky.

The data set I am analysing currently is a total RNA sequencing with ribosome depletion. Therefore, there are a proportion of premature RNA with introns sequenced. Using GENCODE Genes to categorise sequencing reads as exonic and intronic, I see about 30% to 70% of reads per sample mapping to introns. Some famous gene fusions happen in introns, such as PAX3-FOXO1 fusion, which was recently analysed in [Nature Genetics in December 2019](https://www.nature.com/articles/s41588-019-0534-4).

![image](https://user-images.githubusercontent.com/631218/72774798-019fd380-3c60-11ea-91ff-2e0abe205555.png)
Source: [Atlas of Genetics in Oncology](http://atlasgeneticsoncology.org/Tumors/t213q35q14AlvRhabdoID5013.html)

Could I identify such fusions if they were in my data set or is arriba tailored to poly-A RNA sequencing which has mature mRNA with introns spliced out? I have whole genome DNA sequencing for all of the total RNA data set samples, so I anticipate it should give good results, at least on the exonic fusions.

**Comment by suhrig** [comment]
> Ah, I thought I could tell real events from preparation artefacts by looking for sharp peaks of chimeric reads.

You can, and that's what Arriba does. Just that the peaks aren't always as sharp as you would expect them. Arriba uses its own statistical model to decide if a peak is "sharp enough", which can be as little as a few reads in a pile of a hundred. This depends on many factors.

> Some famous gene fusions happen in introns, such as PAX3-FOXO1 fusion

While it is true that the large majority of fusion arise from breaks in introns (on the DNA level), on the RNA level you hardly every see these breaks. Here, the breakpoints are at exon boundaries.

Even with ribo-depleted libraries you will notice that Arriba usually picks a breakpoint at an exon boundary. This is because Arriba reports the breakpoint with the most supporting reads. This breakpoint corresponds to the transcript with the highest expression in the cancer cell and should thus be most relevant.

Arriba is able to detect PAX3-FOXO1 fusions. If you want to be extra sensitive, you can pass Arriba a file via the parameter `-k` and the following content:

```
PAX3	FOXO1
```

Arriba will then detect the fusion even when there is little evidence (1-2 supporting reads). This is helpful with low-purity samples. In my experience, increasing the sensitivity this way does not hurt specificity, as long as you don't put thousands of combinations of genes in the known fusions file.

> Could I identify such fusions if they were in my data set or is arriba tailored to poly-A RNA
> sequencing which has mature mRNA with introns spliced out?

I have tested Arriba successfully with both types of data. Breakpoints in intronic regions can be detected - as long as there is at least one supporting read that overlaps with an exon, which is most often the case. You can remove this condition by disabling the `intronic` filter using `-f intronic`, but I don't recommend doing so, because it will hurt specificity and is rarely necessary to detect an event.

> I have whole genome DNA sequencing for all of the total RNA data set samples

That's going to be very helpful. I recommend making use of *all* of the SV calls when you benchmark the fusion detection tools. Don't just check, which tool picks up the expected PAX3-FOXO1 fusion. Just because a tool makes an additional 100 calls, does not mean it is worse than one that only makes 10 additional calls, since many of the 100 calls may be true positives. You should check which tool picks up most of the SV calls and should balance that with the total number of calls. Also, please note that the low-confidence calls of Arriba have a high false-positive rate (~90%). You are free to ignore them. They are only there for people with a need for high sensitivity.

**Comment by DarioS** [comment]
Excellent explanation!
