### ISSUE TITLE
Support for Hisat2?

### ISSUE THREAD

**Issue by JspSrs** [suhrig/arriba#46]
Hi Sebastian,

We would like to investigate the effect of some large copy number gains (SV, CNV), but also screen some of our patients for unexpected events. Currently we align using Hisat2 mainly en use Kallisto for counting. I am not an bioinformatician myself, but have some support.
Sofar I understand both aligners do not give output compatible with Arriba. Do you know whether this understanding is correct? And are you thinking on generating support for other aligners or a file converter?
Best regards, Jasper Saris

**Comment by suhrig** [comment]
Hi Jasper,

Arriba accepts chimeric reads in the standards-compliant SAM format. It is thus designed for interoperability. Unfortunately, to my knowledge, neither Hisat2 nor Kallisto report chimeric reads in this format. Hisat2 only reports discordant mates, but no split reads. And last time I checked, Kallisto used a proprietary text-based output format. The best you could do is to extract the chimeric reads reported by one of the methods and realign only them using STAR. Effectively, this would reduce the purpose of STAR to a file format conversion tool. I have used this approach successfully with Kallisto in a small test. Specifically, I converted Kallisto's proprietary text format `fusion.txt` to FastA files and fed those into STAR. But generally speaking, I cannot recommend this approach. You loose a lot of sensitivity, because (1) Arriba then only sees the reads that are alignable by both Kallisto and STAR, and (2) Kallisto only reports gene-to-gene fusions, but lacks information about intronic and intergenic breakpoints.

For Hisat2, you would have to extract all unaligned reads, discordant mates, and soft-/hard-clipped reads and convert them back to FastQ (using bamtofastq, for example) and pass them to STAR, which would then produce a `Chimeric.out.sam` file to be passed to Arriba. However, the best option would be to ask the developers of Hisat2 to report split alignments using the supplementary alignment flag as specified by the SAM format spec.

Regards,
Sebastian

**Comment by JspSrs** [comment]
Hi Sebastian,

Clear to me, Thx.  I suppose we will start with option 1+2, using STAR via a local Galaxy.
I will separately contact the Hisat2 developers.

Best regards, Jasper

**Comment by suhrig** [comment]
Hi Jasper,

This is an old question, but I now have a workable solution to your question. In case other users search for HISAT(2) compatibility and come across your post, I am answering here.

There is now a script section in repository. One of the scripts ([run_arriba_on_prealigned_bam.sh](https://github.com/suhrig/arriba/blob/develop/scripts/run_arriba_on_prealigned_bam.sh)) lets you use existing alignments from any aligner (e.g., from HISAT2) and realign only the reads that are relevant to fusion detection: unmapped reads and clipped reads. All other reads are taken as is. The script still has to make use of STAR for realignment, because STAR still is the only aligner out there which reports chimeric alignments in SAM-compliant format. So strictly speaking, it is not based on HISAT2. But this script can be used as an efficient addon to a HISAT2-based alignment workflow. In my tests, the script typically used only 10-15% of the CPU time of what a complete realignment would take.

The script has two limitations:

- The fusion calls will differ slightly from a complete realignment and may be inferior. Officially, I still recommend doing a complete realignment, because this method is well-tested.
- The script does not scale well. It does not parallelize beyond 2 CPUs, because the script is mostly concerned with extracting relevant reads from the prealigned BAM file, and this process is not easy to parallelize with standard command-line tools.

Admittedly, this solution is not as clean as if HISAT supported chimeric alignments natively. But I am not sure if this will ever be the case. The corresponding issue on in the HISAT2 repo has been opened years ago and no progress has been made. In contrast, my proposed solution works, and it is computationally much more efficient than doing a complete realignment, which may be important to some users. Also, this solution is very flexible. It works with pretty much any aligner.

Regards,
Sebastian
