### ISSUE TITLE
Advice and Explanation About Multi-mapping Chimeric Reads

### ISSUE THREAD

**Issue by DarioS** [suhrig/arriba#50]
When next updating the user guide, can you add a paragraph about multi-mapping chimeras? It seems that setting `--chimMultimapNmax` to a higher number [will be possible in a couple of weeks](https://github.com/alexdobin/STAR/issues/816#issuecomment-591538113) when the next version of STAR is planned to be released.

**Comment by suhrig** [comment]
Thanks for the notification. I am aware of this already, as it was me who submitted this pull request. There currently is a (very brief) paragraph about multi-mapping chimeras in the manual already, in the chapter about [current limitations](https://arriba.readthedocs.io/en/latest/current-limitations/). However, I actually planned on *removing* this paragraph, since it will no longer be limitation. I already have a prototype of Arriba that can deal with multi-mapping chimeras and I will try to make it public at around the same time that the STAR pull request is merged.

I could add a section about multi-mapping chimeras somewhere else, but frankly, I wouldn't know what to write there. The usage of Arriba remains exactly the same and handling of multi-mapping chimeras is going to be absolutely transparent to the user. What would you like to read in such a section?

**Comment by DarioS** [comment]
Ah, it will all just fall into place soon.
