### ISSUE TITLE
most highly expressed transcript

### ISSUE THREAD

**Issue by erprateek** [suhrig/arriba#51]
Hi Sebastian,

WIth the `-T` option, I know it is possible to output the transcript sequence for the detected fusion. I am wondering if there is a flag for generating the Ensembl transcript ID as well. 

Thanks,
Prateek

**Comment by suhrig** [comment]
Unfortunately no. There probably should be, since you are not the first one to ask for this. I still have not implemented this, because it would change the output format and would thus require a major version change, which I am generally reluctant to, because major version changes mean that existing pipelines that make use of Arriba could break. Then again, Arriba 1.x has been around for a while and I plan on releasing a new version with substantial enhancements, so maybe it is time for a new major version. I'll think about it.

Could you tell me what you would use this information for? This would help me with the design. If I add such a column, I want to make sure it's useful and informative.

**Comment by erprateek** [comment]
I am trying to mimic how we stored outputs from previous tools in our database without changing the schema. Transcript IDs was a part of them. SInce I am not the one ultimately involved in the assessment, Im not super clear myself how this is used.

Meanwhile could you point me in the direction how to get this information? My idea would be to take the breakpoint and intersect with the ranges in the GENCODE19.gtf (for that gene), get the list of transcripts that fall in that range and perform an alignment of reads (output courtesy of arriba) against a tiny transcript db of that gene and pick the top result. Do you see a better way of achieving this?

**Comment by suhrig** [comment]
Sounds like a good approach and this is actually what Arriba does internally sort of; just that it does not have to do an alignment, because it can use the already aligned reads of STAR and match the splice patterns to annotated transcripts.

Alternatively, you could also take a simpler route: Most breakpoints are at splice sites. You could select transcripts that have exon boundaries at the given breakpoints. If there are multiple candidates to choose from (usually the case), pick the canonical transcript. This is what `draw_fusions.R` has done in the past. The newer version that I am currently working on interrogates the coverage, which selects more fitting transcripts in my experience.

Both of the above would mean you have to reinvent the wheel, because Arriba already determines the transcript internally. It's a bit complicated and would probably be quite some effort for you to develop. I can offer you a third option: I have been thinking about making the next release of Arriba a new major version (2.0.0) and have pretty much come to the conclusion to do this. This would allow me to add new columns to the output file, e.g. `transcript1` and `transcript2`. Until the 2.0.0 release is out, I could push an intermediate version to the development branch for you to use. I would need a week or two to complete this, however.

**Comment by JspSrs** [comment]
Although, I am currently not running the pipeline I am involved in actual verification of RNAseq results and normal patient-wise studies of the actual effects of variants. And from tha point of view I was triggered by 'pick the canonical' transcript. I would like to share some suggestions or options.
In (diagnostic) practice the canonical is the longest (coding) transcript, while from e.g. the GTEx initiative we know which ENST is the prevalent one. This is insightful shown by the gnomAD database from the Broad Institute (see button transcripts). Which does link out to the GTEx portal for the actual data).
Separate from that initiative there is the MANE project from Ensembl, NCBI and UCSC to come to 'one' reference transcript for a reference gene. For which recently a track was released by UCSC (both for hg19 and 38)

I hope the above is helpful in planning for your release 2.

**Comment by suhrig** [comment]
Thanks for your input, Jasper! But I don't want to open that can of worms. :-D I know your pain, since I have to deal with this question myself often enough. In my opinion, there is no such thing as a canonical transcript - after all, the predominant transcript is tissue specific - and all the different databases contradicting each other seems to support that notion. So far, I have taken the pragmatic route and simply relied on what the GTF file provided by the user defined as canonical. I will stick with that in the future, because trying to figure out the canonical transcript myself would be a whole endeavor on its own. Letting the user decide (by means of choosing a GTF file) offers users maximum flexibility and spares me from breaking my head over this. Nevertheless, your advice is appreciated!

**Comment by suhrig** [comment]
I just pushed an enhanced version of Arriba to the `develop` branch. It includes two new columns `transcript_id1` and `transcript_id2`, which should contain the information you need. You can obtain the new version using these commands:

```
git clone https://github.com/suhrig/arriba.git
cd arriba
git checkout develop
make
```

Please beware that this is a development version of Arriba. Although it should run fine in practice, it has not been tested as thoroughly as official releases. Also, there are definitely going to be additional changes to the output format (new columns added, some rearranged) in the next official release, so please be flexible with regards to changes.

**Comment by suhrig** [comment]
Forgot to mention: The parameter `-P` must be specified for the transcript ID columns to be filled. This is a requirement that will likely be removed with the next official release.

**Comment by erprateek** [comment]
Thanks Sebastian! This is great! I did a test run using the develop branch verified that I am able to successfully generate Transcript IDs now as well.

On one sample, change from 1.2.0 to bleeding edge develop caused the number of detected fusions count to go from 28 -> 97. I am guessing there is more work to do. I was also able to get something implemented meanwhile based on your suggestion of closest transcript exon from breakpoint. I guess the increase in the number of calls would need to be looked at. This is just based on a wc -l command on before and after outputs. I will keep you posted of any other findings that I get.

**Comment by suhrig** [comment]
> caused the number of detected fusions count to go from 28 -> 97. 

Can you share the data of that sample? It's hard to figure out what is different with this sample that causes a filter to fail. I made changes to two filters (`mismappers`, `end_to_end`) that could explain the additional fusion predictions. If you grep for the breakpoints in the discarded fusions file of the old Arriba, the column `filters` tells you which filters used to discard the new predictions in the previous version.

**Comment by erprateek** [comment]
Hey Sebastian, 
I am still trying to characterize those results observed. Too many things going on at the same time. Meanwhile, I noticed that in the bleeding edge version, blacklist filter throws some warnings like this:
WARNING: unknown gene or malformed range: 2:91679087-91679734     22:22380474-23922495
WARNING: unknown gene or malformed range: 2:91679087-91679734     2:89156674-90458671
WARNING: unknown gene or malformed range: 2:91679087-91679734     14:106053226-107288019
WARNING: unknown gene or malformed range: 2:92005797-92006650     22:22380474-23922495

It does end up getting rid of fusions from 1500 -> 450 though. Just in case this is unexpected and might cause more fusions to stay behind.

**Comment by suhrig** [comment]
The warnings are the result of an error in the blacklist of Arriba v1.2.0. I accidentally used blanks as column separators instead of tabs for some of the lines. Arriba v2.0.0 will be more strict when it comes to parsing TSV files and will not accept blanks any longer. So strictly speaking, the warning should already have been shown in earlier versions, but wasn't due to sloppy parsing of TSV files by earlier versions. You can fix the blacklist yourself with the following commands:

```
gunzip blacklist_hg19_hs37d5_GRCh37_2018-11-04.tsv.gz
sed -i -e 's/   */\t/' blacklist_hg19_hs37d5_GRCh37_2018-11-04.tsv
gzip -9 blacklist_hg19_hs37d5_GRCh37_2018-11-04.tsv
```

Make sure to copy and paste the `sed` command to copy the correct number of blanks!

> It does end up getting rid of fusions from 1500 -> 450 though

So you're saying one sample shows an increase of predictions from 28 -> 97; another sample shows a decrease from 1500 -> 450?

**Comment by erprateek** [comment]
Oh sorry by the reduction in numbers I meant that the blacklist step is working. Thanks for the fix!

**Comment by suhrig** [comment]
Transcript IDs are now reported in the output of Arriba 2.0.0. By default, `draw_fusions.R` does not evaluate the transcript ID columns of Arriba, however. Instead, it chooses the transcripts that produce nice coverage profiles, which if often not the case when transcripts are chosen by splice pattern (what Arriba does internally). You have the possibility to change this behavior by means of the `--transcriptSelection` parameter. It has three options: `coverage` (default), `provided` (use transcripts provided in Arriba's output file), `canonical` (use transcript annotated as canonical in GTF file).
