### ISSUE TITLE
error with GTF features argument parsing

### ISSUE THREAD

**Issue by MariusGheorghe** [suhrig/arriba#52]
Hi,

First of all, good job with arriba :] 
I was trying to export some additional information from the GTF file by making use of the `-G "<my_gtf_features>"` parameter, but I (always) get:
`ERROR: Malformed GTF features: "<my_gtf_features>"` even if I use only one value that is also present in your defaults.
A concrete example launching arriba (v1.2.0):
```
marius@dev:~/fusion$ arriba -x chr21.bam  -o chr21_fusions.tsv -O chr21_fusions_discarded.tsv -a GRCh38.fna -g ensembl_annotation.gtf -b arriba/arriba_v1.2.0/database/blacklist_hg38_GRCh38_2018-11-04.tsv.gz -T -T -P -P -I -I -G "gene_name=gene_id"
ERROR: Malformed GTF features: gene_name=gene_id
```
If I remove the `-G "gene_name=gene_id"` part, the run finishes successfully. Any feature I specify with `-G` ends up in `ERROR: Malformed GTF features`.
Head of my GTF file:
```
chr1	ensembl	CDS	100149045	100149097	.	-	2	gene_id "ENSG00000122477"; gene_version "12"; transcript_id "ENST00000342895"; transcript_version "7"; exon_number "9"; gene_name "LRRC39"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "LRRC39-201"; transcript_source "ensembl"; transcript_biotype "protein_coding"; tag "CCDS"; ccds_id "CCDS766"; protein_id "ENSP00000344470"; protein_version "3"; tag "basic"; transcript_support_level "5";
chr1	ensembl	CDS	100149371	100149435	.	-	2	gene_id "ENSG00000122477"; gene_version "12"; transcript_id "ENST00000620882"; transcript_version "4"; exon_number "9"; gene_name "LRRC39"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "LRRC39-204"; transcript_source "ensembl"; transcript_biotype "protein_coding"; tag "CCDS"; ccds_id "CCDS58014"; protein_id "ENSP00000480740"; protein_version "1"; tag "basic"; transcript_support_level "5";
```

Ideally I would like to extract more info from the GTF file, but I see that your object has "only" 5 attributes: 
```
struct gtf_features_t {
	vector<string> gene_name;
	vector<string> gene_id;
	vector<string> transcript_id;
	vector<string> feature_exon;
	vector<string> feature_cds;
};
```
so to get more "metadata" I tried concatenating everything else (separated by `;` or `|`) from the GTF file (from column 9 to end of line) as the value for `gene_id`, and then leaving the rest of the columns intact. This works, but it's rather an ugly hack. Is there a plan to implement some `metadata` column in the output? Maybe a different issue for that.

Thank you in advance.

Marius

**Comment by suhrig** [comment]
Hi Marius,

I'm glad you find the tool useful.

> I (always) get: `ERROR: Malformed GTF features: "<my_gtf_features>"` even if I use only one value that is also present in your defaults.

Arriba keeps complaining about this, because you need to specify **all** the features. All of them are required by Arriba for proper parsing of the GTF file. Otherwise, it cannot sort out which exon/transcript belongs to which gene, which genes are coding and how exons are represented.

> Ideally I would like to extract more info from the GTF file, but I see that your object has "only" 5 attributes:

I deliberately use a minimal representation, because I don't want to restrict users in what GTF file they use (GENCODE, ENSEMBL, RefSeq, ...) and this is the minimal consensus between all. If Arriba required more information to be present, some GTF files would be incompatible.

> so to get more "metadata" I tried concatenating everything else (separated by ; or |) from the GTF file (from column 9 to end of line) 

This is actually not the way to go. If you concatenate the whole ninth column of the GTF file and put it as `gene_id`, then Arriba is mislead to believe that each line belongs to a separate gene. The results would be hardly useful. At the moment, your best option is to annotate the output file of Arriba using some tool like bedtools. You will need to reformat the coordinates, but this should not be to complicated. Let me know, if you need help with this.

> Is there a plan to implement some metadata column in the output? Maybe a different issue for that.

Yes! I'm glad you bring this up, because just a few days ago, I have been contemplating whether I'd want to do this or not. I am currently thinking about releasing a new major version (still far from being finalized, but anyway). And this was one potential new feature that came to my mind. So far, I thought about adding a `tags` column that is filled with whatever tags a user supplied in a separate file, probably via a new parameter `-t`. I thought about making it a three-column tab-separated format like this:

```
gene1	gene2	tags
```

`gene1` and `gene2` could be gene names or regions (e.g., `1:3254385-3843095`) and a value in `gene2` would probably be optional. This could be used to tag fusions with oncogenes or known fusions, for example.

Regards,
Sebastian

**Comment by MariusGheorghe** [comment]
Hi Sebastian,

Thank you for the quick and detailed reply. 
I see. So I have to specify the complete list of parameters. Maybe being a bit more explicit in the doc would help other users like me. Like "note: all parameters have to be specified". Now looking at the code I see the return statement of the GTF feature parser:
```
return !gtf_features.gene_name.empty() &&
	       !gtf_features.gene_id.empty() &&
	       !gtf_features.transcript_id.empty() &&
	       !gtf_features.feature_exon.empty() &&
	       !gtf_features.feature_cds.empty();
``` 
missed this bit :roll_eyes: 

I saw also that if I mush all the data as the "gene name" then arriba produces thousands of lines in the output instead of the expected handful. So I guess it outputs all combinations of all genes. Probably that's what you meant by the output being hardly useful :D I'll use a third party tool then to get the info I need.

Yeah, good idea with adding some sort of `tag` column. Looking forward to the new release. Again, thank you very much for the support and keep up the good work :]

I consider this issue closed

Marius
