### ISSUE TITLE
Cannot work with Slurm 18.8

### ISSUE THREAD

**Issue by jzj2035198** [suhrig/arriba#57]
Arriba works correctly on my local computer, but when I ran it on my server with slurm 18.8, It said it could not find sequence of contig X. I guess Arriba is  incompatible with slurm 18.8.

**Comment by suhrig** [comment]
Hi Zijie,

It should not matter if you run Arriba in the context of a job scheduler or not. I have not tested Arriba with Slurm, but with several other job schedulers and I doubt that the error you are seeing has anything to do with it. Much rather it could be a compilation / system / usage error. What is the operating system that you run Arriba on? Can you paste the full command of Arriba? Are you using the precompiled binary that comes with the download package or have you recompiled the code yourself?

Regards,
Sebastian

**Comment by jzj2035198** [comment]
I recompiled the code. OS: CentOS 7.6

I found I could correctly run Arriba 1.0.1 with Slurm using the same command , but neither version 1.1.0 or 1.2.0 can work. 

I ran it using the run_arriba.sh.

 Command: 
sh run_arriba.sh hg19StarIndex_2.7.2b_normal/ gencode.v19.annotation.gtf.gz hg19.fa database/blacklist_hg19_hs37d5_GRCh37_2018-11-04.tsv.gz 1_1.fastq 1_2.fastq 20

**Comment by suhrig** [comment]
If it works with 1.0.1 and fails with >=1.1.0, then the issue is the same as #37. What's interesting, though, is that this is the first time someone runs into this error on Linux. So far, this error has only been observed on MacOS.

The gist of the error is that (due to a bug) Arriba fails to read plain text files. You can circumvent the error by giving it gzip-compressed files. If you gzip-compress `hg19.fa`, then it should work. Alternatively, you can download the current the latest code from the `develop` branch, where the bug has been fixed already. I don't necessarily recommend the latter, however, because the code has not been tested as well as the release versions.

**Comment by jzj2035198** [comment]
Good, it works now. Thanks
