### ISSUE TITLE
Fusion orientation determination

### ISSUE THREAD

**Issue by erprateek** [suhrig/arriba#58]
Hi Sebastian,

I have been noticing for some samples that detected fusions contain nearly identical but reverse orientation (5' partner - 3' partner =>  3' partner - 5' partner ) records. Do you have a recommendation for consolidating these?

Example these records:

SMAD4   MEX3C   +/-     -/+     18:48584495     18:48722937     CDS     CDS     inversion       upstream        upstream        141     37      8       1615    637     high    .       .       duplicates(196),inconsistently_clipped(9)
       GTCCACGTATCCATCAACAGTAACAATAGGGCAGCTTGAAGGAACCTTAAATGTCTCTCCTACCTGAACATCCATTTCAAAGTAAGCAATGGAACACCAATACTCAGGAG___CAGGATGATTGGAAATGGGAGGCTGGAATGCAAGCTCATTGTGAACAGGCC___AGTAATGTCCGGGATGGGGCGGCATAGGCGGGTGGTGCTGAAGATGGCCGTTTTGGTGGTGAGGCAAATTAGGTGTGTATGGTGCAGTCCTACTTCCAGTCCAGGTGGTAGTGCTGT___TATGATGGTAAGTAGCTGGCTGACCAGTAAATCCATTCTGCTGCTGTCCTGGCTGAGGCCCTGATGCTATCTGCAACAGTCCTTCACTATGGCTGCCCCCCAGTATACTGGCAGGCTGAC|CCTGGCGGCCGACGATCTCGGCGACGTGCTCGGAGCTGGGCACCGGGACGCACTCGGTGGTGTTGACGCTCTTTCTCCGGAGCAGGGCCGCCTGCTCCCCGTTCAGGGCGGCCGCCGCCGCCCCACAACCGCCGGGGCCGTAGGCGTGGGACAGCATCGCCGCCATCATGCCCTGGGCATCGTCCCCTCCGTACAGCACCCCCGCCGCCGCCGCCGCGG     .       .

MEX3C   SMAD4   -/+     +/-     18:48703946     18:48581363     CDS     CDS     inversion       downstream      downstream      15      50      2       227     714     medium  .       .       duplicates(51),inconsistently_clipped(1)
        CGGAGTTACTATGTAGGTGTGGGTCTGCTGCTGAATTCTTTTAATAGTTGCTCCTTTGGGTCCAACCACTAATCCTACCACACGATAAGGGACCCTGACTTGGACGGTGGTTTGACCGGGCAGATTAGGACTACATGATAATCCTCCCAGGGCAGGCCCATTTTTGTTTCGAGATGCACGAATCATGGAGAAGTGCTCTGCAGCTGAGAGGATCTCTCTTTTGGCCATGG
CAACATCTTCTTTCCTTCCAGTGACAACAAAAATGGGCTCTTCACCACGAACAGGAGTCTTGATATACGTGTTTGTCTTGGCTCTCAGTGCTTTAATTTTACAAC|TTGTGGAAGCCACAGGAATGTTGGGAAAGTTGGCAGTGCTGGTAGCATTAGACTCAGATGGGGCTAACAGAGCTGGGGTGCTGTATGTCTCTGTCGATGCACGATTACTTGGTGGATGCTGGATGGTTTGAA
TTGAATGTCCTTCAGTGGACAACGATGGCTGTCCCTCAAAGTCATGCACATATTCATCCTTCACCATCATACTTGATGGAG___CATTACTCTGCAGTGTTAATCCTGAGAGAT___CAATTCCAGGTGATACAACTCGTTCGTAGTGATATGGATTCACACAGACACTATCACATTTTAAGTCAAACGCATACTGACAATATTTAACATGTTTTAGTTCATTTTTGTGAAGATCAGG
CCACCTCCAGAGACG       .       .

Thanks,
Prateek

**Comment by erprateek** [comment]
Also, for TMPRSS2-ERG fusion, I checked 2 samples that are known to have that fusion.

In sample 1 the orientation is correct: TMPRSS2-ERG
In sample 2 the orientation is flipped: ERG-TMPRSS2.

In these two samples, the respective reciprocal fusions are not called at all i.e. sample1 does not call ERG-TMPRSS2 and sample2 does not call TMPRSS2-ERG. Sample1 and Sample 2 are not the same samples.

**Comment by suhrig** [comment]
Hi Prateek,

Arriba reports all orientations of which it finds evidence in the RNA-Seq data. The assignment of 5' and 3' gene is far from random and follows carefully designed logic, taking breakpoint orientation, strandedness, and splice patterns into account. There is no real way to "consolidate" the orientation. Arriba simply reports what is supported by the data.

The SMAD4-MEX3C could be a reciprocal rearrangement resulting in reciprocal fusions. The TMPRSS2-ERG fusions *should* always be reported with TMPRSS2 as the 5' gene and ERG as the 3', because this is the biologically active fusion protein. But sometimes there are not enough reads in the data for Arriba to detect the correct orientation. Nevertheless, in case of TMPRSS2-ERG fusions, you can safely assume that there is a TMPRSS2-ERG fusion, when Arriba reports only an ERG-TMPRSS2 fusion. In view of the high prevalence of this fusion in prostate cancer, it would be a gigantic coincidence, if the tumor harbored a non-functional ERG-TMPRSS2 fusion (as a passenger event), but no functional TMPRSS2-ERG fusion.

Regards,
Sebastian

**Comment by erprateek** [comment]
Closed by mistake

**Comment by erprateek** [comment]
Hey an interesting find. I tested the bleeding edge version of Arriba on that same sample that output ERG-TMPRSS2 only. With latest code, I get TMPRSS2-ERG. I wonder some of the changes since 1.2.0 fixed this issue?

**Comment by erprateek** [comment]
And so it went for the other fusion as well. Maybe this can be added to the next release bugfix notes

**Comment by suhrig** [comment]
Interesting ... I did not make changes to the code that determines the 5' and 3' ends of the fusion. Probably, some other changes now cause Arriba to choose a different breakpoint that happens to have the genes in proper orientation. You should see that the breakpoints are different ones than before. Another explanation is the known fusions list: Are you using one and are the fusions supported by very few reads? If yes, then it's a change I made to the blacklist that now causes Arriba to only report known fusions, if the partners are in proper orientation.

**Comment by erprateek** [comment]
Just documenting for reference
* Now:
MEX3C   SMAD4   -/-     +/+     18:48722937     18:48584495     splice-site     splice-site     inversion       upstream        upstream        37      141     8       647     1615    high    .       .       duplicates(197),inconsistently_clipped(9) 
* Previously:
SMAD4 MEX3C +/- -/+ 18:48584495 18:48722937 CDS CDS inversion upstream upstream 141 37 8 1615 637 high . . duplicates(196),inconsistently_clipped(9)

I think so the improved strand detection might be the place where this is handled

**Comment by suhrig** [comment]
You're right. It's the strand detection that was wrong. But I neither have I changed that code in the recent past. Hm ...

The last time I made notable changes to strand detection was between versions 1.0.1 and 1.1.0. If strand detection now really is different, you should see that the line saying `Detecting strandedness` comes to a different conclusion. Whatever the reason may be, I don't mind if things work better than before. ;-)

**Comment by erprateek** [comment]
Infact detecting strandedness does not come to a different conclusion, it is still the same. Since the issue is fixed, I am going to close it.

**Comment by sufyazi** [comment]
Hi Sebastian,

Apologies for necro-ing this old thread but I am facing an baffling phenomenon with Arriba (and several other tools) on an established cancer cell line fusion dataset (Edgren et al.), where a small subset of fusion pairs called by Arriba (and others) is turning up in the reverse order; for example. *BCAS3::MED13* and *MRPL45::TRPC4AP* were previously reported (and validated by Edgren et al), were called as *MED13::BCAS3* and *TRPC4AP::MRPL45* in the output of newer algorithms (including yours).

Your statement here helps enlighten me on what could be happening;

> The assignment of 5' and 3' gene is far from random and follows carefully designed logic, taking breakpoint orientation, strandedness, and splice patterns into account. There is no real way to "consolidate" the orientation. Arriba simply reports what is supported by the data.

and 

> But sometimes there are not enough reads in the data for Arriba to detect the correct orientation.

I am not too worried about this in light of your explanations because I'm just testing out different algorithms on the validation dataset, but in your opinion, is it wise or sufficient to chalk this up to differences in algorithms? The Edgren dataset was quite old by this point and the first paper it appeared in couldn't even test the currently mainstream algos like yours and STAR-Fusion because they didn't even exist yet. 

I also wonder if it's valid to consider those two example fusion pairs as "detected by Arriba/STAR-Fusion/[insert whatever algorithm that returns the reversed order fusions]"? Do you have any thoughts or opinions?

Best,
Suffian

**Comment by suhrig** [comment]
Hi Suffian,

> Apologies for necro-ing this old thread

No problem.

> were called as MED13::BCAS3 and TRPC4AP::MRPL45 in the output of newer algorithms (including yours).

The evidence is pretty clear here. I am convinced that this is the correct orientation. The splice pattern clearly supports this orientation. I am not sure what Edgren et al. found and validated. (I couldn't find a mention of these fusions in their paper. Sorry, if I overlooked it.)

> is it wise or sufficient to chalk this up to differences in algorithms?

There are three reasons why orientations may be discrepant:

1. Algorithms make mistakes (spit out the wrong orientation, because they interpret the data incorrectly).
2. The data is ambiguous. Especially unstranded RNA-seq data with low coverage is affected by this. Without sufficient reads supporting the fusion and no strand information, it can be a coin-toss to get the orientation right.
3. Both orientations are correct ([balanced translocation](https://github.com/suhrig/arriba/wiki/08-Interpretation-of-results#multiple-transcript-variants)). However, one fusion caller only detected one orientation and another caller detected only the other orientation.

> I also wonder if it's valid to consider those two example fusion pairs as "detected by Arriba/STAR-Fusion/[insert whatever algorithm that returns the reversed order fusions]"?

Absolutely, yes. All three reasons above are minor mistakes, in my opinion. The main finding a fusion caller should report is a fusion between two genes. Even if the orientation is wrong, it will catch the attention of the analyst. Let's say you analyze a sample with a reported FLI1-EWSR1 fusion. This is the wrong orientation. However, it's a stone's throw away to jump to the relevant conclusion that the tumor carries a EWSR1-FLI1 fusion. The analyst can then check the alignments manually to double-check whether there is evidence in the data for the correct orientation (and likely find it if it exists). Sure, it would be ideal to report the correct orientation in the first place, but I would still count it as a "close enough" call.

Best regards,
Sebastian

**Comment by sufyazi** [comment]
Thank you Sebastian, this is very very helpful and reassuring. Just to be clear, I was referring to the paper by Kangaspeska et al. [https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0048745], which is a follow up study by Edgren et al group, not the original paper. My bad.

Thanks again!
