### ISSUE TITLE
transcript sequence ambiguity from reads

### ISSUE THREAD

**Issue by erprateek** [suhrig/arriba#62]
Hi Sebastian,

I have a particular fusion event for which I get a transcript sequence as follows:

> CGAGGGTGTGTAGGCGGCAGCAATGCTCCGTTGAGAGACGCGGCTTTCGGCAAGAACTGGATTCGTGGCGCCACAAGCTCATTCACTGTGTAG___GTCCCGTTTCCCTCTGTGCGGCGGCCGGCGGGACCATAAGGGCTTAACTCATATATTTAACCCCCCTCCAAAAA___GGTTTGAAAGTATTCTTGAAGGGCTGTTTGGACCTGCATTATTAAAAGATCTCAGTTTATTTAAAG___ACTGTGAACCTGAAAGCATTTCTGATTGGACTTTTGATGAAAACTGTTTATTCTGTTGCTTGAGAAGAGATAAAGTAAAG|

> AT?A???TA?TA?TAT?A?A?A???T?A?AGT???T???GA??TT?CAGT?GAACAAGATGTGGAG??G?AAGA?AG???TtT??A??ATCCCGTCCCTGG___ATTCAACATGACTTATTTGAAAGTATCCAGTTAACTCATTTACAGATGAAAATGTGGATGATGATAAAcAAACCACTCAATTCAAAGAGAAAGTTTTCAAGTACCCAGTTCACTTTGTTCCTGAATATATACAGCAG

(Sequence newlined at the breakpoint for clarity). If you look closely, you can notice that the sequence in close proximity to the breakpoint has quite a bit of uncertainty. To ascertain the root cause of this, I queried the pileups at (and after the breakpoint coordinate) from the Star BAM. Here is what I get:

> [mpileup] 1 samples in 1 input files
> 10	113419940	A	18	.....,...,.,.....^~.	kkkkFFkkk:FFFkkkkF
> 10	113419941	T	19	.....,....,.,......	k_kkFFkkkFFFFFkkkkF
> 10	113419942	G	19	.....,....,.,......	kkkk:FkkkFFFFFkkkkF
> 10	113419943	A	19	.....,....,.,......	kkkkFF_kkFFFFFkkkkF
> 10	113419944	A	19	.....,....,.,......	kkk_FF_kkFFFFFkkkkF
> 10	113419945	G	19	.....,....,.,......	kkkkFFkk_FFFFg_k_kF
> 10	113419946	G	18	.....,.....,......	kkkkFFkkkFF:j_kk_:
> 10	113419947	T	18	.....,.....,......	kkkkFFkkkFF:k_kkkF
> 10	113419948	A	19	.....,....,.,......	kkkkFFQkkF:FF_kkkkF
> 10	113419949	C	19	.....,....,.,......	kSkkFFkkQFF:FkkkkkF
> 10	113419950	T	19	.....,....,.,......	_kkkFFkk_FFFFkkkk_F

This doesnt seem to show any ambiguity at all. Could you shed some light here?

Thanks,
Prateek

**Comment by erprateek** [comment]
To add more context, Arriba reports 35 reads supporting this fusion. 16 of those are marked duplicates in the output. The rest participate in evidence (split/discordant) reads.

**Comment by suhrig** [comment]
Hi Prateek,

I have seen this before, but only in panel sequencing data, which is why I dismissed it as an artifact of panel sequencing where you can have multiple alleles due to very deep sequencing. Thanks for making me aware that it is not specific to panel sequencing. I screened through a few hundred RNA-Seq samples and found a handful of cases similar to yours. I will try to get to the root of this. I have a suspicion that it has something to do with the strand detection of the reads. Probably, due to some bug, Arriba assigns the reads randomly to the plus and the minus strand such that the pileup done by Arriba produces a balanced distribution of complementary bases. Therefore, Arriba fails to decide for one of them. Are your RNA-Seq data stranded? What does Arriba think it is (see the log file)?

Thanks again,
Sebastian

**Comment by erprateek** [comment]
This gets detected as:

[2020-05-20T07:26:56] Detecting strandedness (reverse)
[2020-05-20T07:26:56] Assigning strands to alignments 

although the data is non-stranded

**Comment by erprateek** [comment]
For a few positions though, the pileup reveals them as reference skips (<> all along). I guess those would qualify as ones with insufficient evidence.

**Comment by suhrig** [comment]
Hi Prateek,

I just pushed a fix to the `develop` branch. The gist of the bug was that hard-clipped supplementary reads were not being used properly to assemble the transcript sequence. It had nothing to do with the detection of strandedness. Thanks again for reporting.

Regards,
Sebastian
