### ISSUE TITLE
transcript ID field is '.'

### ISSUE THREAD

**Issue by MariusGheorghe** [suhrig/arriba#68]
Hi Sebastian,

Once again, thank you for adding the transcript IDs on the `develop` branch.
I see that in some cases the transcript IDs are set to '.' so I assume that Arriba was not able to extract them from the annotation file. Is this normal or is it a bug?

Here's an example (I've removed the genomic sequences due to sensitivity):
```
CHD8    RAPGEF6 -/- -/- 14:21401477 5:131589698 CDS intron  translocation   upstream    downstream  2   0   0   135 15  low .   .   duplicates(8)   <seq_1>|<seq_2>    out-of-frame    ENST00000646647 .   <predicted_seq_1>|*   .
```

Or is it because the second part of the predicted sequence is a stop codon?

Please let me know. Thank you in advance!

P.S. Any new big release with the entire predicted protein output coming soon? :stuck_out_tongue_winking_eye:

Marius

**Comment by suhrig** [comment]
Hi Marius,

This is intended behavior. The breakpoint in RAPGEF6 (5:131589698) is deep inside an intron. The region that is transcribed as part of the fusion does not overlap any annotated transcript. Therefore, the field is left empty.

> P.S. Any new big release with the entire predicted protein output coming soon?

I have been sucked into other projects for the past two months and could not work on release 2.0 of Arriba. I have picked it up again yesterday. But since there are still many features to develop/enhance, it is going to take some time.

Regards,
Sebastian

**Comment by MariusGheorghe** [comment]
Hi Sebastian,

Thank you for the prompt reply. I understand now. Makes sense :]
Looking forward to Arriba 2.0 

Have a good day! Closing the issue

Marius
