### ISSUE TITLE
Warning when reading in custom made GTF annotation

### ISSUE THREAD

**Issue by nicodemus88** [suhrig/arriba#7]
Hi to arriba developers,

I tried using arriba to filter for fusion transcripts in my samples between virus and host. I supplied a custom made GTF file for the virus as there are no public GTF available for the virus. However, I always receive a message saying `WARNING: exon belongs to unknown gene with ID: HIV_vif` and it could not read in the virus gene annotations. 

Could you advice on how I can fix the GTF file so I can read in the annotations? I have tried multiple times with various modifications to no avail. 

Here I showed the lines for the first 3 genes of the virus annotation.

```
hiv-1_HXB2	RefSeq	transcript	456	9636	0	+	.	transcript_id "vif_01"; gene_name "Vif"; gene_id "HIV_vif";
hiv-1_HXB2	RefSeq	exon	456	742	0	+	.	transcript_id "vif_01"; gene_name "Vif"; gene_id "HIV_vif";
hiv-1_HXB2	RefSeq	exon	4912	9636	0	+	.	transcript_id "vif_01"; gene_name "Vif"; gene_id "HIV_vif";
hiv-1_HXB2	RefSeq	CDS	5041	5619	0	+	.	transcript_id "vif_01"; gene_name "Vif"; gene_id "HIV_vif";

hiv-1_HXB2	RefSeq	transcript	456	9636	0	+	.	transcript_id "vpr_01"; gene_name "Vpr"; gene_id "HIV_vpr";
hiv-1_HXB2	RefSeq	exon	456	742	0	+	.	transcript_id "vpr_01"; gene_name "Vpr"; gene_id "HIV_vpr";
hiv-1_HXB2	RefSeq	exon	5389	9636	0	+	.	transcript_id "vpr_01"; gene_name "Vpr"; gene_id "HIV_vpr";
hiv-1_HXB2	RefSeq	CDS	5559	5850	0	+	.	transcript_id "vpr_01"; gene_name "Vpr"; gene_id "HIV_vpr";

hiv-1_HXB2	RefSeq	transcript	456	9636	0	+	.	transcript_id "vpu_01"; gene_name "Vpu"; gene_id "HIV_vpu";
hiv-1_HXB2	RefSeq	exon	456	742	0	+	.	transcript_id "vpu_01"; gene_name "Vpu"; gene_id "HIV_vpu";
hiv-1_HXB2	RefSeq	exon	5975	9636	0	+	.	transcript_id "vpu_01"; gene_name "Vpu"; gene_id "HIV_vpu";
hiv-1_HXB2	RefSeq	CDS	6062	6310	0	+	.	transcript_id "vpu_01"; gene_name "Vpu"; gene_id "HIV_vpu";

```

Hope to hear back from you soon. Thank you very much.

**Comment by suhrig** [comment]
Dear nicodemus88,

Arriba requires genes to be explicitly defined in the GTF file. If you have records of type `transcript`, `exon` or `CDS`, which reference a gene via the `gene_id` attribute, then there must be a record of type `gene` introducing a gene with this ID.

Moreover, Arriba requires that records of type `gene` specify the attribute `gene_type` as `protein_coding` for protein-coding genes or some other value for non-coding genes.

Given your example, the following three lines are missing:
```
1       unknown gene    456     9636    .       +       .       gene_id "HIV_vpr"; gene_name "HIV_vpr"; gene_type "protein_coding";
1       unknown gene    456     9636    .       +       .       gene_id "HIV_vpu"; gene_name "HIV_vpu"; gene_type "protein_coding";
1       unknown gene    456     9636    .       +       .       gene_id "HIV_vif"; gene_name "HIV_vif"; gene_type "protein_coding";
```

I am currently working on the next release of Arriba, which features more robust parsing of GTF files. This release will be able to deal with the GTF file you gave as an example out of the box. Until then, you can use the following `awk` script to add the missing records and attributes:

```
awk -v FS='\t' -v OFS='\t' '!(/^$/){

  # extract gene_id
  gene_id=$9
  sub(/.*gene_id "/, "", gene_id)
  sub(/".*/, "", gene_id);
  
  # determine boundaries of genes
  gene_contigs[gene_id]=$1
  gene_strands[gene_id]=$7
  if (!gene_starts[gene_id] || $4 < gene_starts[gene_id]) gene_starts[gene_id]=$4
  if (!gene_ends[gene_id] || $5 > gene_ends[gene_id]) gene_ends[gene_id]=$5
  
  # find out if gene is protein coding based on existence of "CDS" lines
  if ($3 == "CDS") {
    gene_type[gene_id]="gene_type \"protein_coding\""
  } else if (!(gene_id in gene_type)) {
    gene_type[gene_id]="gene_type \"non_coding\""
  }
  
  print
}
END{
  # print genes
  for (gene_id in gene_starts)
    print gene_contigs[gene_id],"unknown","gene",gene_starts[gene_id],gene_ends[gene_id],".",gene_strands[gene_id],".","gene_id \""gene_id"\"; gene_name \""gene_id"\"; "gene_type[gene_id]";"
}' YOUR_CUSTOM_GTF_FILE.gtf > FIXED_GTF_FILE.gtf
```

Two more side notes:

- It seems you are using RefSeq annotation. Depending on how the GTF file was prepared, you might need to run the above awk script on the GTF, too, in order to add missing records of type `gene`. In addition, there are other minor issues with RefSeq annotation, such as gene IDs being reused for multiple copies of a gene, which might cause events to not be reported for such genes. For this reason, I generally recommend using GENCODE annotation. Moreover, the sensitivity improves with GENCODE annotation due to better annotation of splice-sites.

- Please note that you must add the contig containing the viral DNA sequence to the list of interesting contigs using the parameter `-I` of `arriba` or else `arriba` will not report any events relating to your custom contig.

Let me know, if you need further help.

Regards,
Sebastian

**Comment by nicodemus88** [comment]
Hi Sebastian,

Thank you for your reply. 

I will try out the changes you suggested and see if it works. 

On a side note, the GTF file was made by myself, not retrieved from any databases. So if I changed the RefSeq to GENCODE, would it affect the GTF file? I initially put RefSeq because I was imitating the GTF file I was using previously. However, now I have recently changed to using the GENCODE version for hg19. 

Thank you for your assistance and work! I'd really appreciate it!

**Comment by suhrig** [comment]
It does not matter at all, what the second column of your GTF file says (GENCODE or RefSeq or any other value). This column is not interpreted at all. I just assumed that apart from your custom annotation you usually use RefSeq annotation, because in your example it said "RefSeq".

What really matters are the slight differences between RefSeq and GENCODE annotation, such as having records of type `gene` and `gene_type` attributes.

**Comment by nicodemus88** [comment]
Thank you @suhrig for your comment.
I tried out the changes as per your suggestion and it works. 
Thanks again!

On a side note, are there any plans on updating the algorithm for filtering multi-mappers? As I am aware, the recent STAR update has allowed for multi-mapping chimeras, although only on the Chimeric.out.junction file for now.

**Comment by suhrig** [comment]
> I tried out the changes as per your suggestion and it works.

Glad to hear! I'm closing this issue as resolved, then.

> are there any plans on updating the algorithm for filtering multi-mappers?

Yes, definitely! But this will only be possible, if STAR reports multi-mapping reads in the `Chimeric.out.sam` file.
