### ISSUE TITLE
Core dump from renamed data

### ISSUE THREAD

**Issue by 14zac2** [suhrig/arriba#71]
Hello!

I just posted about a segmentation fault issue due to having too many contigs. You were able to fix this issue which is fantastic, but now I have run into another problem. Arriba is throwing the following error and now outputting fusions.discarded.out:

`
WARNING: not enough chimeric reads to estimate mate gap distribution, using default values
WARNING: some fusions were subsampled, because they have more than 300 supporting reads
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 766826) > this->size() (which is 513209)
run_arriba.sh: line 10: 20168 Aborted                 (core dumped) arriba -x star_output/Aligned.out.bam -f "blacklist intronic relative_support" -g ../MONAX5_and_WHV/genes/genes_renamed.gtf -a ../MONAX5_and_WHV/fasta/genome_renamed.fa -o arriba_output/fusions.tsv -O arriba_output/fusions.discarded.tsv -i "*" -I -I -T -T -S 1 -P -P -F 98`

This only started happening after I renamed the genes in both my fasta and gtf file to their appropriate human orthologs because before the gene names were fairly ambiguous. The only other difference is that I increased my STAR parameter from `--chimSegmentMin 10` to `--chimSegmentMin 15` and I read into STAR my fastq reads as 8 files separate by a comma (no space) rather than one large, concatenated fastq file. I think it is most likely that the error is coming from the new gene and contig names, but I'm not sure why I used the renamed files to make a new STAR index and anything else required for the full run of Arriba.

Please let me know if there is any more information you might find useful to help me with this issue!

Thanks,
Zoe

**Comment by suhrig** [comment]
It could also be that the bug is triggered by the second `-P` or the second `-T`. When these parameters are specified twice, the transcript and peptide sequences for the discarded fusions are computed. This should not cause a crash, but maybe disabling them would be a practical workaround.

I'm having a hard time reproducing the error. Can you send me the renamed gtf and fa files?

**Comment by 14zac2** [comment]
I can certainly send you the files (and again, really appreciate you looking at this)!

I can also tell you a few things: I know the error is not triggered by the second -P or -T as I have run this on the original GTF file. I have done some digging in the past few days and think I may have found the root of the error. I am using one:many orthologs so some of my genes have the same name. I found that when STAR makes an index, it assigns unique identifiers to the gene names that repeat themselves. This would then create a discrepancy between the indexing done by STAR and the GTF files that I then pass on to Arriba, which may cause an issue.

A work-around I have found is to simply rename the gene names in the fusion files that are outputted by Arriba, which only requires a couple of extra steps, so it is not a huge deal! I'll attach the files, though!

Genome fasta: https://www.dropbox.com/s/8rlzgs1wkqu28qb/genome_renamed.fa?dl=0
GTF: https://www.dropbox.com/s/1c0jm63mry5z2fs/genes_renamed.gtf?dl=0

**Comment by 14zac2** [comment]
Hi - tested my suspicion that the non-unique gene names were a problem by assigning unique identifiers and rerunning the pipeline. There was no error, so I do think that was the issue! Sorry for the bother and thanks again for your help!

Zoe

**Comment by suhrig** [comment]
Hi Zoe, thank you for the useful test files. I was able to track down the error and make Arriba more robust. There is a new commit now in the `develop` branch. As you figured out yourself, the problem was that gene names were used multiple times. Actually, it was transcript IDs in this particular case. From now on, whenever Arriba detects duplicate transcript IDs, it issues a warning and discards the transcript. Previously, it only did this for gene IDs. Of course, the best way to avoid this error is to provide valid annotation, but Arriba should now be more prepared to deal with problematic input, which is never a bad thing. So thanks for the feedback, Sebastian
