### ISSUE TITLE
custom blacklist file 

### ISSUE THREAD

**Issue by kopardev** [suhrig/arriba#77]
My custom blacklist file is a tsv of the format suggested by arriba documentation and looks like this ...
```
chr1:1-10000	telomere
chr1:207667-257666	contig
chr1:297969-347968	contig
chr1:535989-585988	contig
....
```
but at execution I keep getting warnings like
```
WARNING: unknown gene or malformed range: chrY
WARNING: unknown gene or malformed range: chrY
WARNING: unknown gene or malformed range: chrY
WARNING: unknown gene or malformed range: chrY
...
```
Any idea what is going on here? Whats the point of these warnings? Is my blacklist file format incorrect?
Also, my reference fasta, bam file and blacklist file has the `chr` prefix for all my chromosomes, but the output file `fusions.tsv` has breakpoints without the `chr` prefix ... Is the prefix dropped internally by arriba??

**Comment by suhrig** [comment]
> chr1:1-10000	telomere
> chr1:207667-257666	contig

This is not valid syntax actually. Sorry if the documentation is not clear on this. The keywords `telomere` and `contig` are not recognized keywords. The blacklist should either specify a pair of ranges, e.g.:

```
chr1:1-100000	chr2:400000-500000
```

or - if you want to blacklist a region regardless of where the second breakpoint is located, the keyword `any`, e.g.:

```
chr1:1-100000	any
```

> WARNING: unknown gene or malformed range: chrY

Do you have some lines where column 1 or column 2 contains only the word "chrY" without coordinates? If Arriba does not find a colon in a column, it assumes it is a gene name rather than a range and looks for a gene named "chrY", which does not exist, of course. I assume that is what is happening here.

> Is the prefix dropped internally by arriba??

Yes. I am not happy about this, but it ensures that annotation, assembly, blacklist, and other input files can be handled correctly, regardless of the flavor (GENCODE, RefSeq, ...). I have some ideas about how to avoid dropping the prefix and still ensuring interoperability. I am positive that Arriba 2.0.0 will handle the prefix better. Thanks for bringing this up again, because it tells me that this really is a nuisance to users and should be fixed.

**Comment by kopardev** [comment]
Thanks for getting back to me. Accordingly, I edited my blacklist file to look like this
```
...
chrX:114281199-114331198	any
chrX:115738950-115838949	any
chrX:116557780-116595566	any
chrX:120879382-120929381	any
chrX:144425607-144475606	any
...
```
And I am still getting these warnings:
```
...
WARNING: unknown gene or malformed range: chrX 114281199-114331198
WARNING: unknown gene or malformed range: chrX 115738950-115838949
WARNING: unknown gene or malformed range: chrX 116557780-116595566
WARNING: unknown gene or malformed range: chrX 120879382-120929381
WARNING: unknown gene or malformed range: chrX 144425607-144475606
...
```
Basically, I get a warning for every single line in my blacklist file. Any idea what I may be doing wrong?

**Comment by suhrig** [comment]
You need to remove the `chr` prefix. How could I forget to mention this? My apologies.

**Comment by suhrig** [comment]
Hi @kopardev, [version 2.0.0 of Arriba has been released](https://github.com/suhrig/arriba/releases/tag/v2.0.0). It deals with the `chr` prefix in the blacklist file more transparently (i.e., does not care whether it's present or not). I'm closing this issue for now. If you still run into problems regarding this subject, feel free to reopen this issue.
