### ISSUE TITLE
Arriba's compatibility with STAR multimap feature with 2.7.6a

### ISSUE THREAD

**Issue by erprateek** [suhrig/arriba#80]
Hi Sebastian,

Great to see your feature being pulled in for STAR 2.7.6a! I am wondering where does Arriba v1.2.0 or develop branch stand with respect to that. Is the feature natively supported by the tool as is and maybe switched on/off with a flag or does it require special handling and needs more development?

Thanks for the amazing contributions!
Prateek

**Comment by suhrig** [comment]
Hi Prateek,

STAR needs to be run with the parameters `--chimOutType WithinBAM` and `--chimMultimapNmax` > 0. The `develop` version of Arriba natively supports the feature. There is no extra parameter that needs to be enabled. Arriba automatically detects whether the old (without multi-mapping chimeras) or the new (with multi-mapping chimeras) alignment algorithm is used. However, it is advisable to use a new blacklist, because the new alignment algorithm gives rise to new artifacts. If you can wait a few days, then you can obtain the new blacklist with the official v2.0.0 release. I only need to finalize the blacklist for hg38 and test the installation routines on Linux/Mac/Docker/Singularity/bioconda. Everything else is complete. I plan to finish this this week or next week.

Regards,
Sebastian

**Comment by erprateek** [comment]
Great thanks Sebastian! I don't mind waiting for a couple of weeks. I can setup everything setup with STAR v2.7.6a meanwhile and probably run the standard evaluation samples. Appreciate the fast TAT on this!
