### ISSUE TITLE
how does arriba detect intergenic fusions ?

### ISSUE THREAD

**Issue by ahy1221** [suhrig/arriba#81]
Hi Suhrig,

There is a sentence In the viral integration sites section of the document that says "by defining a virtual gene, all viral integration sites are reported (even integrations into intergenic regions)". 
I was wondering how does arriba could detect intergenic integrations as the input GTF only containing information about genes?
Actually, I also detected many intergenic virus integration sites from my own data. The gene of those integration sites were annotated as  "RP11-5P15.1(68828),RP11-18A15.1(33530)". In my GTF files (Gencode V22), these two genes were annotated as TEC or lincRNA.

Best,
Yao He

**Comment by suhrig** [comment]
Hi Yao He,

> There is a sentence In the viral integration sites section of the document that says "by defining a virtual gene, all viral integration sites are reported (even integrations into intergenic regions)".

What this sentence means is this: By default Arriba does not report fusions if **both** breakpoints are intergenic or intronic. At lesat one of the breakpoints has to be somewhat close to an exon. Otherwise the `intronic` filter discards the event. Therefore, if you run Arriba on viral genomes, the chances are high that a viral integration site is discarded, because most viral integration sites are intergenic and the GTF file usually does not contain information about genes on the viral genome, such that Arriba regards the viral genome as an entirely intergenic region. The latter can be circumvented by defining an artificial/virtual gene that spans the entire viral genome. This ensures that one of the breakpoints is not intergenic and thus prevents the `intronic` filter from discarding the event. Another way to circumvent it is to disable the `intronic` filter altogether using the parameters `-f intronic`.

> I was wondering how does arriba could detect intergenic integrations as the input GTF only containing information about genes?

Arriba detects fusions/viral integration sites using the mapping coordinates of reads. A GTF file is theoretically not even necessary. Even without a GTF file, you could still detect chromosomal rearrangements - you just would not know which genes are affected by them. The GTF file is primarily used to annotate breakpoints and for filtering of artifacts.

> annotated as "RP11-5P15.1(68828),RP11-18A15.1(33530)"

When a breakpoint is annotated with multiple genes separated by a comma, it means that the breakpoint is between the genes (i.e., intergenic). If you did not declare a virtual gene for the viral genome, you should actually not see such breakpoints, because Arriba would regard both breakpoints as intergenic and should discard them by means of the `intronic` filter.

> In my GTF files (Gencode V22), these two genes were annotated as TEC or lincRNA.

Arriba does not interpret the gene type. Anything that is annotated in the GTF file is considered a gene worth being reported.

Let me know if anything is still unclear.

On a related note: Arriba v2.0.0 is coming out in a few days. This release will feature the ability to detect viral integration sites natively. You will not have to deal with manual creation of a combined human-viral genome assembly. Nor will you have to worry about intergenic integration sites being discarded by the `intronic` filter. Arriba will be able to detect viral integration sites for all RefSeq viral genomes.

Regards,
Sebastian

**Comment by ahy1221** [comment]
Thank you very much! Now I totally understand the output of arriba  1.2.0
I am also looking forward to the release of Arriba v2.0.0. I would be happy to try it on my own dataset for virus detection and give you some feedback about that !

Yao He

**Comment by suhrig** [comment]
Hi Yao He, [version 2.0.0 is out](https://github.com/suhrig/arriba/releases/tag/v2.0.0). I hope you find the new virus detection feature useful. Anyway, I am closing this issue, since the original question has been answered.
