### ISSUE TITLE
Split reads counts lower than the ones visualized in IGV

### ISSUE THREAD

**Issue by slw287r** [suhrig/arriba#83]
Hi Sebastian,

Great to see the joint force of STAR 2.7.6a and Arriba 2.0.0! The detection power of multi-fusing fusions improved significantly over the previous combination in our preliminary test.

While when we compared the results to the former ones we found a little discrepancy of split reads support. There are four split reads supporting the fusion as show in the IGV screenshot (left panel), Arriba 1.1.0 spotted 2 while the newer version gave 1 and discarded it.

<details><summary>AKAP13-NTRK3 fusion</summary>

Column | Arriba2.0.0(discarded) | Arriba1.1.0 (fusion)
-------|-------------|------------
#gene1 | AKAP13 | AKAP13
gene2 | NTRK3 | NTRK3
strand1(gene/fusion) | +/+ | +/+
strand2(gene/fusion) | -/- | -/-
breakpoint1 | 15:86253876 | 15:86253876
breakpoint2 | 15:88670457 | 15:88670457
site1 | CDS/splice-site | splice-site
site2 | CDS/splice-site | splice-site
type | inversion | inversion
<b>split_reads1</b> | 1 | 2
split_reads2 | 0 | 0
discordant_mates | 0 | 0
coverage1 | 99 | 97
coverage2 | 75 | 73
confidence | low | low
reading_frame | . | in-frame
tags | . | .
retained_protein_domains | RII_binding_domain(100%)&#x7c;Protein_kinase_domain(100%) | .
closest_genomic_breakpoint1 | . | .
closest_genomic_breakpoint2 | . | .
gene_id1 | ENSG00000170776 | .
gene_id2 | ENSG00000140538 | .
transcript_id1 | . | .
transcript_id2 | . | .
direction1 | downstream | downstream
direction2 | downstream | downstream
filters | duplicates(1),in_vitro | duplicates(1)
fusion_transcript | . | GAAAAAGATAAGATTAAGGAGAAGGAGAAAGATTCTAAAGACAAGGAGAAAGATAAGAAGACTGTCAACGGGCACACTTTCAGTTCCATTCCTGTTGTGGGTCCC...GGTCAAAATGAAG___CCCAAAGGGAGCCTTCAGGCACATGACACATCATCACTGCCCACGGTCATTATGAGAAACAAGC&#x7c;TTGACGAAGTGAGTCCCAC
peptide_sequence | . | VKMKPKGSLQAHDTSSLPTVIMRNK&#x7c;lDEVSP
read_identifiers | . | E100004865L1C020R0190584185,E100004865L1C011R0342492509,E100004865L1C014R0232104466
</details>

<details><summary>STAR command</summary>

```
$star \
  --runMode alignReads \
  --genomeDir $genomeDir \
  --genomeLoad $gl \
  --readFilesIn $fq1 $fq2 \
  --readFilesCommand zcat \
  --chimMultimapNmax 50 \
  --outSAMtype BAM SortedByCoordinate \
  --outFileNamePrefix $wd/$prefix. \
  --outSAMunmapped Within \
  --outBAMcompression 0 \
  --outFilterMultimapNmax 50 \
  --outFilterMismatchNmax 3 \
  --peOverlapNbasesMin 10 \
  --alignSplicedMateMapLminOverLmate 0.5 \
  --chimSegmentMin 10 \
  --chimOutType WithinBAM \
  --chimJunctionOverhangMin 10 \
  --outSAMstrandField intronMotif \
  --chimScoreMin 1 \
  --chimScoreDropMax 30 \
  --chimScoreJunctionNonGTAG 0 \
  --chimScoreSeparation 1 \
  --alignSJstitchMismatchNmax 5 -1 5 5 \
  --chimSegmentReadGapMax 3 \
  --limitBAMsortRAM 16000000000 \
  --runThreadN 4
```
</details>

<details><summary>Arriba command</summary>

```
$arriba \
  -x $bam \
  -g $gtf \
  -a $ref \
  -b $blacklist \
  -k $known_fusions \
  -t $tag \
  -p $protein_domains \
  -o $wd/$prefix.fusions.tsv \
  -O $wd/$prefix.discarded.tsv
```
</details>

AKAP13-NTRK3 [IGV-Screenshot](https://github.com/suhrig/arriba/files/5443870/AKAP13-NTRK3-STAR3.7.6a.pdf)

STAR-2.7.6a bam (flanking 1000bp, hs37d5 as reference fa) [Dropbox link](https://www.dropbox.com/s/f5aorr2ilcmr870/fs.zip?dl=1)

Thank you for the amazing contributions!
Richard

**Comment by suhrig** [comment]
Hi Richard,

Thank you for the commendable issue reporting! There is one chimeric read missing, because STAR does not align it as a chimeric read. I am not deep enough into STAR's chimeric alignment algorithm to understand why it does not look for a supplementary alignment for the shorter of the two clipped reads (`E100004865L1C011R0342492509`). STAR has two alignment algorithms to detect chimeric reads: the old one is used when `--chimMultimapNmax` is 1, the new one is used, when it is >1. The old one finds the supplementary alignment; the new one doesn't. Arriba 1.2.0 and below used the old one and therefore found the fusion. This is not something that can be fixed on Arriba's side. I recommend to stick with `--chimMultimapNmax 50` (i.e., the new chimeric alignment algorithm), even though in this particular example it seems to be inferior, because overall it is better than the old one. The best thing you could do is to add the AKAP13-NTRK3 fusion to the known fusions list. Arriba should then find it. Admittedly, this is not a real solution, because you sort of "help" Arriba to find it, but if this is a recurrent event, it makes sense to "sensitize" Arriba towards it.

> The detection power of multi-fusing fusions improved

One note about this, in case this isn't clear: The new version does not improve detection of genes that are fused to multiple other genes simultaneously. Older versions of Arriba could detect this just as well. What is new in Arriba 2.0.0 is the ability to detect fusions when the supporting reads do not map uniquely to the genome. Take the example of CIC-DUX4: There are dozens of copies of DUX4 in the human genome. When CIC is fused to DUX4, the supporting reads cannot be mapped unambiguously to a certain copy of DUX4, because the copies are pretty much identical. Previous versions of STAR would simply not report such reads at all and Arriba would not be able to detect them, hence. With `--chimMultimapNmax` > 1, STAR reports such reads as multi-mapping alignments, i.e. as multiple fusions between CIC-DUX4L1, CIC-DUX4L2, CIC-DUX4L3 and so on. It is still impossible to tell which individual copy of DUX4 is involved, but at least one of them is reported by Arriba.

Regards,
Sebastian

**Comment by slw287r** [comment]
Hi Sebastian,

Thank you for your detailed reply, we'll stick with the new algorithm.

Cheers,
Richard
