### ISSUE TITLE
WARNING: unknown gene

### ISSUE THREAD

**Issue by sgiannouk** [suhrig/arriba#84]
Hi Sebastian, 

I recently run Arriba and at the final step (when Loading protein domains from '/arriba_v2.0.0/database/protein_domains_hg38_GRCh38_v2.0.0.gff3') I got the following  list of warnings regarding unknown genes:
WARNING: unknown gene: CPSF3L ENSG00000127054
WARNING: unknown gene: FAM213B ENSG00000157870
WARNING: unknown gene: APITD1-CORT ENSG00000251503
WARNING: unknown gene: RP4-635E18.9 ENSG00000277726
WARNING: unknown gene: C1orf64 ENSG00000183888
WARNING: unknown gene: RSG1 ENSG00000132881
WARNING: unknown gene: FAM231B ENSG00000268991
WARNING: unknown gene: FAM231A ENSG00000237847
WARNING: unknown gene: FAM231C ENSG00000279132
WARNING: unknown gene: RP13-279N23.2 ENSG00000255275
WARNING: unknown gene: PQLC2 ENSG00000040487
WARNING: unknown gene: MINOS1 ENSG00000173436
WARNING: unknown gene: TCEB3 ENSG00000011007
WARNING: unknown gene: TMEM57 ENSG00000204178
WARNING: unknown gene: AIM1L ENSG00000176092
WARNING: unknown gene: ATPIF1 ENSG00000130770
WARNING: unknown gene: RP1-27O5.3 ENSG00000254553
WARNING: unknown gene: YARS ENSG00000134684
WARNING: unknown gene: RP11-244H3.4 ENSG00000271741
WARNING: unknown gene: RP5-864K19.6 ENSG00000274944
WARNING: unknown gene: RP4-533D7.6 ENSG00000278139
WARNING: unknown gene: ZCCHC11 ENSG00000134744
WARNING: unknown gene: C1orf123 ENSG00000162384
WARNING: unknown gene: RP11-446E24.4 ENSG00000256407
WARNING: unknown gene: CYR61 ENSG00000142871
WARNING: unknown gene: SEP15 ENSG00000183291
WARNING: unknown gene: RP5-1052I5.2 ENSG00000267561
WARNING: unknown gene: KIAA1107 ENSG00000069712
WARNING: unknown gene: FAM69A ENSG00000154511
WARNING: unknown gene: TMEM56-RWDD3 ENSG00000271092
WARNING: unknown gene: SARS ENSG00000031698
WARNING: unknown gene: ATP5F1 ENSG00000116459
WARNING: unknown gene: FAM212B ENSG00000197852
WARNING: unknown gene: FAM46C ENSG00000183508
...

I am using the newest version of GENCODE  annotation (version 35). I checked randomly some of those genes and they are not in arriba's gff3 protein domain database.  

Thanx!
Stavros

**Comment by suhrig** [comment]
Hi Stavros,

The protein domains in the GFF3 file are matched to the genes in the GTF file by gene name or gene ID. Thus, when the GFF3 file uses different gene names/IDs than the GTF file, you will see these warning messages. The GFF3 of Arriba was generated using PBase. I am not sure which version of GENCODE (or ENSEMBL) they use, but it's certainly not v35. So it's not surprising that some genes cannot be mapped. All this means is that for listed domains, Arriba will not be able to determine the retained protein domains. Usually, only a handful of genes are affected, so there is no need to use a GTF file that matches the GFF3 file.

Even though this is expected (and mostly harmless) behavior, I am glad you bring this to my attention again, because I discovered a bug while going through some of your examples. As it turns out, the genes are solely mapped by gene name, but not gene ID. Some of the genes in your list (e.g., `SARS`) should be mappable by ID, but Arriba fails to do so. I never noticed, because I am using a GTF file that is closer to the GFF3 file than yours, and therefore, I don't see too many warnings. I have already located the source of the bug, but will need some time to implement a fix, because I am busy with other projects. I will leave this issue open as a reminder until then.

Thanks for making me aware,
Sebastian

**Comment by sgiannouk** [comment]
Great, thanx for the clarifications and the fast reply Sebastian!  
Glad you spotted the bug and I will definitely wait for the next version of Arriba.

**Comment by suhrig** [comment]
I have implemented the fix. It was actually very quick and easy. The number of unmapped protein domains should now be substantially less (I count 34 remaining ones for GENCODE 35). If you don't want to wait for the next release, you can clone the `develop` branch where the fix is available already now. I'm closing this issue as solved. Thanks again for reporting.

**Comment by sgiannouk** [comment]
Thank you once again for the effort and the quick response!
