### ISSUE TITLE
in-frame vs out-of-frame controversial

### ISSUE THREAD

**Issue by duaghk** [suhrig/arriba#85]
Hello. 

I used arriba and other fusion callers(FusionCatcher) and there are some differences about output.

the TPM3-NTRK1 fusion has different type of output.

in arriba, that fusion called as out-of-frame.
(TPM3    NTRK1   -/-     +/+     1:154142876     1:156844363     splice-site     splice-site     inversion       upstream        upstream        12      13      1       43      230     high   ..       duplicates(32)  GAGCAGATTAGACTGATGGACCAGAACCTGAAGTGTCTGAGTGCTGCcGAAGAAAAG___TACTCTCAAAAAGAAGATAAATATGAGGAAGAAATCAAGATTCTTACTGATAAACTCAAGGAG___GCAGAGACCCGTGCTGAGTTTGCTGAGAGATCGGTAGCCAAGCTGGAAAAGACAATTGATGACCTGGAAG|ACACTAACAGCACATCTGGAGACCCGGTGGAGAAGAAGGACGAAACACCTTTTGGG___GTCTCGGTGGCTGTGGGCCTGGCCGTCTTTGCCTGCCTCTTCCTTTCTACGCTGCTCCTTGTGCTCAACAAATGTGGACGGAGAAACAAGTTTGGGATCAACC___GCCCGGCTGTGCTGGCTCCAGAGGATGGGCTGGCCATGTCCCTaCATTTCATGACATTGGGTGGCAGCTCCCTG    out-of-frame    EQIRLMDQNLKCLSAAEEKYSQKEDKYEEEIKILTDKLKEAETRAEFAERSVAKLEKTIDDLE|dtnstsgdpvekkdetpfgvsvavglavfaclflstlllvlnkcgrrnkfginrpavlapedglamslhfmtlggss   .)

but in FusionCatcher, that fusion called as in-frame.
TPM3    NTRK1   known,oncogene,tcga,cancer,tumor,m14,t9,exon-exon       0       19      24      30      BOWTIE;BOWTIE+BLAT;BOWTIE+STAR  1:154142876:-   1:156844363:+   ENSG00000143549 ENSG00000198400 ENSE00003479884 ENSE00003559053 AGATCGGTAGCCAAGCTGGAAAAGACAATTGATGACCTGGAAG*ACACTAACAGCACATCTGGAGACCCGGTGGAGAAGAAGGACGA in-frame

the break point was same, and I checked human genome reference determine that.

the NTRK1 breakpoint are start of exon 10. 

I don't know which type is right. 

Could you give me some help??

I used hg19.fa for reference fasta, and gencode.v19.annotation.gtf for annotation.

Thanks.

**Comment by suhrig** [comment]
Hello,

It is in-frame. So Arriba is wrong. I received an e-mail recently from another user about precisely this pair of fusion genes. I am already working on a fix, but have not completed it yet due to lack of time. Here is what I wrote to the other user:

This is a bug ... sort of. In Arriba, transcript selection and reading frame prediction are two separate steps: First, Arriba tries to determine which transcript is expressed as part of the fusions. It does so by looking at the splice pattern of reads. Once it has decided on a transcript, it determines the reading frame of the 5' and 3' transcript and translates the fusion sequence. In your example, it decided that the NTRK1 transcript ENST00000497019.2 is the one that is transcribed as part of the fusion. This transcript has a different reading frame than the the canonical one - it translates to TLTAHLET... instead of DTNSTSG.... Since the peptide sequence of the *selected* transcript does not match the peptide sequence of the translated fusion sequence, Arriba considers it out-of-frame. Technically, this is correct, since the fusion with transcript ENST00000497019.2 is out-of-frame with respect to this transcript. However, Arriba should most likely have chosen a different transcript to begin with. My guess is that Arriba cannot unambiguously decide on a transcript, because all of the NTRK1 transcripts match the splice patterns of the reads equally well. In this situation Arriba picks the transcript with the greatest length or the longest coding sequence. In this example, this is a poor choice.

I have seen this issue before, but dismissed it as a rare occurrence. Thank you for bringing this to my attention again. Apparently, it is not so rare and I need to revisit the transcript selection code and change it in a way that preferably in-frame transcripts are chosen whenever there is ambiguity in the transcript selection. This is not easy, however, because the code for transcript selection and peptide prediction are separate, and actually the latter builds on the former, so the code would have to go back-and-forth between the two. I will think about this some more and hopefully come up with a practical solution.

**Comment by duaghk** [comment]
@suhrig 
Thanks for your kindness. 
I wish that you find the solution soon.

**Comment by ahdee** [comment]
@suhrig Hi any chance you have addressed this issue yet?  I been finding several examples as well where most of my callers are detected in frame but arriba is outputing as either out of frame or with a ".".  Thanks! This is the only caller that is the most robust amoung 5 other callers, other than this issue with frameness.

**Comment by suhrig** [comment]
Hi @ahdee,

Reading frame prediction should be better since version 2.1.0. If you are already using the latest version, can you share the output lines of Arriba with incorrect reading frames, so I can have a look what may be going wrong? If you don't want to post the lines here publicly, you can send me an email: s dot uhrig at dkfz dot de

An empty value (`.`) means the reading frame could not be determined. There are many reasons for this. The most frequent ones are that the fusion transcript does not involve coding exons or that the transcript sequence is missing information (denoted as `...`) near the fusion junction. In the latter case, it may help to enable the switch `-I`. This switch instructs Arriba to fill gaps with information from the assembly if the supporting reads do not cover the whole transcript. 

Regards,
Sebastian

**Comment by ahdee** [comment]
Hi Sebastian, 
that would be awesome. I will put together a few examples and send via email to you.  I'm using arriba 2.10

**Comment by suhrig** [comment]
@ahdee: Have you found the time to collect some examples? I do not recall receiving an e-mail from you (or it ended up in spam). I am close to releasing the next version and could include fixes related to reading frame prediction if your examples point out a bug.

**Comment by ahdee** [comment]
thanks for following up!  Sorry I totally forgotten about this. I'm actually out of town at the moment.  Is it too late if I send it next week?

**Comment by suhrig** [comment]
No worries. Just send it when you find the time. If it's too late for the upcoming release I will put it into the next one.
