### ISSUE TITLE
fusions detected in both normal and tumor, on same gene at the same breakpoint

### ISSUE THREAD

**Issue by MariusGheorghe** [suhrig/arriba#87]
Hi Sebastian,

How's it going? All good I hope. 

I was playing with Arriba on some samples for which we have tumor **and** normal RNA. Part of the question I was trying to answer myself was: how many of the gene fusions detected in tumorous tissue are actually present in the normal tissue? But I found some weird behavior which I do not know if it reflect reality/biology or it's an artifact of the tool. Before going through the attached table with preliminary results, please keep in mind that the normal RNA comes from the same tissue as the tumorous tissue, but "sufficiently far away" from the tumor. 

What I've did to generate the table below was to collect all gene fusions (that were **not** discarded) from four samples, both detected in normal RNA and in tumor RNA, and merge them per sample between the tumor and normal, based on multiple columns: `gene1`, `gene2`, `breakpoint1`, `breakpoint2`, `strand1(gene/fusion)`, `strand2(gene/fusion)`. So, a pretty stringent merging criteria. This is what I got: [common_gene_fusions_per_sample.xlsx](https://github.com/suhrig/arriba/files/5480324/common_gene_fusions_per_sample.xlsx). Sorry if the formatting went bananas, but apparently `.tsv` is not supported and I don't really use Excel.

I left the breakpoints where the fusion was detected in case that info helps you, but I removed the strands (so let me know if you need that info also). As you can see, those common gene fusions occur on the same gene **and** exactly at the same breakpoint **and** on the same strand (gene/fusion) in both tumor and normal. The confidence score is mainly the same across these common gene fusions (albeit only for one it is `high`). 

I could not provide you with the fusion nucleotide sequence nor the predicted peptide sequence due to data sensitivity, but I've calculated a similarity score between the strings of the two fusion transcripts (tumor vs. normal) and the two predicted peptide sequences (tumor vs. normal). This score ranges from 0 (completely different) to 1 (identical strings) and it is based on string distances. As you can see, the resulting transcripts and peptides are highly similar.

Now, I do not know if this is actually going on biologically, possibly contamination of normal tissue with tumorous tissue, or it is some systematic artifact or what it is. I do not think that it is a gene inversion, because the strand of gene/fusion is the same. Could it be an exon deletion. Do you have some insight as of the biological interpretation and/or computational interpretation? Thanks a lot in advance and let me know if you need more info.
Have a good day!

Marius

**Comment by suhrig** [comment]
Hi Marius,

The examples you sent me are mostly (internal) tandem duplications. If you also observe them in normal tissue, most likely they are rare germline variants and not relevant to cancer. Arriba removes common germline ITDs by means of its blacklist, but rare variants can only be removed with the help of a matched normal control, because the blacklist only includes the variants that were observed in the samples I used to build the blacklist. If you don't want ITDs to be reported, you can disable the ITD filter with `-f internal_tandem_duplication`. However, there are two important examples where ITDs matter: (1) some cancer types are frequently driven by ITDs (e.g., FLT3, BCOR, ERBB3) and (2) some rare germline ITDs can be pathogenic (e.g. BRCA1/2, TP53) and are just as interesting in the context of cancer as somatic variants.

If you see a lot of those, I should probably tweak the blacklist to include more ITDs. I will run some tests and possibly update the blacklist with more stringent ITD filtering for the next release.

Are these samples from patients of Caucasian descent? The blacklist was mostly trained on Caucasian patients and is best at removing germline variants from those.

Regards,
Sebastian

**Comment by MariusGheorghe** [comment]
Hi Sebastian,

Thank you for the detailed explanation. It makes sense. Now, the thing is that we are not sure what is the level of tumor in normal contamination, so those gene fusions might very well be specific **only** to the tumor. We are currently trying to put in place a tool to detect this level of contamination, so I guess when that is done we can have another indicator.

I don't think we will discard those entries, because as you point out, we might be missing out on some important data. However, for the four samples summarized in this issue, we got 41.34% of the gene fusions detected in tumor RNA that are IDTs and 34.48% when using normal RNA. It is a pretty significant subset IMO. 
Unfortunately, I do not know the ethnicity of the patients. Sorry for that. 

If you want, I can test your next release with an updated blacklist on the same data and see if the number of IDTs decreases. Just let me know. I'd be glad to help.

Thanks again and have a good weekend!

Marius

**Comment by suhrig** [comment]
I doubt that this is tumor-in-normal contamination. Arriba only calls ITDs when the allele frequency is high. Contamination is usually only found in trace amounts and thus with a low allele frequency - unless this is a haematologic disease and the control sample is blood and could not be cleared from tumor cells.

34-41% is a lot. Another explanation could be that your sequencing protocols give rise to a particular type of artifact that looks like small tandem duplications. What sequencing platform did you use? If you can share FastQ files from nonsensitive samples affected by this problem I am happy to have a look at them myself and try to tweak the filters.

**Comment by MariusGheorghe** [comment]
Ahum! Okay, did not know that about Arriba. Thanks for the details. The samples come from breast cancer, so no haematological cancer or disease. Was worried about tumor in normal contamination due to the fact that they took the sample from breast and "sufficiently far away" is relative from patient to patient. 

Some details about the sequencing: 

- samples were flash frozen

- sequencing platform used was Illumina NovaSeq6000. 

- sequencing library for RNA was:  mRNAseq: ~250-300 bp insert cDNA library

- non strand-specific sequencing library.

- number of reads: RNA Normal; 60Mx2, RNA Cancer;120Mx2

Unfortunately, for now, the only data we got with matching normal is all sensitive. So, I cannot share the FASTQ files :disappointed: 
But let's think about an alternative. Maybe some benchmarking/parameter tuning system that I can run on our side?
Thanks again for your help.

Marius

**Comment by suhrig** [comment]
Hi Marius,

I created a new blacklist with more strict filtering of ITDs:

https://c.1und1.de/@854294030366802154/F5BioX8AR86j7E2n0a6gWw

It would be helpful if you could give me some feedback about how much this alleviates the problem with your samples. On my benchmark samples, it reduced the number of ITDs by ~30%. Since my benchmark dataset is enriched with somatic ITDs, the effect on germline ITDs may be even higher (maybe 40%).

If absolutely necessary I could make it even more strict, but this would come at the risk of accidentally blacklisting somatic ITDs, so ideally I would like to keep it as lenient as it is.

Regards,
Sebastian

**Comment by MariusGheorghe** [comment]
Hi Sebastian,

I've downloaded the file from the link provided.

Will setup the analyses with the new blacklisted regions and run them when time allows it. Right now, I'm pretty busy with other projects, but hopefully something will break down and I'll have time to run the analyses :grin: 

I will keep you posted with the results. Thank you for taking time to do that.

Marius

**Comment by MariusGheorghe** [comment]
Hi Sebastian,

I've ran the same analyses using the new version of the blacklisted regions database. Indeed, there is a significant reduction of ITDs:
```
# new blacklist
> Normal tissue
5.13 (%)
> Tumorous tissue
12.7 (%)

# old blacklist
> Normal tissue
34.5 (%)
> Tumorous tissue
41.35 (%)
```
are those numbers according to your expectations?

Marius

**Comment by suhrig** [comment]
Hi Marius,

Thanks a lot for the feedback. I am very satisfied with the new results. 5-10% is still quite a lot, but any further improvement should be hard to accomplish. I have mentioned ITDs as a frequent type of false positives in the manual to warn users about them and will leave it at that for now. If I can get my hands on a bigger training cohort (currently "only" 2000+ samples), I can enlarge the blacklist with more ITDs that are common in the population and improve the blacklist further.

Regards,
Sebastian

**Comment by MariusGheorghe** [comment]
Hi Sebastian,

I also think it's a significant improvement. Thank you very much for taking your time and updating the blacklisted database.
Let's keep in touch for further issues/updates.

Have a happy new year!

Marius
