### ISSUE TITLE
Fusion Sites Overlaping RepeatMasker DNA Repeats

### ISSUE THREAD

**Issue by DarioS** [suhrig/arriba#92]
Sometimes, one segment of a split read maps to a repeat such as a LINE or SINE. Is such a fusion plausible? SINE repeats are present in thousands of places in the reference genome and the best mapping might be quite similar to the second best and other ones.

![image](https://user-images.githubusercontent.com/631218/101728880-4d26ce80-3b0b-11eb-80d0-f503cb92e318.png)

The location of the other part of the read is far from any exons for KNTC1 and inside an Alu repeat.

![image](https://user-images.githubusercontent.com/631218/101729438-40ef4100-3b0c-11eb-8ec7-f6ff557074f0.png)

None of the reads belonging to the Alu retrotransposon (pink reads) are spliced to any exons of KNTC1 (blue reads), so it's probably wrong that arriba joins all of the exons of KNTC1 in the PDF plot. The soft-clipped reads do map perfectly to CLIP1 though.

![image](https://user-images.githubusercontent.com/631218/101731879-65e5b300-3b10-11eb-815e-3480c4f0313a.png)

So, even with all the complex filters already in arriba, it seems there are more to add in future! This seems to be a similar mechanism described in [Alu Elements: At The Crossroads Between Disease and Evolution](https://portlandpress.com/biochemsoctrans/article/41/6/1532/68203/Alu-elements-at-the-crossroads-between-disease-and)

**Comment by suhrig** [comment]
True, the fusion does not really involve KNTC1 (apart from disrupting the gene body). There is no fusion between CLIP1 and KNTC1 per se - not only are all of the fusion reads intronic, they are on the antisense strand as well. But if the Alu sequence is not annotated in the gene model that you use, then Arriba assigns the next best hit, which is KNTC1 in this case. You can also see this from the fusion plot in that the genes are fused head-to-head.

It's not obvious to tell if CLIP1 is fused with this particular Alu copy or another one elsewhere in the genome, unless there is a uniquely identifying SNP that distinguishes this copy from others. And then again, it could be a false positive prediction altogether. You can search for other reads in KNTC1 that link it to CLIP1 (e.g., a reciprocal translocation) for confirmation. The best confirmation would be a matched whole-genome sequencing sample with a genomic breakpoint in the vicinity - if happen to have that data.

Yes, filters can always be improved. The types of artifacts are unlimited, it seems.

**Comment by DarioS** [comment]
Now that you mention it, closest_genomic_breakpoint1 and closest_genomic_breakpoint2 are . for that variant and most others. Why do some variants have a dot value but others have values like chr2:186503623(1071) ? Also, what's the number inside the brackets?

**Comment by suhrig** [comment]
A dot indicates that there is no SV that matches the fusion. There is a higher chance that it is a false positive, but not necessarily. There are exceptions, for example: the SV caller may have missed the SV, or it's a complex rearrangement like pos1 -> pos2 -> pos3, which is reported by the SV caller as two separate SVs pos1 -> pos2 and pos2 -> pos3 and by Arriba as pos1 -> pos3 (and thus cannot be matched to the SVs), because the spliceosome skips the intermediate breakpoints.

The value in the parentheses is the distance to the breakpoint. Should've mentioned this in the manual ...

**Comment by suhrig** [comment]
I used data from [this study](https://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-15-675), which compares various polyA-selection kits and ribo-depletion kits. I don't see a bias towards intergenic breakpoints for any of the protocols (or towards any other breakpoint sites for that matter):

![site_frequency](https://user-images.githubusercontent.com/10560654/108774117-8d6ce900-755f-11eb-8a9e-87b3f9e9609f.png)

The overall number of fusion predictions are also similar. Moreover, when I annotate the breakpoints with SINE/LINE/Alu repeats from the UCSC RepeatMasker track, I don't see an enrichment in the ribo-depleted libraries. So I'm having a bit of trouble replicating your observations.

How severe is this issue in your samples? What fraction of the calls is located in repeats? It could be that there really is a fusion with a repeat, just not with the one where STAR put the reads. This would explain why the breakpoints are not confirmed by structural variants. The breakpoints reported by Arriba may be wrong, but the fact that some gene is fused to a repeat would still be correct.

Regarding your question about a benchmark with other tools on ribo-depleted samples: I realized that such a benchmark would be pointless, because most fusion detection tools do not call breakpoints in intronic or intergenic regions.

**Comment by DarioS** [comment]
About one-third of fusion calls per sample have the splice-site to intron and it always appears to be to an Alu element. It's similar to the bar chart displayed above. I have matched adjacent normal RNA-seq as well, so I could check if these Alu are present in the normal sample and simply because natural population variation between people not captured in the human reference genome.
