### ISSUE TITLE
Running arriba without blacklist is not possible

### ISSUE THREAD

**Issue by Bonder-MJ** [suhrig/arriba#93]
Hello!

Thanks for the great tool! 

I was trying to use the tool without the blacklist to see what would happen on our data. But I get the following error:
`ERROR: filter 'blacklist' enabled, but missing option: -b`

I installed arriba via bioconda and try to use the following command:
`arriba -x bam -o fusion.txt -g geneAnnotation.gtf -a referenceGenome.fa -d wgsCalls.tsv`

**Comment by suhrig** [comment]
Hi,

You must run it with the additional parameter `-f blacklist` to disable the blacklist filter and get rid of the error. I decided to put this extra hurdle in the user's way so that users do no accidentally forget to pass the blacklist as a parameter, because without the blacklist, Arriba's accuracy suffers a lot. I wanted to avoid the situation that users accidentally run the tool without the blacklist and then wonder why it produces so many false positives. Thank you for your feedback. To avoid confusion of other users, I will adapt the error message to reflect the fact that the additional parameter is required.

Regards,
Sebastian

**Comment by Bonder-MJ** [comment]
Hi,

Thanks! It works now. 

Just a quick comment. For the -d WGS file I had a file with windows enters (\r\n) this caused warnings in the arriba run stating it couldn't read lines in the tabulated file. Probably good to capture the "\r" that is causing this. As I changed the end of line sign and now it works without warnings.

Best,
Marc

**Comment by suhrig** [comment]
> Probably good to capture the "\r" that is causing this.

Good idea. Will do for the next release.

**Comment by suhrig** [comment]
Hi Marc,

I'm closing this issue, unless you have further questions ...

I edited the error message to clearly state how the blacklist can be disabled. And I implemented a fix that deals with CRLF line breaks properly. Both changes can now be found in the `develop` branch and will be part of the next stable release. Thanks again for bringing these things to my attention.

Regards,
Sebastian
