### ISSUE TITLE
Do you recommend to run STAR in two-pass mode?

### ISSUE THREAD

**Issue by mkazanov** [suhrig/arriba#95]
STAR manual contains recommendation about two-pass run for better junction detection sensitivity.
Do you recommend to run STAR (inside Arriba pipeline) in two-pass mode?

**Comment by suhrig** [comment]
You can do whatever you prefer. For the sake of fusion detection, two-pass mode does not improve the results in my experience. So I usually do not use it, because it doubles the CPU time. However, it should not hurt either. You might see some more read-through fusions, which are mostly false positives, but I expect the difference to single-pass to be marginal.

BTW, you can find the recommended alignment parameters in the [manual](https://arriba.readthedocs.io/en/latest/workflow/#demo-script) or the [demo script](https://github.com/suhrig/arriba/blob/master/run_arriba.sh). You are free to adapt parameters that are not related to chimeric alignment according to your preferences / needs. I try to make Arriba robust to different parameters, because I understand that different users have different requirements w.r.t. their data and might not want to align data anew just for the sake of fusion detection, but rather prefer to use existing alignments that are anyway generated as part of a regular RNA-Seq workflow.

**Comment by mkazanov** [comment]
Thanks!
