### ISSUE TITLE
Input for arriba

### ISSUE THREAD

**Issue by maximus3219** [suhrig/arriba#98]
In the manual of Arriba, it is required to have input from --chimOutType WithinBAM. 

Could I use the default output from --chimOutType Chimeric.out.junction to give Arriba as input instead, together with Aligned.SortedbyCoordinate.bam?

Thank you.

Best Regards,
Maximus

**Comment by suhrig** [comment]
Hi Maximus,

Arriba requires chimeric reads in SAM/BAM/CRAM format. Although the `Chimeric.out.junction` format is the default, it is not supported by Arriba, because it is a proprietary file format of STAR. The SAM format on the other hand is a standards-compliant format, which is why Arriba was developed for it. This means you have two options:

`--chimOutType WithinBAM`, which stores the chimeric alignments in the main BAM file `Aligned.out.(sortedByCoord.)bam`

`--chimOutType SeparateSAMold` which stores the chimeric alignments in a separate SAM file `Chimeric.out.sam`

Note that the latter is deprecated. It will not be supported by STAR in the future and also lacks quite a few chimeric reads that are found, when `WithinBAM` is used (because different alignment algorithms are used for `WithinBAM` and `SeparateSAMold`).

Regards,
Sebastian

**Comment by maximus3219** [comment]
Hi Sebastian,

Would there be any difference in fusion detection result with 1 pass mode or 2 pass mode of STAR aligner?

Thank you.

Best Regards,
Maximus

**Comment by suhrig** [comment]
For the sake of fusion detection, two-pass mode does not improve the results in my experience. So I usually do not use it, because it doubles the CPU time. However, it should not hurt either. You might see some more read-through fusions, which are mostly false positives, but I expect the difference to single-pass to be marginal. So you can do whatever you prefer.

**Comment by suhrig** [comment]
I'm also closing this issue, since all questions have been answered as far as I can see. Feel free to reopen if not.
