### ISSUE TITLE
Quantification of expression for Gene1-Gene2 fusion, and wild type Gene1 and Gene2

### ISSUE THREAD

**Issue by mkazanov** [suhrig/arriba#99]
Hi Sebastian,

In our tasks after the detection of the let say Gene1-Gene2 fusion,
we are usually interested whether the wild type Gene1 and Gene2 are also expressed.
So we need to somehow quantify the expression of the fusion Gene1-Gene2, as well as the Gene1 and Gene2 transcripts.
Can Arriba can somehow provide this information? Or could you recommend any options on how to do it?

Thanks
Marat

**Comment by suhrig** [comment]
Hi Marat,

Two ways to do this:

- You can sum `split_reads1` + `split_reads2` and compare the sum to the values in `coverage1` and `coverage2`. The former is the expression of the fusion; the latter is the expression of the fusion + the wild-type gene1 and gene2, respectively. This method is fairly inaccurate, however, because the split reads are often highly underestimated, because STAR fails to align some split reads and because Arriba discards some as alignment artifacts (see column `filters`). So at best, this is going to give you a rough approximation of the wild-type expression. I guess if the split reads are much lower, it is fair to say that the wild-type is also expressed. In fact, in most cases the wild-type is also expressed, because usually only one allele is involved in the fusion.

- The other way is to look at the coverage in the [output of draw.fusions.R or in IGV](https://arriba.readthedocs.io/en/latest/visualization/). The exons that are expressed as part of the fusion are usually expressed at a markedly higher level than those not involved. The difference between the two is the expression of the wild-type allele. This method is harder to automate, however, and also far from fool-proof, because usually you can only notice the different between fusion- and wild-type expression when it is large.

To complicate the matter further, you also have to think about expression coming from contaminating normal tissue. RNA-Seq samples are typically not 100% pure tumor tissue (unless you are working with cell lines). There is almost always some contamination from surrounding normal tissue from where the lesion was isolated. It can be very difficult (near impossible, really) to subtract the expression coming from the normal tissue, because you don't really know how high the expression in the normal tissue is.

And finally, when you are dealing with a complex rearrangement where a gene was shattered into many pieces and stitched back together with multiple other genes, it can be very hard to tell whether there even is a wild-type allele left. Only long-read sequencing could answer this.

Regards,
Sebastian

**Comment by suhrig** [comment]
Correction: After having a look at the source code that computes the coverage, you should not sum up the columns `split_reads1` and `split_reads2`, because supplementary alignments are not taken into consideration for computing the coverage. Doing so would overestimate the fusion expression. Instead you should simply compare `split_reads1` to `coverage1` and `split_reads2` to `coverage2`.

**Comment by mkazanov** [comment]
Sebastian,

Thank you for the detailed answer!
I saw in Arriba docs that `coverage` is calculated including all fragments (even duplicates), while `split_reads` are calculated taking into account only non-discarded reads (as I understand duplicates are removed). Thus, if I understand correctly from Arriba docs these columns (`coverage` and `split_reads`) are presented in different "units". Is it correct to directly compare them in this case?
I would like also to ask - do I understand correctly that `split_reads` are reads that are broken by fusion junction, while `discordant_mates` are read pairs, for which junction position is located between the reads (one read is located on gene1 and the second read on gene2)?

**Comment by suhrig** [comment]
All of your assumptions are correct.

You could divide the `coverage` by the duplication rate of the sample to get more comparable numbers. Arriba does not compute it, so you will have to compute it yourself. Still, this won't eliminate all of the biases (STAR and Arriba still discard quite a bunch of the reads for other reasons). I guess the most accurate way to quantify fusion expression would be to create a synthetic genome composed of the concatenated fusion genes and doing a realignment of all reads against this, then counting the reads that map across the junction. However, this is a lot of work to implement and computationally expensive. I doubt that the extra computational costs are worth the marginal increase in accuracy in most cases.

I just thought of another way that can be thought of as a compromise: You could take the reads mentioned in the `read_identifiers` column, extract them from around the fusion breakpoints into a separate BAM file and compute the coverage around the breakpoints. Then you could do the same for the whole BAM file. To reduce stochastic noise a bit, you could compute the average coverage in a window of 20bp adjacent to the breakpoints. This way, the only thing that will be missing are the fusion reads that STAR failed to align. Other than that, the numbers will be perfectly comparable.

**Comment by mkazanov** [comment]
I see. Thank you very much for your answers!

**Comment by xie186** [comment]
> Correction: After having a look at the source code that computes the coverage, you should not sum up the columns `split_reads1` and `split_reads2`, because supplementary alignments are not taken into consideration for computing the coverage. Doing so would overestimate the fusion expression. Instead you should simply compare `split_reads1` to `coverage1` and `split_reads2` to `coverage2`.

Hi @suhrig, what do you mean "compare `split_reads1` to `coverage1` and `split_reads2` to `coverage2`" here? For example, if I want to compare two samples, do you have any suggestions what formula I should use to quantify the gene fusion? Thanks in advance.

**Comment by suhrig** [comment]
Hi @xie186,

By "compare" I meant divide `split_reads1` by `coverage1` and `split_reads2` by `coverage2`. This will tell you what fraction of the expression comes from the fusion. Actually, you will get two fractions - one for each breakpoint. The truth is somewhere in-between, probably. As explained above, quantification of fusions is fairly inaccurate (unless the fusion is expressed at a high level) due to stochastic noise and the difficulty of finding all fusion-supporting reads.

The method of dividing split reads by coverage is really easy to implement, but it is also the most inaccurate one. The most accurate method would be to create a synthetic genome consisting of the fusion sequence, aligning all reads to this synthetic genome, somehow removing alignment artifacts, and finally counting the reads mapping across the junction. This is computationally very demanding, however.

There is a middle-ground solution: I pushed a [script](https://github.com/suhrig/arriba/blob/develop/scripts/extract_fusion-supporting_alignments.sh) to the repo recently, that lets you extract all fusion supporting-reads from the BAM file. You can use this script to generate one BAM file per fusion prediction and measure the coverage at the fusion breakpoints. You can then compare this to the coverage at the fusion breakpoints in the regular BAM (`Aligned.sortedByCoord.out.bam`) to get a sense of how much the fusion contributes to the overall expression. There is one catch, though: Arriba only counts supporting reads up to a limit of 300. For performance reasons, it stops counting beyond that. You can increase this limit by setting the parameter `-U` to a high value, for example 10000.

Regards,
Sebastian

**Comment by xie186** [comment]
Thank you, @suhrig!
